# -*- coding: utf-8 -*-
"""PFE_12_decision_engine_recommendations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0ysgPQ5Xdm1-_cwO3krUve7vvg3WLZH

# PFE_12_decision_engine_recommendations.ipynb

## Objective
Create a Decision Engine that transforms model outputs and simulation results into clear business recommendations for email sending IP optimization.

## Main Goal
Given an IP strategy or simulation scenario, the system should decide on actions like continuing, increasing/reducing volume, adjusting time gaps, stopping growth, or stopping sending temporarily.

## STEP 1 — Import libraries

First, we'll import all the necessary Python libraries for data manipulation, analysis, and visualization.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options for pandas DataFrames
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

"""## STEP 2 — Load simulation results from PFE11

We will load a sample simulation result file. This file represents the output of a hypothetical IP sending strategy over several days, including various metrics and predicted risks.

**Note:** If you have actual simulation results, replace the path to `simulation_results_moderate_strategy.csv` with your file path. If the columns mentioned in the prompt are not present in your actual data, you may need to add placeholder columns or adjust the subsequent steps.
"""

try:
    # Try to load a moderate strategy simulation as demo data
    simulation_df = pd.read_csv('/content/simulation_results_moderate_strategy.csv')
    print("Loaded 'simulation_results_moderate_strategy.csv' as demo data.")

    # Standardize column names to snake_case and lowercase for consistency with rule logic
    simulation_df.columns = simulation_df.columns.str.replace(' ', '_').str.lower()

    # Rename specific columns to match expected names in rules
    simulation_df = simulation_df.rename(columns={
        'estimated_sent_ratio': 'sent_ratio',
        'estimated_risk_probability': 'risk_probability',
        'estimated_error_probability': 'error_probability',
        'predicted_risk_zone': 'predicted_risk_zone'
    })

    # Create specific risk/error probability columns from generic ones or predicted_risk_zone
    # This is a heuristic to make the rules function work with available data from the CSV.
    # In a real scenario, these would come from specific prediction models.
    simulation_df['risk_probability_ratelimit'] = 0.0
    simulation_df['risk_probability_dangerous'] = 0.0
    simulation_df['risk_probability_netblock'] = 0.0
    simulation_df['error_probability_spf'] = 0.0
    simulation_df['error_probability_dkim'] = 0.0

    # Based on 'predicted_risk_zone', assign the 'risk_probability' to the most relevant specific risk type.
    # This is an interpretation since specific risk types are not explicitly in the CSV.
    simulation_df.loc[simulation_df['predicted_risk_zone'] == 'critical', 'risk_probability_netblock'] = simulation_df['risk_probability']
    simulation_df.loc[simulation_df['predicted_risk_zone'] == 'dangerous', 'risk_probability_dangerous'] = simulation_df['risk_probability']
    simulation_df.loc[simulation_df['predicted_risk_zone'] == 'high', 'risk_probability_ratelimit'] = simulation_df['risk_probability']

    # For SPF/DKIM, if there's a generic error probability, distribute it.
    # Assuming if error_probability is high, it could be either SPF or DKIM.
    simulation_df['error_probability_spf'] = simulation_df['error_probability'] * 0.5 # Distribute for demo purposes
    simulation_df['error_probability_dkim'] = simulation_df['error_probability'] * 0.5 # Distribute for demo purposes

except FileNotFoundError:
    print("Simulation results file not found. Creating dummy data for demonstration.")
    # Create dummy data if the file is not found
    data = {
        'day': range(1, 11),
        'daily_volume': [10000, 15000, 20000, 25000, 30000, 32000, 33000, 34000, 35000, 36000],
        'volume_per_drop': [1000, 1000, 1200, 1250, 1500, 1600, 1650, 1700, 1750, 1800],
        'cumulative_volume': [10000, 25000, 45000, 70000, 100000, 132000, 165000, 199000, 234000, 270000],
        'limit_usage_ratio': [0.5, 0.6, 0.7, 0.8, 0.85, 0.92, 0.95, 0.97, 0.98, 0.99],
        'growth_rate': [0.1, 0.5, 0.33, 0.25, 0.2, 0.06, 0.03, 0.03, 0.03, 0.03],
        'estimated_sent_ratio': [0.95, 0.94, 0.93, 0.92, 0.88, 0.85, 0.75, 0.68, 0.65, 0.60],
        'risk_probability_ratelimit': [0.05, 0.1, 0.2, 0.3, 0.4, 0.65, 0.7, 0.75, 0.8, 0.85],
        'risk_probability_dangerous': [0.01, 0.02, 0.03, 0.05, 0.08, 0.15, 0.25, 0.5, 0.72, 0.8],
        'risk_probability_netblock': [0.01, 0.01, 0.02, 0.03, 0.05, 0.1, 0.2, 0.3, 0.4, 0.55],
        'error_probability_spf': [0.01, 0.01, 0.02, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08],
        'error_probability_dkim': [0.01, 0.01, 0.01, 0.02, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07],
        'predicted_risk_zone': ['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High', 'Critical', 'Critical', 'Critical'],
        'predicted_error_type': ['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'Netblock']
    }
    simulation_df = pd.DataFrame(data)
    # Rename columns to match expected input for generic risk/error probability
    simulation_df['risk_probability'] = simulation_df[['risk_probability_ratelimit', 'risk_probability_dangerous', 'risk_probability_netblock']].max(axis=1)
    simulation_df['error_probability'] = simulation_df[['error_probability_spf', 'error_probability_dkim']].max(axis=1)
    simulation_df['sent_ratio'] = simulation_df['estimated_sent_ratio'] # Aligning column name for consistency with rules

display(simulation_df.head())

"""## STEP 3 — Load or create safe historical thresholds

We define several thresholds based on historical data or expert knowledge. These thresholds will be used in our decision rules to determine the appropriate actions.

**Note:** These values are examples. In a real-world scenario, these should be derived from your `model_growth_rate.pkl`, `model_initial_volume.pkl`, `model_drops_per_day.pkl`, `model_time_gap_min.pkl`, `model_max_safe_volume.pkl` models or historical analysis.
"""

# --- Thresholds for Decision Rules ---

# Rule 1: RateLimit risk
RATE_LIMIT_PROB_THRESHOLD = 0.60 # If RateLimit probability > 60%

# Rule 2: Dangerous risk
DANGEROUS_RISK_PROB_THRESHOLD = 0.70 # If Dangerous risk probability > 70%

# Rule 3: Limit pressure
LIMIT_USAGE_RATIO_THRESHOLD = 0.90 # If limit_usage_ratio > 90%

# Rule 4: High growth (assuming safe historical growth is known)
# For demo purposes, we'll set a hypothetical safe growth rate.
SAFE_HISTORICAL_GROWTH_RATE = 0.20 # If growth_rate > safe historical growth

# Rule 5: Low sent ratio
SENT_RATIO_THRESHOLD = 0.70 # If sent_ratio < 70%

# Rule 6: Netblock danger
NETBLOCK_PROB_THRESHOLD = 0.50 # If Netblock probability > 50%

# Rule 7: SPF/DKIM issue
# Assuming a combined high probability for either SPF or DKIM indicates an issue
SPF_DKIM_PROB_THRESHOLD = 0.05 # If SPF or DKIM probability is high (e.g., > 5%)

"""## STEP 4 — Load risk/error predictions if available

The simulation results DataFrame already contains `risk_probability`, `error_probability`, `predicted_risk_zone`, and `predicted_error_type` columns. Therefore, separate loading of prediction files is not required at this stage. These columns are assumed to be generated by the `PFE6` (Risk prediction model) and `PFE7` (Error prediction model) and integrated into the simulation output by `PFE11` (Simulation Engine).

## STEP 5 — Create decision rules

Now we will define a function that applies the decision rules based on the thresholds and predicted risk/error probabilities. This function will take a row of the simulation DataFrame as input and return a decision and a main reason for that decision.
"""

def apply_decision_rules(row):
    """
    Applies a set of predefined decision rules to a single row of simulation data
    and returns a decision and a main reason.
    """
    decision = "Continue sending"
    main_reason = "Low risk, good performance"
    recommendation = "Continue current strategy."

    # Rule 6 — Netblock danger
    # Check for specific error probabilities if available
    # Note: Column names are now lowercase with underscores due to preprocessing in STEP 2.
    if 'risk_probability_netblock' in row.index and row['risk_probability_netblock'] > NETBLOCK_PROB_THRESHOLD:
        decision = "Stop sending temporarily"
        main_reason = f"High Netblock risk ({row['risk_probability_netblock']:.1%})"
        recommendation = "Stop sending immediately. Investigate and resolve Netblock issues before resuming."

    # Rule 2 — Dangerous risk (General high risk probability)
    elif 'risk_probability_dangerous' in row.index and row['risk_probability_dangerous'] > DANGEROUS_RISK_PROB_THRESHOLD:
        decision = "Stop growth"
        main_reason = f"Dangerous risk ({row['risk_probability_dangerous']:.1%})"
        recommendation = "Stop any volume growth immediately. Consider reducing volume if risk persists."

    # Rule 1 — RateLimit risk
    elif 'risk_probability_ratelimit' in row.index and row['risk_probability_ratelimit'] > RATE_LIMIT_PROB_THRESHOLD:
        decision = "Reduce drops or increase time gap"
        main_reason = f"High RateLimit probability ({row['risk_probability_ratelimit']:.1%})"
        recommendation = "Reduce the number of drops per day or increase the time gap between them."

    # Rule 3 — Limit pressure
    elif row['limit_usage_ratio'] > LIMIT_USAGE_RATIO_THRESHOLD:
        decision = "Reduce volume"
        main_reason = f"High limit usage ratio ({row['limit_usage_ratio']:.1%})"
        recommendation = "Lower daily sent volume to stay within acceptable limits."

    # Rule 5 — Low sent ratio
    elif row['sent_ratio'] < SENT_RATIO_THRESHOLD:
        decision = "Reduce volume and check delivery quality"
        main_reason = f"Low sent ratio ({row['sent_ratio']:.1%})"
        recommendation = "Reduce volume and thoroughly check delivery quality, content, and recipient engagement."

    # Rule 7 — SPF/DKIM issue
    # Check for specific error probabilities if available
    elif ('error_probability_spf' in row.index and row['error_probability_spf'] > SPF_DKIM_PROB_THRESHOLD) or \
         ('error_probability_dkim' in row.index and row['error_probability_dkim'] > SPF_DKIM_PROB_THRESHOLD):
        decision = "Check authentication configuration"
        main_reason = "Potential SPF/DKIM authentication issue"
        recommendation = "Verify SPF and DKIM records and configuration before increasing volume."

    # Rule 4 — High growth
    elif row['growth_rate'] > SAFE_HISTORICAL_GROWTH_RATE:
        decision = "Slow down warm-up"
        main_reason = f"Growth rate too high ({row['growth_rate']:.1%})"
        recommendation = "Reduce the growth rate to a safer historical level."

    # Rule 8 — Safe zone (default case if no other rules triggered)
    else:
        decision = "Continue strategy or increase slowly"
        main_reason = "Low risk, good performance"
        recommendation = "Current strategy is performing well. Consider a slow, controlled volume increase."

    return pd.Series([decision, main_reason, recommendation], index=['decision', 'main_reason', 'recommendation'])

print("Decision rules function `apply_decision_rules` defined.")

"""## STEP 6 — Apply rules day by day

We will now apply the `apply_decision_rules` function to each row of our `simulation_df`. This will enrich the DataFrame with new columns: `decision`, `main_reason`, and `recommendation` for each day of the simulation.
"""

# Apply the decision rules to each row of the simulation DataFrame
decision_results = simulation_df.apply(apply_decision_rules, axis=1)

# Join the results back to the original simulation_df
simulation_df = pd.concat([simulation_df, decision_results], axis=1)

print("Decision rules applied. Updated DataFrame head:")
display(simulation_df.head())

"""## STEP 7 — Generate recommendation text

Now that we have applied the decision rules and enriched our DataFrame with `decision`, `main_reason`, and `recommendation` columns, we can generate a more detailed recommendation text for each day. This step is about articulating the actions in a human-readable format, combining the various insights.
"""

def generate_recommendation_text(row):
    """
    Generates a human-readable recommendation text for a given day.
    """
    day = int(row['day'])
    decision = row['decision']
    main_reason = row['main_reason']
    recommendation = row['recommendation']
    daily_volume = int(row['daily_volume'])

    text = f"Day {day}: Current Daily Volume: {daily_volume:,d}. "
    text += f"Decision: {decision}. "
    text += f"Main Reason: {main_reason}. "
    text += f"Recommendation: {recommendation}"

    return text

# Apply the function to create a new column with the recommendation text
simulation_df['recommendation_text'] = simulation_df.apply(generate_recommendation_text, axis=1)

print("Recommendation text generated for each day. Displaying first 5:")
for i in range(min(5, len(simulation_df))):
    print(simulation_df.loc[i, 'recommendation_text'])

"""## STEP 8 — Detect first risky day

Identifying the 'first risky day' is crucial for proactive management. This step finds the earliest point in the simulation where the decision engine recommends an action other than simply 'Continue strategy or increase slowly'.
"""

# Detect the first day that is not a 'Continue strategy or increase slowly' decision
first_risky_day_row = simulation_df[simulation_df['decision'] != 'Continue strategy or increase slowly'].iloc[0] if not simulation_df[simulation_df['decision'] != 'Continue strategy or increase slowly'].empty else None

if first_risky_day_row is not None:
    first_risky_day = int(first_risky_day_row['day'])
    print(f"The first risky day detected is Day {first_risky_day}.")
    print(f"Decision for Day {first_risky_day}: {first_risky_day_row['decision']}")
    print(f"Main Reason: {first_risky_day_row['main_reason']}")
    print(f"Recommendation: {first_risky_day_row['recommendation']}")
else:
    first_risky_day = None
    print("No risky days detected throughout the simulation. Strategy seems safe.")

# Detect the first day that is not a 'Continue strategy or increase slowly' decision
first_risky_day_row = simulation_df[simulation_df['decision'] != 'Continue strategy or increase slowly'].iloc[0] if not simulation_df[simulation_df['decision'] != 'Continue strategy or increase slowly'].empty else None

if first_risky_day_row is not None:
    first_risky_day = int(first_risky_day_row['day'])
    print(f"The first risky day detected is Day {first_risky_day}.")
    print(f"Decision for Day {first_risky_day}: {first_risky_day_row['decision']}")
    print(f"Main Reason: {first_risky_day_row['main_reason']}")
    print(f"Recommendation: {first_risky_day_row['recommendation']}")
else:
    first_risky_day = None
    print("No risky days detected throughout the simulation. Strategy seems safe.")

"""## STEP 9 — Detect main risk reasons

To get a high-level understanding of why certain decisions are being made, especially when a strategy is not 'Continue strategy or increase slowly', we will analyze the `main_reason` column. This can help summarize the most frequent challenges encountered during the simulation.
"""

# Filter out the 'Continue strategy or increase slowly' decisions to focus on problematic ones
risky_decisions = simulation_df[simulation_df['decision'] != 'Continue strategy or increase slowly']

if not risky_decisions.empty:
    # Get the value counts of the 'main_reason' column
    main_risk_reasons = risky_decisions['main_reason'].value_counts()
    print("Main risk reasons detected across the simulation (excluding 'Continue strategy or increase slowly'):")
    display(main_risk_reasons)

    # Optionally, identify the single most common reason
    most_common_reason = main_risk_reasons.index[0] if not main_risk_reasons.empty else "No specific main risk reason found."
    print(f"\nThe most common risk reason is: {most_common_reason}")
else:
    print("No risky decisions (other than 'Continue strategy or increase slowly') were made throughout the simulation.")

"""## STEP 10 — Create final decision summary

This step consolidates the key findings from the decision engine into a concise, human-readable summary. It includes information about the first risky day, the most common risk reasons, and an overall assessment of the simulation's outcome.
"""

print("--- Final Decision Engine Summary ---")

print("\nOverall Simulation Analysis:")
if first_risky_day is not None:
    print(f"The simulation indicates that the strategy becomes risky starting from Day {first_risky_day}.")
    print(f"The first intervention recommended is: '{first_risky_day_row['decision']}'.")
    print(f"Main Reason for first intervention: {first_risky_day_row['main_reason']}.")
    print(f"Recommendation for first intervention: {first_risky_day_row['recommendation']}.")
else:
    print("The simulated strategy appears safe throughout the entire period, with no risky days detected.")

if 'most_common_reason' in globals():
    print(f"\nThe most common underlying issue observed across all risky days is: '{most_common_reason}'.")
else:
    print("\nNo specific common risk reason was found as no risky decisions were made.")

print("\nDetailed daily recommendations are available in the 'recommendation_text' column of the simulation_df.")
print("Please review the full 'simulation_df' for a comprehensive breakdown of decisions and recommendations per day.")

"""## STEP 11 — Visualize decision zones

Visualizing the simulation results and the decisions made helps in understanding the impact of the strategy over time. We will create plots to show key metrics alongside the identified risk zones and decisions.
"""

plt.figure(figsize=(14, 7))
sns.lineplot(data=simulation_df, x='day', y='daily_volume', marker='o', label='Daily Volume')

# Shade areas based on 'predicted_risk_zone'
# Map risk zones to colors for consistent visualization
risk_colors = {
    'low': 'green',
    'medium': 'yellow',
    'high': 'orange',
    'dangerous': 'red',
    'critical': 'purple'
}

# Create a new column 'risk_zone_color' for plotting
simulation_df['risk_zone_color'] = simulation_df['predicted_risk_zone'].str.lower().map(risk_colors)

# Fill areas between risk zones
# Iterate through the DataFrame to find changes in risk zone and shade accordingly
current_risk_zone = None
start_day = simulation_df['day'].min()

for index, row in simulation_df.iterrows():
    if row['predicted_risk_zone'].lower() != current_risk_zone:
        if current_risk_zone is not None:
            # Fill the area for the previous risk zone
            plt.axvspan(start_day - 0.5, row['day'] - 0.5, color=risk_colors.get(current_risk_zone, 'gray'), alpha=0.2, label=f'{current_risk_zone.capitalize()} Zone')
        current_risk_zone = row['predicted_risk_zone'].lower()
        start_day = row['day']

# Fill the area for the last risk zone
plt.axvspan(start_day - 0.5, simulation_df['day'].max() + 0.5, color=risk_colors.get(current_risk_zone, 'gray'), alpha=0.2, label=f'{current_risk_zone.capitalize()} Zone')

# Mark the first risky day
if first_risky_day is not None:
    plt.axvline(x=first_risky_day, color='black', linestyle='--', label=f'First Risky Day (Day {first_risky_day})')

plt.title('Daily Volume with Predicted Risk Zones')
plt.xlabel('Day')
plt.ylabel('Daily Volume')
plt.legend(title='Legend', loc='upper left', bbox_to_anchor=(1, 1))
plt.grid(True)
plt.tight_layout()
plt.show()