# -*- coding: utf-8 -*-
"""PFE_6_risk_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnpydxTgRig87McyRjn8gMkJJQ3PVoOi

## Email Sending IP Optimization: Risk Classification Model Training

This notebook demonstrates how to train a risk classification model while carefully avoiding data leakage. We'll use a predefined set of features to predict email sending risk (Safe / Risk / Dangerous).

### Step 1: Load the Dataset and Initial Inspection

First, we'll load the `df_ml.xlsx` file into a pandas DataFrame and perform an initial inspection to understand its structure and data types.
"""

# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_excel('/content/df_ml.xlsx')

# Display the first few rows of the DataFrame
print("First 5 rows of the dataset:")
display(df.head())

# Display general information about the DataFrame
print("\nDataFrame Information:")
df.info()

"""### Step 2: Select Features (X) and Target (y)

This is a critical step to prevent data leakage. We will define the allowed features strictly and exclude all columns that directly reveal error information, as specified in your rules. The target variable is `risk_label_encoded`.
"""

# Define the list of leakage features to be explicitly excluded
leakage_features = [
    'error_flag',
    'spf_error',
    'ratelimit_error',
    'netblock_error',
    'error_count_last_24h',
    'blocked_before'
]

# Define the allowed features for the model training
allowed_features = [
    'sent_per_ip',
    'r_sent_per_ip',
    'limit_per_ip',
    'offset',
    'previous_sent_per_ip',
    'volume_change',
    'growth_rate',
    'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip',
    'daily_volume',
    'volume_per_drop',
    'sent_ratio',
    'limit_usage_ratio',
    'drops_per_day',
    'time_gap_min',
    'days_since_launch',
    'hour',
    'day_of_week'
]

# Define the target variable
target_column = 'risk_label_encoded'

# Create feature matrix X and target vector y
X = df[allowed_features]
y = df[target_column]

# Verify that no leakage features are present in X (for sanity check)
if any(feature in X.columns for feature in leakage_features):
    print("WARNING: Leakage features detected in X. Please recheck feature selection.")
else:
    print("Feature selection successful: No leakage features found in X.")

print("\nShape of X:", X.shape)
print("Shape of y:", y.shape)
print("\nFeatures (X) head:")
display(X.head())
print("\nTarget (y) head:")
display(y.head())

"""### Step 3: Handle Missing Values and Infinite Values

Missing values (`NaN`) and infinite values (`inf`, `-inf`) can cause issues with many machine learning algorithms. We will replace infinite values with `NaN` and then use median imputation to fill in any missing values in our feature set `X`.
"""

# Replace infinite values with NaN
X.replace([np.inf, -np.inf], np.nan, inplace=True)

# Initialize SimpleImputer with median strategy
# Median is often preferred over mean for skewed distributions or presence of outliers
imputer = SimpleImputer(strategy='median')

# Fit the imputer on X and transform X
X_imputed = imputer.fit_transform(X)

# Convert the imputed array back to a DataFrame, preserving column names
X = pd.DataFrame(X_imputed, columns=X.columns)

print("Missing values after imputation:")
print(X.isnull().sum().sum())

print("\nFirst 5 rows of X after handling missing values:")
display(X.head())

"""### Step 4: Train/Test Split

We will split our data into training (80%) and testing (20%) sets. It's crucial to use `stratify=y` to ensure that the proportion of each class in the target variable (`y`) is maintained in both the training and testing sets, especially important for imbalanced datasets.
"""

# Perform 80/20 train-test split, stratifying by 'y'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

print("\nClass distribution in original y:")
print(y.value_counts(normalize=True))
print("\nClass distribution in y_train:")
print(y_train.value_counts(normalize=True))
print("\nClass distribution in y_test:")
print(y_test.value_counts(normalize=True))

"""### Step 5: Train Models

We will train three different ensemble models: `RandomForestClassifier`, `GradientBoostingClassifier`, and `ExtraTreesClassifier`. These models are robust and generally perform well on classification tasks. For this initial training, we will use default parameters, but in a real-world scenario, hyperparameter tuning would be essential.
"""

# Initialize and train RandomForestClassifier
print("Training RandomForestClassifier...")
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
print("RandomForestClassifier trained.")

# Initialize and train GradientBoostingClassifier
print("\nTraining GradientBoostingClassifier...")
gbc_model = GradientBoostingClassifier(random_state=42)
gbc_model.fit(X_train, y_train)
print("GradientBoostingClassifier trained.")

# Initialize and train ExtraTreesClassifier
print("\nTraining ExtraTreesClassifier...")
et_model = ExtraTreesClassifier(random_state=42)
et_model.fit(X_train, y_train)
print("ExtraTreesClassifier trained.")

models = {
    'RandomForestClassifier': rf_model,
    'GradientBoostingClassifier': gbc_model,
    'ExtraTreesClassifier': et_model
}

print("\nAll models trained successfully.")

"""### Step 6: Evaluate Models

Model evaluation is crucial to understand how well each model performs. We will calculate common metrics such as accuracy, precision, recall, F1-score, and display a confusion matrix and classification report for each model. Special attention will be given to the 'Risk' and 'Dangerous' classes.
"""

evaluation_results = []

for name, model in models.items():
    print(f"\n--- Evaluating {name} ---")
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision_macro = precision_score(y_test, y_pred, average='macro', zero_division=0)
    recall_macro = recall_score(y_test, y_pred, average='macro', zero_division=0)
    f1_macro = f1_score(y_test, y_pred, average='macro', zero_division=0)

    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision (Macro): {precision_macro:.4f}")
    print(f"Recall (Macro): {recall_macro:.4f}")
    print(f"F1-Score (Macro): {f1_macro:.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=model.classes_, yticklabels=model.classes_)
    plt.title(f'Confusion Matrix for {name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

    # Store results
    report_dict = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    evaluation_results.append({
        'Model': name,
        'Accuracy': accuracy,
        'Precision (Macro)': precision_macro,
        'Recall (Macro)': recall_macro,
        'F1-Score (Macro)': f1_macro,
        'Precision_Safe': report_dict.get('0', {}).get('precision', 0),
        'Recall_Safe': report_dict.get('0', {}).get('recall', 0),
        'F1_Safe': report_dict.get('0', {}).get('f1-score', 0),
        'Precision_Risk': report_dict.get('1', {}).get('precision', 0),
        'Recall_Risk': report_dict.get('1', {}).get('recall', 0),
        'F1_Risk': report_dict.get('1', {}).get('f1-score', 0),
        'Precision_Dangerous': report_dict.get('2', {}).get('precision', 0),
        'Recall_Dangerous': report_dict.get('2', {}).get('recall', 0),
        'F1_Dangerous': report_dict.get('2', {}).get('f1-score', 0)
    })

"""### Step 7: Compare Models in a Table

To easily compare the performance of our three models, we'll compile their evaluation metrics into a pandas DataFrame. This will help us identify the best-performing model based on the defined objective (focus on 'Risk' and 'Dangerous' classes).
"""

# Create a DataFrame from the evaluation results
results_df = pd.DataFrame(evaluation_results)

# Set Model name as index for better readability
results_df.set_index('Model', inplace=True)

# Display the comparison table
print("\nModel Comparison Table:")
display(results_df.round(4))

# Determine the best model based on F1-score for 'Risk' and 'Dangerous' classes, or overall macro F1-score
# For multi-class, often macro F1 is a good overall indicator, but specific class F1 can be prioritized.
# Let's consider the model with the highest macro F1-score as 'best' for now.
best_model_name = results_df['F1-Score (Macro)'].idxmax()
best_model = models[best_model_name]

print(f"\nThe best performing model based on Macro F1-Score is: {best_model_name}")

"""### Step 8: Show Feature Importance of Best Model

Understanding which features contribute most to the model's predictions can provide valuable insights. We'll extract and visualize the feature importances for the best-performing model identified in the previous step.
"""

# Check if the best model has feature importances (Tree-based models do)
if hasattr(best_model, 'feature_importances_'):
    # Get feature importances
    feature_importances = best_model.feature_importances_

    # Create a pandas Series for better visualization
    feature_importance_df = pd.Series(feature_importances, index=X.columns)

    # Sort features by importance
    feature_importance_df = feature_importance_df.sort_values(ascending=False)

    # Plot feature importances
    plt.figure(figsize=(12, 8))
    sns.barplot(x=feature_importance_df.values, y=feature_importance_df.index, palette='viridis')
    plt.title(f'Feature Importance for {best_model_name}')
    plt.xlabel('Importance')
    plt.ylabel('Feature')
    plt.tight_layout()
    plt.show()
else:
    print(f"The best model ({best_model_name}) does not have 'feature_importances_' attribute.")

"""### Step 9: Save Best Model

Finally, we'll save the best-performing model to a file (`risk_model.pkl`) using `joblib`. This allows us to load and reuse the trained model later without retraining.

### Step 10: Download the Best Model
"""

# from google.colab import files

# files.download('risk_model.pkl')

# Define the filename for saving the model
model_filename = 'risk_model.pkl'

# Save the best model
joblib.dump(best_model, model_filename)

print(f"The best model ({best_model_name}) has been saved as '{model_filename}'.")

# Optional: To load the model later, you can use:
loaded_model = joblib.load(model_filename)
print(f"Model loaded: {type(loaded_model).__name__}")