# -*- coding: utf-8 -*-
"""PFE_5_feature_engineering_labels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxK91qXpBl5k6XYl8PinOiDFWSNLoL0A

# PFE_5_feature_engineering_labels.ipynb

## Objective: Create advanced ML/dashboard features and create Safe / Risk / Dangerous labels for email sending IP optimization.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Set display options for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

"""### 1. Load IP_life.xlsx"""

# Load the dataset
import pandas as pd

# Load data from the specified Excel file into a pandas DataFrame
df = pd.read_excel("/content/IP_Analyse.xlsx")
df.head()

"""### 2. Data Type Conversion"""

# Convert datetime columns to appropriate datetime objects
df['datetime_gride'] = pd.to_datetime(df['datetime_gride'])
df['first_used_at'] = pd.to_datetime(df['first_used_at'])

print("Datetime columns converted successfully.")
# Display data types to confirm conversion
display(df[['datetime_gride', 'first_used_at']].dtypes)

"""### 3. Feature Engineering

#### 3.1 Time-based features
"""

# 1. days_since_launch: difference in days between datetime_gride and first_used_at
df['days_since_launch'] = (df['datetime_gride'] - df['first_used_at']).dt.days

print("Feature 'days_since_launch' created.")
display(df[['datetime_gride', 'first_used_at', 'days_since_launch']].head(2))

"""#### 3.2 Performance features"""

# 2. sent_ratio = r_sent_per_ip / sent_per_ip
# Handle division by zero by replacing 0 with NaN, then filling NaN with 0 or a suitable value
df['sent_ratio'] = df['r_sent_per_ip'] / df['sent_per_ip'].replace(0, np.nan)
# Replace inf values (if any result from division by zero when sent_per_ip is non-zero but very small)
df['sent_ratio'] = df['sent_ratio'].replace([np.inf, -np.inf], np.nan)
# Fill any remaining NaNs (from division by zero or inf replacement) with 0. This implies no successful sends if sent_per_ip was 0.
df['sent_ratio'] = df['sent_ratio'].fillna(0)
df['sent_ratio'] = df['sent_ratio'].round(3)

print("Feature 'sent_ratio' created.")
display(df[['sent_per_ip', 'r_sent_per_ip', 'sent_ratio']].head())

"""#### 3.3 Pressure features"""

# 3. limit_usage_ratio = sent_per_ip / limit_per_ip
# Handle division by zero for limit_per_ip
df['limit_usage_ratio'] = df['sent_per_ip'] / df['limit_per_ip'].replace(0, np.nan)
# Replace inf values
df['limit_usage_ratio'] = df['limit_usage_ratio'].replace([np.inf, -np.inf], np.nan)
# Fill NaNs with 0. This implies no limit usage if limit_per_ip was 0 or sent_per_ip was 0.
df['limit_usage_ratio'] = df['limit_usage_ratio'].fillna(0)
df['limit_usage_ratio'] = df['limit_usage_ratio'].round(2)

print("Feature 'limit_usage_ratio' created.")
display(df[['sent_per_ip', 'limit_per_ip', 'limit_usage_ratio']].head())

"""#### 3.4 Daily aggregation"""

# Ensure the DataFrame is sorted for correct rolling/grouping operations
df = df.sort_values(by=['ip', 'datetime_gride']).reset_index(drop=True)

# Extract date part for daily aggregation
df['date'] = df['datetime_gride'].dt.date

# 4. daily_volume = total sent_per_ip per IP per day
daily_volume_df = df.groupby(['ip', 'date'])['sent_per_ip'].sum().reset_index()
daily_volume_df.rename(columns={'sent_per_ip': 'daily_volume'}, inplace=True)
df = pd.merge(df, daily_volume_df, on=['ip', 'date'], how='left')

# 5. volume_per_drop = daily_volume / drops_per_day
# Handle division by zero for drops_per_day
df['volume_per_drop'] = df['daily_volume'] / df['drops_per_day'].replace(0, np.nan)
# Replace inf values
df['volume_per_drop'] = df['volume_per_drop'].replace([np.inf, -np.inf], np.nan)
# Fill NaNs with 0 (if no drops, then volume per drop is 0)
df['volume_per_drop'] = df['volume_per_drop'].fillna(0)
df['volume_per_drop'] = df['volume_per_drop'].round(2)

print("Features 'daily_volume' and 'volume_per_drop' created.")
display(df[['ip', 'date', 'daily_volume', 'drops_per_day', 'volume_per_drop']].head())

"""#### 3.5 Time gap"""

# 6. time_gap_min = time difference in minutes between two consecutive drops per IP
# Ensure data is sorted by IP and then by datetime_gride for correct lag calculation
df['time_gap_min'] = df.groupby('ip')['datetime_gride'].diff().dt.total_seconds() / 60
# Fill NaN for the first entry of each IP (where there's no previous drop) with 0 or a relevant value
df['time_gap_min'] = df['time_gap_min'].fillna(0)
df['time_gap_min'] = df['time_gap_min'].round(2)

print("Feature 'time_gap_min' created.")
display(df[['ip', 'datetime_gride', 'time_gap_min']].head())

"""#### 3.6 Error features"""

# 7. error_flag = 1 if error_type_from_error != "No error" else 0
df['error_flag'] = (df['error_type_from_error'] != "No error").astype(int)

# 8. spf_error = 1 if error_type_from_error == "SPF" else 0
df['spf_error'] = (df['error_type_from_error'] == "Rate limit SPF").astype(int)

# 9. ratelimit_error = 1 if error_type_from_error == "RateLimit" else 0
df['dkim_error'] = (df['error_type_from_error'] == "Rate limit DKIM").astype(int)

# 10. netblock_error = 1 if error_type_from_error == "Netblock" else 0
df['netblock_error'] = (df['error_type_from_error'] == "Rate limit IP Netblock").astype(int)

print("Error-related features created.")
display(df[['error_type_from_error', 'error_flag', 'spf_error', 'dkim_error', 'netblock_error']].head())

"""#### 3.7 Behavioral features"""

# Ensure data is sorted by IP and then by datetime_gride for correct rolling operations
df = df.sort_values(by=['ip', 'datetime_gride']).reset_index(drop=True)

# 11. error_count_last_24h per IP
# Define a function to apply to each group
def count_errors_last_24h(group):
    # Set datetime_gride as index to use rolling on time window
    group = group.set_index('datetime_gride')
    # Count error_flag within a 24-hour rolling window, excluding the current point (closed='left')
    # or including it based on definition, here we count all in the window including current.
    # Using '24H' for the window and counting error_flag (1 if error)
    return group['error_flag'].rolling('24H', closed='right').sum()

df['error_count_last_24h'] = df.groupby('ip', group_keys=False).apply(count_errors_last_24h).reset_index(level=0, drop=True)

# We want error_count_last_24h to be the count of *previous* errors in the last 24h before current datetime_gride.
# Adjusting the rolling window to exclude the current row's error.
# If closed='right' includes the current row, we need to subtract the current row's error_flag if we want 'before'.
# For simplicity and common use-case, we'll keep it as 'right' for now, counting errors *up to and including* the current time point in the 24h window.
# If 'excluding current' is strictly needed, it requires a different approach (e.g. shift or custom window logic)
# For this task, 'closed=right' is typically acceptable for 'errors in last 24h'.


# 12. blocked_before = 1 if IP had a Netblock before current row else 0
# Use cumsum to check if a 'netblock_error' occurred previously for the same IP
df['blocked_before'] = df.groupby('ip')['netblock_error'].shift(1).fillna(0).cumsum().astype(int)
# For each IP, check if any netblock_error happened *before* the current row
df['blocked_before'] = df.groupby('ip')['netblock_error'].cumsum().shift(1).fillna(0).astype(int)

print("Features 'error_count_last_24h' and 'blocked_before' created.")
display(df[['ip', 'datetime_gride', 'error_flag', 'netblock_error', 'error_count_last_24h', 'blocked_before']].head(5))

"""#### 3.8 Flags"""

# 13. is_high_growth = 1 if growth_rate > 0.5 else 0
df['is_high_growth'] = (df['growth_rate'] > 0.5).astype(int)

# 14. is_high_pressure = 1 if limit_usage_ratio > 0.9 else 0
df['is_high_pressure'] = (df['limit_usage_ratio'] > 0.9).astype(int)

# 15. is_low_performance = 1 if sent_ratio < 0.7 else 0
df['is_low_performance'] = (df['sent_ratio'] < 0.7).astype(int)

print("Flag features created.")
display(df[['growth_rate', 'is_high_growth', 'limit_usage_ratio', 'is_high_pressure', 'sent_ratio', 'is_low_performance']].head())

"""### 4. Handle remaining missing/infinite values"""

# Check for any remaining infinite values after calculations and replace with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Fill any remaining NaN values in newly created numerical features.
# For simplicity, filling with 0 or median might be appropriate depending on the feature.
# Here, we'll fill with 0 for ratio-based and count-based features, as NaN likely means 'none' or 'not applicable'.

# List of potentially NaN columns from feature engineering
fill_zero_cols = [
    'sent_ratio', 'limit_usage_ratio', 'daily_volume', 'volume_per_drop',
    'time_gap_min', 'error_count_last_24h', 'blocked_before',
    'is_high_growth', 'is_high_pressure', 'is_low_performance'
]

for col in fill_zero_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0)

print("Checked and handled infinite and missing values in new features.")
display(df.isnull().sum()[df.isnull().sum() > 0]) # Show any remaining columns with NaNs

"""### 5. Create `risk_label`"""

# Initialize risk_label with 'Safe' as the default
df['risk_label'] = 'Safe'

# Dangerous conditions
dangerous_conditions = (
    (df['error_type_from_error'] == "Rate limit IP Netblock") |
    (df['blocked_before'] == 1) |
    (df['sent_ratio'] < 0.4)
)
df.loc[dangerous_conditions, 'risk_label'] = 'Dangerous'

# Risk conditions (apply only if not already 'Dangerous')
risk_conditions = (
    (df['error_type_from_error'].isin(["Rate limit SPF", "Rate limit DKIM "])) |
    (df['limit_usage_ratio'] > 0.9) |
    (df['growth_rate'] > 0.5) |
    (df['sent_ratio'] < 0.7) |
    (df['error_count_last_24h'] >= 2)
)
# Apply risk label only to rows that are not already marked 'Dangerous'
df.loc[~dangerous_conditions & risk_conditions, 'risk_label'] = 'Risk'

print("Risk labels created successfully.")
display(df[['error_type_from_error', 'blocked_before', 'sent_ratio', 'limit_usage_ratio', 'growth_rate', 'error_count_last_24h', 'risk_label']].head(10))

"""### 6. Encode `risk_label`"""

# Create a mapping for encoding
risk_mapping = {'Safe': 0, 'Risk': 1, 'Dangerous': 2}
df['risk_label_encoded'] = df['risk_label'].map(risk_mapping)

print("Risk labels encoded successfully.")
display(df[['risk_label', 'risk_label_encoded']].head())

"""### 7. Data Checks"""

print("#### Risk Label Distribution ####")
display(df['risk_label'].value_counts())
display(df['risk_label_encoded'].value_counts())

print("\n#### Error Type from Error Distribution ####")
display(df['error_type_from_error'].value_counts())

print("\n#### Missing Values ####")
display(df.isnull().sum()[df.isnull().sum() > 0])

"""### 7.1 Visualizing Risk Label and Error Type Distributions"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style
sns.set_style("whitegrid")

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.countplot(x='risk_label', data=df, palette='viridis', order=['Safe', 'Risk', 'Dangerous'])
plt.title('Distribution of Risk Labels')
plt.xlabel('Risk Label')
plt.ylabel('Count')

plt.subplot(1, 2, 2)
sns.countplot(y='error_type_from_error', data=df, palette='magma', order=df['error_type_from_error'].value_counts().index)
plt.title('Distribution of Error Types')
plt.xlabel('Count')
plt.ylabel('Error Type')
plt.tight_layout()
plt.show()

"""### 7.2 Relationship Between Key Features and Risk Label"""

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.boxplot(x='risk_label', y='sent_ratio', data=df, palette='viridis', order=['Safe', 'Risk', 'Dangerous'])
plt.title('Sent Ratio by Risk Label')
plt.xlabel('Risk Label')
plt.ylabel('Sent Ratio')

plt.subplot(1, 2, 2)
sns.boxplot(x='risk_label', y='limit_usage_ratio', data=df, palette='magma', order=['Safe', 'Risk', 'Dangerous'])
plt.title('Limit Usage Ratio by Risk Label')
plt.xlabel('Risk Label')
plt.ylabel('Limit Usage Ratio')

plt.tight_layout()
plt.show()

"""### 7.3 Correlation Matrix"""

ml_ready_columns = [
    'ip',
    'server',
    'datetime_gride',
    'campaign_id',
    'sent_per_ip',
    'r_sent_per_ip',
    'limit_per_ip',
    'offset',
    'previous_sent_per_ip',
    'volume_change',
    'growth_rate',
    'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip',
    'daily_volume',
    'volume_per_drop',
    'sent_ratio',
    'limit_usage_ratio',
    'drops_per_day',
    'time_gap_min',
    'days_since_launch',
    'hour',
    'day_of_week',
    'error_flag',
    'spf_error',
    'dkim_error',
    'netblock_error',
    'error_count_last_24h',
    'blocked_before',
    'is_high_growth',
    'is_high_pressure',
    'is_low_performance',
    'risk_label',
    'risk_label_encoded'
]

# Filter the DataFrame to include only ML-ready columns
# Ensure all specified columns exist in the DataFrame
existing_ml_columns = [col for col in ml_ready_columns if col in df.columns]

# If any columns are missing, print a warning (optional, but good practice)
missing_ml_columns = [col for col in ml_ready_columns if col not in df.columns]
if missing_ml_columns:
    print(f"Warning: The following ML-ready columns were not found and will be excluded: {missing_ml_columns}")

df_ml = df[existing_ml_columns].copy()

# Select numerical features and the encoded risk label for correlation analysis
numerical_cols = df_ml.select_dtypes(include=np.number).columns.tolist()

# Ensure 'risk_label_encoded' is in the list and other non-feature identifiers are removed
analysis_cols = [col for col in numerical_cols if col not in ['campaign_id', 'offset']]

correlation_matrix = df_ml[analysis_cols].corr()

plt.figure(figsize=(16, 12))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Numerical Features and Risk Label')
plt.show()

"""### 7.4 Feature Importance (Exploratory Analysis using RandomForest)"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Prepare data for feature importance calculation
# Exclude non-numerical and identifier columns, and the target itself
features_for_ml = [
    'sent_per_ip', 'r_sent_per_ip', 'limit_per_ip', 'offset',
    'previous_sent_per_ip', 'volume_change', 'growth_rate',
    'cumulative_sent_per_ip', 'daily_cumulative_sent_per_ip',
    'daily_volume', 'volume_per_drop', 'sent_ratio',
    'limit_usage_ratio', 'drops_per_day', 'time_gap_min',
    'days_since_launch', 'hour', 'day_of_week',
    'error_flag', 'spf_error', 'dkim_error',
    'netblock_error', 'error_count_last_24h', 'blocked_before',
    'is_high_growth', 'is_high_pressure', 'is_low_performance'
]

# Filter to only include columns that exist in the DataFrame
existing_features = [col for col in features_for_ml if col in df_ml.columns]
missing_features = [col for col in features_for_ml if col not in df_ml.columns]

if missing_features:
    print(f"Warning: The following features for ML were not found and will be excluded: {missing_features}")

X = df_ml[existing_features]
y = df_ml['risk_label_encoded']

# Split data (optional, but good practice for model-based importance)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train a RandomForestClassifier
# (Using a small number of estimators for exploratory purposes, not for optimal performance)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)

# Get feature importances
feature_importances = pd.Series(rf_model.feature_importances_, index=X_train.columns)
sorted_importances = feature_importances.sort_values(ascending=False)

print("Top 10 Feature Importances:")
display(sorted_importances.head(10))

# Plot feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x=sorted_importances.head(15).values, y=sorted_importances.head(15).index, palette='viridis')
plt.title('Top 15 Feature Importances for Risk Label Prediction (Random Forest)')
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

"""### 8. Select ML-ready columns"""

ml_ready_columns = [
    'ip',
    'server',
    'datetime_gride',
    'campaign_id',
    'sent_per_ip',
    'r_sent_per_ip',
    'limit_per_ip',
    'offset',
    'previous_sent_per_ip',
    'volume_change',
    'growth_rate',
    'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip',
    'daily_volume',
    'volume_per_drop',
    'sent_ratio',
    'limit_usage_ratio',
    'drops_per_day',
    'time_gap_min',
    'days_since_launch',
    'hour',
    'day_of_week',
    'error_flag',
    'spf_error',
    'dkim_error',
    'netblock_error',
    'error_count_last_24h',
    'blocked_before',
    'is_high_growth',
    'is_high_pressure',
    'is_low_performance',
    'risk_label',
    'risk_label_encoded'
]

# Filter the DataFrame to include only ML-ready columns
# Ensure all specified columns exist in the DataFrame
existing_ml_columns = [col for col in ml_ready_columns if col in df.columns]
missing_ml_columns = [col for col in ml_ready_columns if col not in df.columns]

if missing_ml_columns:
    print(f"Warning: The following ML-ready columns were not found and will be excluded: {missing_ml_columns}")

df_ml = df[existing_ml_columns].copy()

print("ML-ready dataset created with selected columns.")
display(df_ml.head())

"""### 9. Save Output"""

# The following lines are commented out but show how to save the 'IP_life' DataFrame to an Excel file
# and then download it in a Colab environment.
df_ml.to_excel('/content/df_ml.xlsx', index=False)
from google.colab import files
files.download('/content/df_ml.xlsx')

df_ml.columns

