# -*- coding: utf-8 -*-
"""PFE_10_time_series_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toIPDYR53Yh6U1O74d7XeDSHaYPzdcrp

# PFE_10_time_series_forecasting.ipynb

## Objective
Build a Time Series Forecasting system for email sending IP behavior to forecast future sending behavior and risk evolution.

### STEP 1 — Import libraries

We'll import all the necessary libraries for data manipulation, time series modeling, and visualization.
"""

# Core libraries for data manipulation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Prophet for time series forecasting
from prophet import Prophet

# Statsmodels for ARIMA (alternative time series model)
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA

# Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")

"""### STEP 2 — Load dataset

We will load the `df_ml.xlsx` file into a pandas DataFrame. This dataset contains the IP behavior data.
"""

# Load the dataset from the specified Excel file
df = pd.read_excel('/content/df_ml.xlsx')

# Display the first 5 rows and basic info to understand the data structure
print("Dataset loaded successfully. Here are the first 5 rows:")
display(df.head())
print("\nDataset Information:")
df.info()

"""### STEP 3 — Convert datetime columns

We need to ensure the `datetime_gride` column is in the correct datetime format to perform time-based operations.
"""

# Convert 'datetime_gride' to datetime objects
df['datetime_gride'] = pd.to_datetime(df['datetime_gride'])

# Verify the conversion
print("Data type of 'datetime_gride' after conversion:")
print(df['datetime_gride'].dtype)
print("\nFirst 5 entries of 'datetime_gride' after conversion:")
display(df['datetime_gride'].head())

"""### STEP 4 — Create date column

For daily aggregation, we will extract just the date part from the `datetime_gride` column and create a new `date` column.
"""

# Extract the date part from 'datetime_gride' to create a new 'date' column
df['date'] = df['datetime_gride'].dt.date

# Convert the 'date' column to datetime objects for consistency in time series operations
df['date'] = pd.to_datetime(df['date'])

# Display the first few rows with the new 'date' column
print("DataFrame with new 'date' column:")
display(df[['datetime_gride', 'date']].head())

"""### STEP 5 — Aggregate by IP + Date

To prepare the data for daily time series forecasting, we need to aggregate the data by `ip` and `date`. We will sum `daily_volume` and `risk_label_encoded`, and calculate the mean for `sent_ratio` for each IP on each day.

We will also handle missing dates by reindexing and filling missing values.

"""

# Define the columns to aggregate and their aggregation methods
aggregation_rules = {
    'daily_volume': 'sum',
    'sent_ratio': 'mean', # Assuming sent_ratio is an average/proportion
    'risk_label_encoded': 'mean' # Assuming risk_label_encoded is an average risk per day
}

# Aggregate the data by 'ip' and 'date'
df_aggregated = df.groupby(['ip', 'date']).agg(aggregation_rules).reset_index()

# Handle missing dates for each IP
# Create a complete date range for the entire dataset
all_dates = pd.date_range(start=df_aggregated['date'].min(), end=df_aggregated['date'].max(), freq='D')

# Create a multi-index DataFrame for all possible ip-date combinations
ips = df_aggregated['ip'].unique()
multi_index = pd.MultiIndex.from_product([ips, all_dates], names=['ip', 'date'])

# Reindex the aggregated DataFrame to include all dates and fill missing values
df_full_dates = df_aggregated.set_index(['ip', 'date']).reindex(multi_index).reset_index()

# Fill missing 'daily_volume' and 'risk_label_encoded' with 0 (or a suitable default)
df_full_dates['daily_volume'] = df_full_dates['daily_volume'].fillna(0)
# Fill missing 'sent_ratio' with the mean of the respective IP, or a global mean, or 0 if appropriate
# For simplicity, filling with 0, but a more sophisticated approach might be needed
df_full_dates['sent_ratio'] = df_full_dates['sent_ratio'].fillna(0)
# For 'risk_label_encoded', it might be more appropriate to forward-fill or use a last known value strategy
df_full_dates['risk_label_encoded'] = df_full_dates['risk_label_encoded'].fillna(method='ffill').fillna(0)


# Display the first few rows of the aggregated data
print("Aggregated DataFrame by IP and Date (first 5 rows):")
display(df_full_dates.head())

print("\nAggregated DataFrame Information:")
df_full_dates.info()

"""### STEP 6 — Select one IP example

For demonstration and to simplify the initial forecasting setup, we will select a single IP address from our `df_full_dates` DataFrame. This IP's historical data will be used to train and test our time series models.

"""

# Get a list of unique IPs to choose from
unique_ips = df_full_dates['ip'].unique()
print(f"Available IPs: {unique_ips}")

# Select one specific IP for forecasting with more data points.
# Let's find an IP with the most data points for a better demonstration.
# Assuming '69.162.64.211' has more data based on observation of `df_full_dates` or prior analysis.
# In a real scenario, you would dynamically select an IP with sufficient history.
selected_ip = '107.6.171.227' # Manually selecting an IP that is likely to have more data

# Filter the DataFrame for the selected IP
ip_df = df_full_dates[df_full_dates['ip'] == selected_ip].copy()

# Display the first few rows and information of the selected IP's data
print(f"\nData for selected IP: {selected_ip}")
display(ip_df.head())
print(f"\nInformation for selected IP's data:")
ip_df.info()

"""### STEP 7 — Prepare time series format

Time series forecasting models often require specific input formats. For Prophet, the DataFrame needs two columns: `ds` (datestamp, which is our 'date' column) and `y` (the variable we want to forecast).

We will create three separate DataFrames, one for each target variable (`daily_volume`, `sent_ratio`, `risk_label_encoded`), each formatted for Prophet.
"""

# Prepare data for 'daily_volume' forecasting
# Rename 'date' to 'ds' and 'daily_volume' to 'y'
df_volume = ip_df[['date', 'daily_volume']].rename(columns={'date': 'ds', 'daily_volume': 'y'})
print("Daily Volume Data (first 5 rows):")
display(df_volume.head())

# Prepare data for 'sent_ratio' forecasting
# Rename 'date' to 'ds' and 'sent_ratio' to 'y'
df_sent_ratio = ip_df[['date', 'sent_ratio']].rename(columns={'date': 'ds', 'sent_ratio': 'y'})
print("\nSent Ratio Data (first 5 rows):")
display(df_sent_ratio.head())

# Prepare data for 'risk_label_encoded' forecasting
# Rename 'date' to 'ds' and 'risk_label_encoded' to 'y'
df_risk_encoded = ip_df[['date', 'risk_label_encoded']].rename(columns={'date': 'ds', 'risk_label_encoded': 'y'})
print("\nRisk Label Encoded Data (first 5 rows):")
display(df_risk_encoded.head())

print("\nTime series data prepared for forecasting.")

"""### STEP 8 — Train forecasting model

Now we will train a forecasting model. We'll start with Prophet for `daily_volume`, as it's well-suited for time series data with trends and seasonality. We will initialize the Prophet model and then fit it to our prepared `df_volume` data.
"""

# Initialize the Prophet model for daily_volume
# We can add parameters like seasonality_mode or changepoint_prior_scale for better performance
model_volume = Prophet(daily_seasonality=True) # Assuming daily seasonality is relevant

# Fit the model to the daily_volume data
model_volume.fit(df_volume)

print("Prophet model for daily_volume trained successfully!")

"""### STEP 9 — Predict next 7 days

After training the model, we can use it to make predictions for future dates. We will create a DataFrame with future dates (in `ds` format) for the next 7 days and then use the `predict` method of our trained Prophet model.
"""

# Create a DataFrame with future dates for the next 7 days
future = model_volume.make_future_dataframe(periods=7)

# Make predictions using the trained model
forecast_volume = model_volume.predict(future)

# Display the last few rows of the forecast, showing the predicted future values
print("Forecasted Daily Volume for the next 7 days (last 10 rows):")
display(forecast_volume[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

"""### STEP 10 — Plot forecasts

Visualizing the forecast is crucial to understand the model's predictions and how well they align with historical data. We will plot the historical `daily_volume` and the forecasted values, including the upper and lower bounds of the predictions.
"""

# Plot the forecast for daily_volume
fig1 = model_volume.plot(forecast_volume)
plt.title('Daily Volume Forecast for Next 7 Days')
plt.xlabel('Date')
plt.ylabel('Daily Volume')
plt.show()

# Optionally, plot the forecast components (trend, seasonality)
fig2 = model_volume.plot_components(forecast_volume)
plt.suptitle('Daily Volume Forecast Components', y=1.02) # Adjust suptitle position
plt.tight_layout()
plt.show()

"""### STEP 11 — Forecast risk evolution

Following the same approach as `daily_volume`, we will now train a Prophet model to forecast the `risk_label_encoded` for the selected IP. This will give us an insight into the future risk trend.

"""

# Initialize the Prophet model for risk_label_encoded
# We disable daily seasonality here as risk might not have strong daily patterns, or due to limited data.
# Given the very limited historical data (only 2 days), the model's ability to learn any meaningful patterns is severely constrained.
# The forecasts will likely be simplistic and not very accurate.
model_risk = Prophet(daily_seasonality=False, yearly_seasonality=False, weekly_seasonality=False) # Disabling seasonality due to limited data

# Fit the model to the risk_label_encoded data
model_risk.fit(df_risk_encoded)

print("Prophet model for risk_label_encoded trained successfully!")

# Create a DataFrame with future dates for the next 7 days (same as before)
future_risk = model_risk.make_future_dataframe(periods=7)

# Make predictions using the trained model
forecast_risk = model_risk.predict(future_risk)

# Display the last few rows of the forecast
print("\nForecasted Risk Label Encoded for the next 7 days (last 10 rows):")
display(forecast_risk[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

# Plot the forecast for risk_label_encoded
fig_risk = model_risk.plot(forecast_risk)
plt.title(f'Risk Label Encoded Forecast for IP: {selected_ip}')
plt.xlabel('Date')
plt.ylabel('Risk Label Encoded')
plt.show()

# Plot the forecast components (optional)
fig_risk_components = model_risk.plot_components(forecast_risk)
plt.suptitle(f'Risk Label Encoded Forecast Components for IP: {selected_ip}', y=1.02)
plt.tight_layout()
plt.show()

"""### STEP 12 — Create reusable forecasting function

To make our forecasting process more efficient and reusable, we will create a function that can take any time series DataFrame (formatted with 'ds' and 'y' columns) and forecast future values using Prophet. This function will also handle model fitting, prediction, and return a clean forecast DataFrame.
"""

def create_prophet_forecast(df_ts, periods=7, seasonality=False, seasonality_mode='additive', cap_floor=False, model_name="Prophet Model"):
    """
    Trains a Prophet model and generates a forecast.

    Args:
        df_ts (pd.DataFrame): DataFrame with 'ds' (datestamp) and 'y' (target) columns.
        periods (int): Number of periods to forecast into the future.
        seasonality (bool): Whether to include daily seasonality.
        seasonality_mode (str): 'additive' or 'multiplicative' for seasonality.
        cap_floor (bool): Whether to include cap and floor values for logistic growth.
        model_name (str): Name for the model for printing/identification.

    Returns:
        pd.DataFrame: DataFrame containing the forecast, with 'ds', 'yhat', 'yhat_lower', 'yhat_upper' columns.
        Prophet model: The trained Prophet model.
    """
    print(f"\nTraining {model_name}...")

    # Initialize Prophet model
    model = Prophet(
        daily_seasonality=seasonality,
        weekly_seasonality=seasonality,
        yearly_seasonality=seasonality,
        seasonality_mode=seasonality_mode # 'additive' or 'multiplicative'
    )

    if cap_floor:
        # Ensure 'cap' and 'floor' columns exist if logistic growth is enabled
        # For simplicity, we'll assume y is always positive for cap/floor example.
        # In real scenarios, you'd define these based on domain knowledge.
        df_ts['cap'] = df_ts['y'].max() * 1.2 # 20% above max observed
        df_ts['floor'] = df_ts['y'].min() * 0.8 # 20% below min observed
        # Ensure cap is always greater than y
        df_ts['cap'] = df_ts['cap'].apply(lambda x: x if x > df_ts['y'].max() else df_ts['y'].max() + 1)
        model = Prophet(growth='logistic', daily_seasonality=seasonality, weekly_seasonality=seasonality, yearly_seasonality=seasonality, seasonality_mode=seasonality_mode)

    # Fit the model
    model.fit(df_ts)

    # Create future dataframe
    future = model.make_future_dataframe(periods=periods)
    if cap_floor:
        # For logistic growth, future dataframe also needs cap and floor
        future['cap'] = df_ts['cap'].iloc[-1] # Carry forward last known cap
        future['floor'] = df_ts['floor'].iloc[-1] # Carry forward last known floor

    # Make prediction
    forecast = model.predict(future)

    print(f"{model_name} trained and forecasted successfully!")
    return forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], model

print("Reusable forecasting function 'create_prophet_forecast' defined.")

"""### Apply the Reusable Function to Forecast Sent Ratio

Now we'll use the `create_prophet_forecast` function to predict the `sent_ratio` for the next 7 days.
"""

# Forecast sent_ratio using the new function
forecast_sent_ratio, model_sent_ratio = create_prophet_forecast(
    df_sent_ratio,
    periods=7,
    seasonality=False, # Sent ratio might not have strong seasonality in this dataset
    model_name="Prophet Model for Sent Ratio"
)

print("\nForecasted Sent Ratio for the next 7 days (last 10 rows):")
display(forecast_sent_ratio.tail(10))

# Plot the forecast for sent_ratio
fig_sent_ratio = model_sent_ratio.plot(forecast_sent_ratio)
plt.title(f'Sent Ratio Forecast for IP: {selected_ip}')
plt.xlabel('Date')
plt.ylabel('Sent Ratio')
plt.show()

# Plot the forecast components (optional - commented out due to insufficient data for meaningful components)
# fig_sent_ratio_components = model_sent_ratio.plot_components(forecast_sent_ratio)
# plt.suptitle(f'Sent Ratio Forecast Components for IP: {selected_ip}', y=1.02)
# plt.tight_layout()
# plt.show()

"""### Re-apply the Reusable Function for Daily Volume and Risk (for demonstration)

We can also re-apply the function to `daily_volume` and `risk_label_encoded` to show its flexibility and get consistent output formats. Note that these results will be similar to the direct calls made earlier, but now they utilize the new function.
"""

# Forecast daily_volume using the new function
forecast_volume_func, model_volume_func = create_prophet_forecast(
    df_volume,
    periods=7,
    seasonality=True, # Assuming daily seasonality is relevant
    model_name="Prophet Model for Daily Volume (using function)"
)

print("\nForecasted Daily Volume (using function) for the next 7 days (last 10 rows):")
display(forecast_volume_func.tail(10))

# Forecast risk_label_encoded using the new function
forecast_risk_func, model_risk_func = create_prophet_forecast(
    df_risk_encoded,
    periods=7,
    seasonality=False, # Disabling seasonality due to limited data
    model_name="Prophet Model for Risk Label Encoded (using function)"
)

print("\nForecasted Risk Label Encoded (using function) for the next 7 days (last 10 rows):")
display(forecast_risk_func.tail(10))

print("All three metrics have now been forecasted using the reusable function.")

"""### STEP 13 — Export forecast results

To make the forecasts accessible for further use (e.g., integration into a dashboard or other analysis), we will combine the key forecast results into a single DataFrame and export it to a CSV file.
"""

# Combine the relevant forecast columns into a single DataFrame
# We'll use the forecasts generated by the reusable function for consistency

# Ensure all forecast DataFrames have the same 'ds' (date) range, which they should if make_future_dataframe was called consistently

# Rename 'yhat' columns to be specific to the metric
forecast_volume_func_export = forecast_volume_func[['ds', 'yhat']].rename(columns={'yhat': 'forecast_daily_volume'})
forecast_sent_ratio_export = forecast_sent_ratio[['ds', 'yhat']].rename(columns={'yhat': 'forecast_sent_ratio'})
forecast_risk_func_export = forecast_risk_func[['ds', 'yhat']].rename(columns={'yhat': 'forecast_risk_label_encoded'})

# Merge the forecasts based on the 'ds' column
final_forecast_df = forecast_volume_func_export.merge(forecast_sent_ratio_export, on='ds', how='left')
final_forecast_df = final_forecast_df.merge(forecast_risk_func_export, on='ds', how='left')

# Add the selected IP to the forecast DataFrame
final_forecast_df['ip'] = selected_ip

# Reorder columns for clarity (e.g., ip, ds, then forecasts)
final_forecast_df = final_forecast_df[['ip', 'ds', 'forecast_daily_volume', 'forecast_sent_ratio', 'forecast_risk_label_encoded']]

# Display the final forecast DataFrame
print("\nFinal combined forecast for the next 7 days:")
display(final_forecast_df.tail(7)) # Displaying only the future forecasts

# Define the output file path
output_filename = f'forecast_{selected_ip.replace('.', '_')}.csv'

# Export the DataFrame to a CSV file
final_forecast_df.to_csv(output_filename, index=False)

print(f"\nForecast results exported to {output_filename}")

"""### STEP 14 — Train and Forecast with ARIMA Model (for comparison)

Now, let's train an ARIMA model using the `statsmodels` library for `daily_volume` to compare its performance with Prophet. Due to the very limited number of data points (only 2), choosing appropriate `p`, `d`, `q` orders for ARIMA is challenging and might lead to unstable models. We'll start with a simple order (e.g., 1, 0, 0) for demonstration purposes, acknowledging its limitations with so little data.
"""

# For ARIMA, the index should be datetime
# Make a copy to avoid modifying the original df_volume which is used by Prophet
df_volume_arima = df_volume.set_index('ds').copy()

# Due to only 2 data points, a complex ARIMA model will not fit.
# We'll try a simple ARIMA(1,0,0) model for demonstration, but results will be unreliable.
# 'd' (differencing) is typically 1 for non-stationary data, but with 2 points, it's hard to assess stationarity.
# 'p' (AR) and 'q' (MA) are also difficult to determine with so little data.

try:
    # Initialize and fit the ARIMA model
    # Setting enforce_stationarity=False and enforce_invertibility=False might be necessary for very short series
    model_arima_volume = ARIMA(df_volume_arima['y'], order=(1,0,0))
    model_arima_volume_fit = model_arima_volume.fit()

    print("ARIMA model for daily_volume trained successfully!")
    print(model_arima_volume_fit.summary())

    # Predict the next 7 days
    # Start prediction from the end of the training data
    start_idx = len(df_volume_arima)
    end_idx = start_idx + 6 # Forecast 7 days into the future
    forecast_arima_volume = model_arima_volume_fit.predict(start=start_idx, end=end_idx, typ='levels')

    # Create a DataFrame for ARIMA forecast results
    future_dates = pd.date_range(start=df_volume_arima.index.max() + pd.Timedelta(days=1), periods=7, freq='D')
    df_arima_forecast = pd.DataFrame({'ds': future_dates, 'yhat_arima': forecast_arima_volume})

    print("\nForecasted Daily Volume with ARIMA for the next 7 days:")
    display(df_arima_forecast.head(7))

except Exception as e:
    print(f"Could not train ARIMA model due to insufficient data or model complexity: {e}")
    model_arima_volume_fit = None
    df_arima_forecast = pd.DataFrame(columns=['ds', 'yhat_arima']) # Empty DataFrame if error

"""### STEP 15 — Compare Prophet and ARIMA Forecasts for Daily Volume

Now, let's visualize the forecasts from both Prophet and ARIMA for `daily_volume`. This will allow us to see how each model predicts future values given the very limited historical data.
"""

if not df_arima_forecast.empty:
    # Merge historical data with both forecasts for plotting
    # Ensure forecast_volume_func (Prophet forecast) only contains future predictions
    prophet_future_forecast = forecast_volume_func[forecast_volume_func['ds'] > df_volume.ds.max()]

    plt.figure(figsize=(14, 7))
    plt.plot(df_volume['ds'], df_volume['y'], label='Historical Daily Volume', marker='o')

    # Plot Prophet forecast
    plt.plot(prophet_future_forecast['ds'], prophet_future_forecast['yhat'], label='Prophet Forecast', linestyle='--')
    plt.fill_between(prophet_future_forecast['ds'], prophet_future_forecast['yhat_lower'], prophet_future_forecast['yhat_upper'], color='blue', alpha=0.2, label='Prophet Confidence Interval')

    # Plot ARIMA forecast
    plt.plot(df_arima_forecast['ds'], df_arima_forecast['yhat_arima'], label='ARIMA Forecast', linestyle=':', color='red')

    plt.title(f'Daily Volume Forecast Comparison for IP: {selected_ip}')
    plt.xlabel('Date')
    plt.ylabel('Daily Volume')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
else:
    print("ARIMA forecast could not be generated, so no comparison plot can be shown.")