# -*- coding: utf-8 -*-
"""PFE_4_ip_lifecycle_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mo2KEDbzA8J8VbWRwHGrkmg31KT8uErR

## Initial Setup and Data Loading

**Goal**: To prepare the environment and load the raw data into a pandas DataFrame, ensuring it's in a usable format for subsequent analysis.

This first step involves importing necessary libraries and configuring pandas for better readability of output. It then loads the `final_data.xlsx` file, which is the starting point for our IP lifecycle analysis. Key columns like `datetime_gride` are converted to datetime objects, and the data is sorted by `ip` and `datetime_gride` to establish a chronological order for each IP, which is fundamental for time-series feature engineering.
"""

import os
import pandas as pd
import numpy as np

# Configure pandas to display all columns and format numbers with two decimal places
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

"""### Data Loading and Initial Preparation

**Goal**: Load the raw data and perform initial cleaning steps like converting date columns and sorting, which are prerequisites for accurate time-series analysis.

We load the Excel file into a DataFrame, convert the `datetime_gride` column to a proper datetime format, and sort the data. This sorting is critical because many subsequent calculations (like finding the first event for an IP, or calculating time differences and previous values) rely on the data being in chronological order for each unique IP address.
"""

import pandas as pd

# Load data from the specified Excel file into a pandas DataFrame
df = pd.read_excel("/content/final_data.xlsx")

# Convert the 'datetime_gride' column to datetime objects for proper time-based operations
df["datetime_gride"] = pd.to_datetime(df["datetime_gride"])

# Sort the DataFrame first by 'ip' and then by 'datetime_gride' to ensure chronological order for each IP
df = df.sort_values(["ip", "datetime_gride"])

# Display the first few rows of the DataFrame to verify the load and sorting
df.head()

"""### Robust Datetime Conversion

**Goal**: Ensure the `datetime_gride` column is correctly interpreted as datetime objects, handling any malformed entries gracefully to prevent errors in calculations.

This step explicitly converts the `datetime_gride` column to a datetime type. Using `errors='coerce'` is a robust way to handle any data inconsistencies: if a date value cannot be parsed, it will be replaced with `NaT` (Not a Time) instead of crashing the process, allowing for further data cleaning or imputation if needed.

Convert datetime_gride to a proper datetime type
"""

# Ensure the 'datetime_gride' column is parsed correctly into datetime format.
# `errors='coerce'` will turn any unparseable dates into NaT (Not a Time) instead of raising an error.
df["datetime_gride"] = pd.to_datetime(df["datetime_gride"], errors="coerce")

"""### Re-sorting Data for Consistency

**Goal**: Maintain the crucial chronological order for each IP after any potential data type conversions or modifications, ensuring that all time-based calculations remain accurate.

We re-sort the DataFrame by `ip` and `datetime_gride`. This is a defensive step to ensure that the data remains correctly ordered after the datetime conversion. Time-series operations like `shift()` or `cumsum()` are highly dependent on this order to provide meaningful results per IP. `reset_index(drop=True)` creates a clean, default integer index.

Sort rows by IP and datetime
"""

# Sort the DataFrame by 'ip' and then by 'datetime_gride'.
# This is crucial for correctly calculating time-series features like cumulative sums or shifts.
# `reset_index(drop=True)` removes the old index and creates a new default integer index.
df = df.sort_values(by=["ip", "datetime_gride"]).reset_index(drop=True)

"""### Standardize Column Names

**Goal**: Improve readability and ensure consistency in column naming, especially for columns that will be used in multiple downstream calculations or merges.

Renaming `offset` to `offset_x` and `limit` to `limit_x` helps to differentiate these columns in a larger dataset and avoid potential naming conflicts, particularly if other `offset` or `limit` columns are introduced from different data sources or calculated features.

### Standardize Column Names

Rename `sent_per_ip` to `sent_gride`, `offset` to `offset_x`, and `limit` to `limit_x` to align with the column names used in subsequent feature engineering steps.

### Detect First Usage of Each IP

**Goal**: Identify and extract the very first interaction or event for each unique IP address. This is essential for understanding an IP's 'launch' or initial state, and forms the basis for lifecycle analysis.

By grouping the DataFrame by `ip` and selecting the `.first()` entry for each group (thanks to the prior sorting), we capture the initial timestamp, first `sent_per_ip` volume, and initial error status for every unique IP. These 'first' values are fundamental for calculating metrics like 'days since launch' or determining if the initial launch was successful.

Detect first usage of each IP
"""

# Group the DataFrame by 'ip' and select the first record for each IP.
# This captures the very first event or 'usage' details for each unique IP address.
first_usage = df.groupby("ip", as_index=False).first()

# Rename columns in the 'first_usage' DataFrame to make their meaning explicit.
# This helps differentiate these 'first event' attributes from general event attributes.
first_usage = first_usage.rename(
    columns={
        "datetime_gride": "first_used_at",
        "sent_per_ip": "first_sent_per_ip",
        "error_type_from_error": "first_error",
        "limit_per_ip": "first_limit",
        "offset": "first_offset",
    }
)[
    [
        "ip",
        "server",
        "first_used_at",
        "first_sent_per_ip",
        "first_error",
        "first_limit",
        "first_offset",
    ]
]

"""### First-Launch Success Flag

**Goal**: To create a clear, binary indicator of whether an IP's initial activity can be considered 'successful' based on specific business rules. This allows for easy categorization and analysis of IP onboarding quality.

This step defines 'success' for an IP's first launch: no error occurred or a specific rate limit/netblock error occurred (`'No error'`, `'SPF'`, `'Rate limit SPF'`, `'Rate limit DKIM'`, `'Netblock'`) and the volume sent (`'first_sent_per_ip'`) was below a certain threshold (10,000). This flag (`first_launch_success`) provides a quick way to filter and analyze the performance of new IPs, potentially identifying issues with initial setup or configuration for failed launches.

First‑launch success flag
"""

# Define the condition for a 'successful' first launch:
#   1. The 'first_error' must be 'No error' OR one of the specified rate limit/netblock errors.
#   2. The 'first_sent_per_ip' volume must be less than 10,000.
cond = (first_usage["first_error"].isin(["No error", "SPF", "Rate limit SPF", "Rate limit DKIM", "Netblock"])) & \
       (first_usage["first_sent_per_ip"] < 10_000)

# Create a new binary column 'first_launch_success' based on the condition.
# It will be 1 for success and 0 for failure.
first_usage["first_launch_success"] = cond.astype(int)

"""### Row-level Lifecycle Feature Engineering

**Goal**: To generate a rich set of features for each individual event (row) in the DataFrame. These features capture various aspects of an IP's behavior over time, including its sequential activity, temporal metrics, volume changes, and error patterns.

This section is crucial for transforming raw event data into actionable insights. Each new column added (like `drop_number`, `days_since_launch`, `volume_change`, `growth_rate`, `cumulative_sent_per_ip`, `daily_cumulative_sent_per_ip`, `hour`, `day_of_week`, `drops_per_day`, `error_code`, `volume_category`) provides a different perspective on an IP's journey. For example, `previous_sent_per_ip` and `volume_change` are essential for understanding how an IP's activity evolves from one event to the next, while `cumulative_sent_per_ip` shows its overall activity level.

It also includes a helper function `clean_and_round_numeric_columns` to ensure numerical consistency across the DataFrame, which is applied before the final export.

### Initial Datetime Conversion for Feature Engineering

**Goal**: Ensure the primary time-based column (`datetime_gride`) is in the correct format to enable all subsequent time-series calculations without errors. This is a crucial data preparation step.

Similar to earlier, this step confirms `datetime_gride` is a proper datetime column, using `errors='coerce'` to handle any problematic entries by turning them into `NaT`. This robustness ensures that further calculations based on this column (e.g., time differences, hourly/daily extraction) proceed smoothly.

Row‑level lifecycle features
[ignoring loop detection]

Below is a complete, ready‑to‑run Jupyter notebook (PFE_4_ip_lifecycle_analysis.ipynb).
Each cell starts with a short markdown heading that explains what the code does, followed by the implementation.
All code is pure pandas, robust to missing values, and does not train any model.
"""

# Convert the 'datetime_gride' column to a proper pandas datetime format.
# `errors="coerce"` will set any invalid date strings to `NaT` (Not a Time) instead of raising an error.
df["datetime_gride"] = pd.to_datetime(df["datetime_gride"], errors="coerce")

"""### Re-sorting Data for Time-Series Operations

**Goal**: Guarantee that the DataFrame is perfectly ordered by IP and then by event time (`datetime_gride`). This strict ordering is a prerequisite for accurate sequential and cumulative calculations within each IP's activity stream.

This re-sorting is paramount for all time-series feature engineering steps that follow. Operations like `shift()` (to get previous values) and `cumsum()` (to get running totals) will only yield correct results if the data is sorted chronologically *within each group* (i.e., for each IP). `reset_index(drop=True)` cleans up the DataFrame's index after sorting.
"""

# Sort the DataFrame again by 'ip' and 'datetime_gride'.
# This ensures that all subsequent time-series calculations (like shifts or cumulative sums) are performed correctly within each IP's timeline.
# `reset_index(drop=True)` creates a new default integer index and discards the old one.
df = df.sort_values(by=["ip", "datetime_gride"]).reset_index(drop=True)

"""### Re-extracting First Usage Data

**Goal**: Re-calculate and consolidate the first recorded event for each unique IP. This step ensures that the 'first usage' information is consistent and readily available for creating time-since-launch features and first-launch success metrics.

This re-creation of `first_usage` ensures that if any prior data manipulation might have affected its accuracy, it's corrected. It groups the main `df` by IP and takes the first record, then renames key columns for clarity (`first_used_at`, `first_sent_per_ip`, etc.). This summary is then used for IP-level metrics.
"""

# After sorting, the first row for each IP represents its initial activity.
# Group the DataFrame by 'ip', take the first entry for each, and rename columns for clarity.
first_usage = (
    df.groupby("ip", as_index=False)
      .first() # Get the first row for each IP group
      .rename(
          columns={
              "datetime_gride": "first_used_at",
              "sent_per_ip": "first_sent_per_ip",
              "error_type_from_error": "first_error",
              "limit_per_ip": "first_limit",
              "offset": "first_offset",
          }
      )
)

# Select only the essential columns for the 'first_usage' summary to keep it focused
first_usage = first_usage[
    [
        "ip",
        "server",
        "first_used_at",
        "first_sent_per_ip",
        "first_error",
        "first_limit",
        "first_offset",
    ]
]

"""### Re-evaluating First-Launch Success Condition

**Goal**: To re-apply the success criteria for an IP's initial launch, ensuring that this critical binary flag (`first_launch_success`) is accurately determined based on the latest `first_usage` data.

This step re-applies the logic that defines a 'successful' first launch: no error occurred or a specific rate limit/netblock error occurred (`'No error'`, `'SPF'`, `'Rate limit SPF'`, `'Rate limit DKIM'`, `'Netblock'`) and the volume sent (`'first_sent_per_ip'`) was below a certain threshold (10,000). It converts the boolean outcome of this condition into a 0 or 1 integer, making it a clear, quantitative feature for IP performance assessment. This is important as the `first_usage` DataFrame might have been re-computed.
"""

# Define the criteria for a successful first launch:
#   1. The 'first_error' column must indicate 'No error' OR one of the specified rate limit/netblock errors.
#   2. The 'first_sent_per_ip' volume must be less than 10,000.
success_cond = (first_usage["first_error"].isin(["Rate limit IP Netblock","No error", "Rate limit SPF", "Rate limit DKIM"])) & \
               (first_usage["first_sent_per_ip"] < 10_000)

# Create a new column 'first_launch_success' as a binary flag (1 for success, 0 for failure).
# This converts the boolean condition into integers.
first_usage["first_launch_success"] = success_cond.astype(int)

"""### Generating First IP Summary Report

**Goal**: To create a concise summary DataFrame (`first_ip_summary`) where each row represents a unique IP, detailing its initial activity and whether its first launch was successful. This serves as a high-level overview of IP onboarding.

This cell copies the `first_usage` DataFrame to `first_ip_summary` and reorders its columns for better readability. This summary table is valuable for understanding the characteristics of new IPs at their point of entry, such as their initial activity volume, any first-time errors, and their launch success status.
"""

# ---------------------------------------------------------
# Cell 9 – First-IP summary (one row per IP)

# 'first_usage' DataFrame already contains the necessary summary information per IP:
#   ip, server, first_used_at, first_sent_per_ip,
#   first_error, first_limit, first_offset, first_launch_success
# A direct copy is made for 'first_ip_summary' to finalize this summary table.

first_ip_summary = first_usage.copy()

# Re-order columns for better readability and presentation (this step is optional).
first_ip_summary = first_ip_summary[
    [
        "ip",
        "server",
        "first_used_at",
        "first_sent_per_ip",
        "first_error",
        "first_limit",
        "first_offset",
        "first_launch_success",
    ]
]

# Display the first few rows of the 'first_ip_summary' DataFrame for a quick check
first_ip_summary.head()

"""### Optional: Exporting First IP Summary

**Goal**: To provide an example of how to save the `first_ip_summary` to an Excel file and download it, allowing for external analysis or sharing of the high-level IP onboarding metrics.

These lines (currently commented out) demonstrate how you would export the `first_ip_summary` DataFrame to an Excel file. This is useful if you want to further analyze this summary data in other tools or share it as a report. The `files.download` command is specific to Google Colab for downloading generated files.
"""

# first_ip_summary.to_excel('/content/first_ip_summary.xlsx', index=False)
# from google.colab import files
# files.download('/content/first_ip_summary.xlsx')

"""### Analyzing First Launch Statistics

**Goal**: To compute and display key summary statistics related to IP first launches, such as the total number of unique IPs, the count of successful vs. failed launches, and the distribution of initial errors and volumes. This provides an immediate understanding of IP onboarding performance.

This step provides a numerical overview of the first launch data. It calculates:
*   The total number of unique IPs.
*   The count of successful and failed first launches (using the `first_launch_success` flag).
*   The distribution of `first_error` types, showing common issues during initial usage.
*   Descriptive statistics (mean, min, max, quartiles) for `first_sent_per_ip`, indicating typical initial volume patterns.
"""

# 1. Calculate and print the total number of unique IP addresses in the dataset
n_ips = df["ip"].nunique()
print(f"Unique IPs: {n_ips}")

# 2. Calculate and print the count of successful first launches based on the 'first_launch_success' flag
n_success = first_ip_summary["first_launch_success"].sum()
print(f"Successful first launches: {n_success}")

# 3. Calculate and print the count of failed first launches by subtracting successful launches from total unique IPs
n_failed = n_ips - n_success
print(f"Failed first launches: {n_failed}")

# 4. Get and print the distribution (counts) of different 'first_error' types, including NaN values
error_dist = first_ip_summary["first_error"].value_counts(dropna=False)
print("\nFirst error distribution:")
print(error_dist)

# 5. Generate and print descriptive statistics (mean, std, min, max, quartiles) for the 'first_sent_per_ip' column
print("\nFirst sent_per_ip statistics:")
print(first_ip_summary["first_sent_per_ip"].describe())

"""### Helper Function for Numeric Column Cleaning

**Goal**: Define a reusable function to standardize numeric columns by converting them to a numeric type, rounding them to whole numbers, and casting them to a nullable integer format. This ensures data quality and consistency.

This function, `clean_and_round_numeric_columns`, is designed to process a list of specified columns within a DataFrame. It's a robust utility that handles potential non-numeric entries by coercing them to `NaN`, rounds numeric values to the nearest integer, and then converts them to `Int64` (pandas' nullable integer type), which can store `NaN` values, unlike standard `int` types.
"""

import pandas as pd
import numpy as np

def clean_and_round_numeric_columns(dataframe, cols_to_fix):
    """
    Cleans and rounds specified numeric columns in a DataFrame.
    Converts columns to numeric, rounds them to the nearest whole number,
    and then casts them to a nullable integer type (Int64).
    """
    print("Processing columns for rounding...")
    for col in cols_to_fix:
        if col in dataframe.columns:
            print(f"  Cleaning and rounding {col}...")
            # Convert column to numeric, coercing errors (non-numeric values become NaN)
            s = pd.to_numeric(dataframe[col], errors='coerce')
            # Round the numeric values and convert to nullable integer type
            dataframe[col] = s.round().astype('Int64')
    return dataframe

"""### Comprehensive Row-Level Feature Engineering

**Goal**: To create an extensive set of time-series and behavioral features for every event of each IP. These features capture dynamics like event sequencing, time since first use, volume changes, cumulative activity, and error patterns, providing a detailed lifecycle view.

This is the most intensive feature engineering block. It performs several key transformations:
*   **Data Type Cleaning**: Ensures numeric columns used in calculations are clean.
*   **Sequential Event Tracking**: Creates `drop_number` and `is_first_drop` to mark the order and initial event for each IP.
*   **Temporal Metrics**: Calculates `days_since_launch` from the IP's `first_used_at` timestamp.
*   **Volume Dynamics**: Computes `previous_sent_per_ip`, `volume_change`, and `growth_rate` to understand how an IP's sending volume changes between events.
*   **Cumulative Activity**: Tracks `cumulative_sent_per_ip` and `daily_cumulative_sent_per_ip` to measure total activity over time and within a day.
*   **Time-of-Day/Week**: Extracts `hour` and `day_of_week` to capture temporal patterns.
*   **Daily Event Count**: `drops_per_day` counts how many events an IP has on a given day.
*   **Categorical Encoding**: `error_code` converts text error types into numerical representations, and `volume_category` discretizes `sent_per_ip` into 'Low', 'Medium', 'High' bands.
*   **Missing Value Handling**: Fills any remaining `NaN`s in the newly created numerical columns with 0, ensuring data integrity for downstream models or analysis.

These features collectively provide a rich context for understanding the behavior and lifecycle of each IP.
"""

import numpy as np
import pandas as pd

# Ensure relevant source numeric columns are clean and numeric before calculations.
# This step handles potential non-numeric entries or commas in numeric strings.
numeric_cols_for_calc = ["sent_per_ip", "r_sent_per_ip", "cumulative_sent_per_ip"]
for col in numeric_cols_for_calc:
    if col in df.columns:
        # Convert column to string, remove commas, then convert to numeric (errors become NaN)
        df[col] = pd.to_numeric(df[col].astype(str).str.replace(",", ""), errors="coerce")

# Helper: Calculate the sequential order of each 'drop' (event) for every IP.
# The first drop gets number 1, the second gets 2, and so on.
df["drop_number"] = df.groupby("ip").cumcount() + 1

# Create a binary flag (1 or 0) indicating if an event is the very first drop for that IP.
df["is_first_drop"] = (df["drop_number"] == 1).astype(int)

# Calculate days elapsed since the first usage of each IP.
# First, create a mapping from IP to its 'first_used_at' timestamp.
first_used_map = first_usage.set_index("ip")["first_used_at"]
# Then, apply this mapping to the main DataFrame to add 'first_used_at' for each row.
df["first_used_at"] = df["ip"].map(first_used_map)

# Calculate the number of days between the current event and the IP's first usage.
df["days_since_launch"] = (df["datetime_gride"] - df["first_used_at"]).dt.days

# Calculate the 'sent_per_ip' volume from the immediately preceding event for the same IP.
# `shift(1)` moves values down by one row within each IP group.
# `fillna(0)` handles the first event for each IP, which would otherwise have a NaN for previous volume.
df["previous_sent_per_ip"] = df.groupby("ip")["sent_per_ip"].shift(1).fillna(0)

# Calculate the absolute change in volume compared to the previous event.
df["volume_change"] = df["sent_per_ip"] - df["previous_sent_per_ip"]

# Calculate the growth rate as the percentage change from the previous volume.
df["growth_rate"] = df["volume_change"] / df["previous_sent_per_ip"]
# Replace infinite values (due to division by zero) and NaNs with 0 to clean the 'growth_rate' column.
df["growth_rate"] = df["growth_rate"].replace([float("inf"), -float("inf")], 0).fillna(0)

# Calculate the cumulative sum of 'sent_per_ip' for each IP up to the current event.
df["cumulative_sent_per_ip"] = df.groupby("ip")["sent_per_ip"].cumsum()

# Extract the hour of the day (0-23) from 'datetime_gride'.
df["hour"] = df["datetime_gride"].dt.hour
# Extract the day of the week (0=Monday, 6=Sunday) from 'datetime_gride'.
df["day_of_week"] = df["datetime_gride"].dt.dayofweek


# Extract the calendar date (without time) from 'datetime_gride'.
df["date"] = df["datetime_gride"].dt.date
# Calculate the cumulative sum of 'sent_per_ip' for each IP within each specific calendar day.
df["daily_cumulative_sent_per_ip"] = df.groupby(["ip", "date"])["sent_per_ip"].transform('cumsum')
df["daily_cumulative_sent_per_ip"] = df["daily_cumulative_sent_per_ip"].fillna(0)

# Calculate the total number of 'drops' (events) for each IP on a given day.
drops_per_day = df.groupby(["ip", "date"]).size().reset_index(name="drops_per_day")
# Merge this 'drops_per_day' count back into the main DataFrame.
df = df.merge(drops_per_day, on=["ip", "date"], how="left")

# Define a mapping from text-based error types to numerical codes.
error_map = {
    "No error": 0,
    "Rate limit SPF": 1,
    "Rate limit DKIM": 2,
    "Rate limit IP Netblock": 3
}
# Apply the error mapping to create a numerical 'error_code' column. Fill any unmapped errors with 0.
df["error_code"] = df["error_type_from_error"].map(error_map).fillna(0)

# Ensure that newly created numerical columns have no missing values (NaNs).
# Fill any remaining NaNs with 0, as appropriate for these feature columns.
fill_cols = [
    "days_since_launch",
    "previous_sent_per_ip",
    "volume_change",
    "cumulative_sent_per_ip",
    "hour",
    "day_of_week",
    "drops_per_day",
    "error_code"
]
for col in fill_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0)

# Define a function to categorize 'sent_per_ip' volume into 'Low', 'Medium', or 'High'.
def categorize_volume(v):
    if v < 10_000:
        return "Low"
    elif v <= 50_000:
        return "Medium"
    else:
        return "High"
# Apply the categorization function to create the 'volume_category' column.
df["volume_category"] = df["sent_per_ip"].apply(categorize_volume)

# Display concise summary information of the DataFrame, including data types and non-null counts.
df.info()

"""# Select a specific subset of columns to create the final 'IP_life' DataFrame.
# This DataFrame contains all the engineered features for IP lifecycle analysis.
IP_life = df[[
    'campaign_id', 'server', 'ip', 'datetime_gride', 'sent_detail',
    'r_sent_detail', 'sent_per_ip', 'r_sent_per_ip', 'offset', 'limit_per_ip', # Changed 'limit' to 'limit_per_ip'
    'error_type_from_error', 'outSum', 'drop_number',
    'is_first_drop', 'first_used_at', 'previous_sent_per_ip',
    'volume_change', 'growth_rate', 'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip', 'volume_category',
    'hour', 'day_of_week',
    'drops_per_day', 'error_code'
]].copy()

# Define a list of columns that should be cleaned, rounded, and converted to integer type.
cols_to_round = [
    'campaign_id', 'sent_detail', 'r_sent_detail', 'sent_per_ip', 'r_sent_per_ip',
    'offset', 'limit_per_ip', 'outSum', 'drop_number', 'is_first_drop', # Changed 'offset_x', 'limit_x' to 'offset', 'limit_per_ip'
    'previous_sent_per_ip', 'volume_change', 'growth_rate', 'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip', 'hour', 'day_of_week',
    'drops_per_day', 'error_code'
]

# Apply the custom cleaning and rounding function to the specified columns in 'IP_life'.
IP_life = clean_and_round_numeric_columns(IP_life, cols_to_round)

# Save the final 'IP_life' DataFrame to an Excel file without the DataFrame index.
IP_life.to_excel('IP_LifeCycle.xlsx', index=False)
print("File successfully created: IP_LifeCycle.xlsx")
"""

# Select a specific subset of columns to create the final 'IP_life' DataFrame.
# This DataFrame contains all the engineered features for IP lifecycle analysis.
IP_life = df[[
    'campaign_id', 'server', 'ip', 'datetime_gride', 'sent_detail',
    'r_sent_detail', 'sent_per_ip', 'r_sent_per_ip', 'offset',"limit", 'limit_per_ip',
    'error_type_from_error', 'outSum', 'drop_number',
    'is_first_drop', 'first_used_at', 'previous_sent_per_ip',
    'volume_change', 'growth_rate', 'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip', 'volume_category',
    'hour', 'day_of_week',
    'drops_per_day', 'error_code'
]].copy()

# Define a list of columns that should be cleaned, rounded, and converted to integer type.
cols_to_round = [
    'campaign_id', 'sent_detail', 'r_sent_detail', 'sent_per_ip', 'r_sent_per_ip',
    'offset', "limit",'limit_per_ip', 'outSum', 'drop_number', 'is_first_drop',
    'previous_sent_per_ip', 'volume_change', 'growth_rate', 'cumulative_sent_per_ip',
    'daily_cumulative_sent_per_ip', 'hour', 'day_of_week',
    'drops_per_day', 'error_code'
]

# Apply the custom cleaning and rounding function to the specified columns in 'IP_life'.
IP_life = clean_and_round_numeric_columns(IP_life, cols_to_round)

# Save the final 'IP_life' DataFrame to an Excel file without the DataFrame index.
IP_life.to_excel('IP_LifeCycle.xlsx', index=False)
print("File successfully created: IP_LifeCycle.xlsx")

"""### Displaying First Rows of `IP_life`

**Goal**: To quickly inspect the structure and content of the newly created `IP_life` DataFrame, verifying that the feature engineering steps were successful and the data looks as expected.

Displaying the head of the `IP_life` DataFrame allows for a visual check of the engineered features. This is a common practice to ensure that the data processing steps have produced the desired output and that the DataFrame is ready for subsequent analysis or modeling.

## Final IP Lifecycle Analysis Data (`IP_life`)
"""

# Display the first few rows of the final 'IP_life' DataFrame.
# This allows for a quick inspection of the engineered features.
display(IP_life.head())

"""### Optional: Exporting `IP_life` DataFrame

**Goal**: To provide an example of how to save the final `IP_life` DataFrame to an Excel file and download it, allowing for the processed data to be used in other applications or shared.

These lines (currently commented out) show how to export the comprehensive `IP_life` DataFrame to an Excel file. This is useful for archiving the processed data or for loading it into other tools for further visualization, reporting, or machine learning tasks. The `files.download` command facilitates downloading the file directly from the Colab environment.

### Explanation of `IP_life` Columns:

This `IP_life` DataFrame provides a comprehensive view of each IP's lifecycle, incorporating various features derived from the raw data. Here's a breakdown of the key columns:

*   **`campaign_id`**: Identifier for the marketing campaign associated with the IP event.
*   **`server`**: The server that handled the IP event.
*   **`ip`**: The unique IP address.
*   **`datetime_gride`**: Timestamp of the specific grid event.
*   **`sent_detail`**: Detailed volume sent at that specific time.
*   **`r_sent_detail`**: Related 'sent_detail' value, potentially for reconciliation.
*   **`sent_per_ip`**: Volume sent by the IP at this event.
*   **`r_sent_per_ip`**: Related 'sent_per_ip' value, potentially for reconciliation.
*   **`offset`**: An offset value related to the event.
*   **`limit_per_ip`**: The limit assigned per IP, which is considered more important for analysis than the general `limit` column.
*   **`error_type_from_error`**: The type of error detected for this event, if any. 'No error' indicates a successful event.
*   **`outSum`**: A calculated sum, possibly indicating an aggregate output or success metric for dropped IPs.
*   **`drop_number`**: The sequential number of the 'drop' or event for that specific IP (1 for the first event, 2 for the second, etc.).
*   **`is_first_drop`**: A binary flag (1 if it's the first event for that IP, 0 otherwise).
*   **`first_used_at`**: The timestamp when the IP was first observed in the dataset.
*   **`previous_sent_per_ip`**: The volume sent by this IP in its immediately preceding event. This helps in calculating changes over time.
*   **`volume_change`**: The difference in `sent_per_ip` volume compared to the `previous_sent_per_ip` for the same IP.
*   **`growth_rate`**: The percentage change in `sent_per_ip` volume compared to the `previous_sent_per_ip`. (Calculated as `volume_change / previous_sent_per_ip`).
*   **`cumulative_sent_per_ip`**: The running total of `sent_per_ip` volume for that specific IP up to the current event.
*   **`daily_cumulative_sent_per_ip`**: The running total of `sent_per_ip` volume for that specific IP within the current calendar day.
*   **`volume_category`**: A categorical label ('Low', 'Medium', 'High') based on the `sent_per_ip` volume, providing an easy way to understand the scale of activity.
*   **`hour`**: The hour of the day (0-23) when the event occurred, extracted from `datetime_gride`.
*   **`day_of_week`**: The day of the week (0=Monday, 6=Sunday) when the event occurred, extracted from `datetime_gride`.
*   **`sent_ratio`**: The ratio of `r_sent_per_ip` to `sent_per_ip`, indicating message delivery success or reconciliation. (Filled with 0 if `sent_per_ip` is 0).
*   **`limit_usage_ratio`**: The ratio of `sent_per_ip` to `limit_x`, representing how much of the allocated limit for that IP was used. (Filled with 0 if `limit_x` is 0).
*   **`drops_per_day`**: The total number of events (drops) recorded for a given IP on a specific calendar `date`.
*   **`error_code`**: A numerical representation of `error_type_from_error` (0 for 'No error', 1 for 'SPF', 2 for 'RateLimit', 3 for 'Netblock').
*   **`date`**: The calendar date of the event, extracted from `datetime_gride` without the time component.

Certainly! I'll walk you through the entire process step-by-step, explaining what each major section of the code does:

Initial Setup and Data Loading: First, we import necessary libraries like pandas and numpy. We then load the final_merged_data.xlsx into a DataFrame df. Crucially, we convert the datetime_gride column to a proper datetime format and sort the DataFrame by ip and datetime_gride to prepare for time-series calculations.

Detecting First Usage per IP: We create a first_usage DataFrame by grouping the main df by ip and taking the first entry for each IP. This DataFrame captures information about when each IP was first seen, its initial sent_gride volume, and any initial errors.

First-Launch Success Flag: Based on the first_usage DataFrame, we calculate a first_launch_success flag. This flag indicates whether an IP's first activity was 'successful' (defined as 'No error' and initial volume under 10,000).

Generating Row-Level Lifecycle Features: This is a significant step where we add several new columns to the main df DataFrame:

drop_number: Assigns a sequential number to each event (or 'drop') for a given IP.
is_first_drop: A binary flag identifying the very first event for an IP.
days_since_launch: Calculates how many days have passed since an IP's first appearance up to each event.
previous_sent_per_ip: Captures the sent_gride volume from the immediately preceding event for the same IP, which is vital for calculating changes over time.
volume_change and growth_rate: These calculate the absolute and percentage change in sent_gride volume compared to the previous event.
cumulative_sent_per_ip: Computes the running total of sent_gride volume for each IP.
daily_cumulative_sent_per_ip: Calculates the running total of sent_gride volume for each IP within a single calendar day.
volume_category: Categorizes the sent_gride into 'Low', 'Medium', or 'High' based on predefined thresholds.
Final IP_life DataFrame and Export: We select a specific subset of relevant columns from the df to form the IP_life DataFrame. Numeric columns within IP_life are then cleaned, rounded, and converted to integer types for consistency. Finally, this IP_life DataFrame is exported to an Excel file named IP_LifeCycle.xlsx.

Each of these steps builds upon the previous one to transform the raw event data into a comprehensive view of each IP's activity throughout its lifecycle. The explanations provided in the markdown cells within the notebook, especially for the IP_life columns, offer more detailed insights into specific features.
"""

# # The following lines are commented out but show how to save the 'IP_life' DataFrame to an Excel file
# # and then download it in a Colab environment.
# IP_life.to_excel('/content/IP_Analyse.xlsx', index=False)
# from google.colab import files
# files.download('/content/IP_Analyse.xlsx')

"""### Listing `IP_life` Column Names

**Goal**: To provide a complete list of all the feature names available in the final `IP_life` DataFrame. This serves as a reference for understanding the dataset's composition and for selecting features for modeling or analysis.

This command simply prints all column names in the `IP_life` DataFrame. It's a quick way to get an overview of all the engineered features that have been created and are now part of the dataset, which is useful for documentation and for planning subsequent analysis.
"""

# Display all column names present in the 'IP_life' DataFrame.
# This provides a clear overview of the available features.
IP_life.columns

