# -*- coding: utf-8 -*-
"""PFE'3'.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d7Oq6AqVJRSOrChpEz7K8b-qkxP7tyE

## Notebook Overview

This notebook processes three datasets: `DataDetail.csv`, `DataGride.csv`, and `Drop.json`. The goal is to clean, transform, and merge these datasets to create a comprehensive view of campaign performance, focusing on IP-level details and error analysis. The final output, `final_data`, provides a detailed record of sent emails per IP, along with associated errors from the drop data.

Detail Data

This section focuses on loading and cleaning the `DataDetail.csv` file, which contains detailed information about individual sending events for each campaign. The data is transformed to make it suitable for merging and analysis.
"""

import pandas as pd
import json

"""First, we import the necessary libraries: `pandas` for data manipulation and `json` (though `json` is not directly used here, it is imported)."""

detail = pd.read_csv('/content/DataDetail.csv')
detail.info()

"""The `DataDetail.csv` file is loaded into a pandas DataFrame named `detail`. The `detail.info()` method provides a summary of the DataFrame, including the number of entries, column names, non-null counts, and data types, which is crucial for identifying data quality issues and planning cleaning steps."""

detail.head(3)

"""To get a quick glimpse of the data structure and content, the first 3 rows of the `detail` DataFrame are displayed using `detail.head(3)`."""

# creat new dataFrame keep only columns need it
detail_clean = detail[['FK_ID', 'Date', 'Sent', 'R.Sent', 'Offset', 'Limit', 'Server', 'Ips']].copy()

# Rename columns for analyse
detail_clean = detail_clean.rename(columns={
    'FK_ID': 'campaign_id',
    'Date': 'raw_date',
    'Sent': 'sent_detail',
    'R.Sent': 'r_sent_detail',
    'Offset': 'offset',
    'Limit': 'limit',
    'Server': 'server',
    'Ips': 'ips_raw'
})

"""Here, a new DataFrame `detail_clean` is created, selecting only the columns relevant for our analysis. These columns are then renamed to more descriptive and consistent names (e.g., `FK_ID` to `campaign_id`, `Date` to `raw_date`) for better readability and easier manipulation in subsequent steps."""

# cleand columns if we have space and type
detail_clean['server'] = detail_clean['server'].astype(str).str.strip()
detail_clean['raw_date'] = detail_clean['raw_date'].astype(str).str.strip()
detail_clean['ips_raw'] = detail_clean['ips_raw'].astype(str).str.strip()

"""This step ensures consistency by cleaning string-type columns. `astype(str)` converts the column to string type, and `str.strip()` removes any leading or trailing whitespace, which can cause inconsistencies in data matching or analysis."""

# Convert date to the correct forma
import pandas as pd
import re

def parse_detail_datetime(x, year=2026):
    x = str(x).strip()

    date_match = re.search(r'(\d{2})/(\d{2})', x)
    time_match = re.search(r'(\d{2}:\d{2}:\d{2})', x)

    if not date_match:
        return pd.NaT

    day = date_match.group(1)
    month = date_match.group(2)
    time_part = time_match.group(1) if time_match else "00:00:00"

    full_str = f"{year}-{day}-{month} {time_part}"
    return pd.to_datetime(full_str, format="%Y-%m-%d %H:%M:%S", errors="coerce")

detail_clean['datetime'] = detail_clean['raw_date'].apply(parse_detail_datetime)

# Extract date only and time only
detail_clean['date_only'] = detail_clean['datetime'].dt.date
detail_clean['time_only'] = detail_clean['datetime'].dt.time

"""The `raw_date` column contains date and time information in a mixed format (`04/08\n(23:57:44)`). A custom function `parse_detail_datetime` is defined to extract and convert this string into a proper datetime object. A default `year=2026` is assumed as the year is missing from the raw data. This conversion is essential for time-series analysis and accurate merging based on time. New columns `date_only` and `time_only` are then extracted from the `datetime` column."""

detail_clean.head(2)

"""The `detail_clean.head(2)` command is used to display the first two rows of the DataFrame, allowing us to inspect the results of the datetime conversion and ensure the new `datetime`, `date_only`, and `time_only` columns are correctly populated."""

# Transform Ips like a list and number of Ips
def split_ips(val):
    val = str(val).strip()

    if val == '' or val.lower() == 'nan':
        return []

    parts = [ip.strip() for ip in val.split(',') if ip.strip() != '']
    return parts

detail_clean['ips_list'] = detail_clean['ips_raw'].apply(split_ips)
detail_clean['nb_ips'] = detail_clean['ips_list'].apply(len)

"""The `ips_raw` column contains a comma-separated string of IP addresses. The `split_ips` function parses this string into a list of individual IP addresses, stored in the `ips_list` column. Additionally, `nb_ips` is created to count the number of IPs associated with each record, which can be useful for distribution analysis."""

detail_clean.head(2)

"""Displaying the head again helps verify that the IP list and count columns have been correctly added to the `detail_clean` DataFrame."""

# convert numerical columns
num_cols = ['campaign_id', 'sent_detail', 'r_sent_detail', 'offset', 'limit']
for col in num_cols:
    detail_clean[col] = pd.to_numeric(detail_clean[col], errors='coerce')

"""Numerical columns that might have been imported as objects are explicitly converted to a numeric type using `pd.to_numeric`. The `errors='coerce'` argument ensures that any non-numeric values encountered during conversion are turned into `NaN` (Not a Number), preventing errors and allowing for easier handling of problematic data."""

# Sort the data
detail_clean = detail_clean.sort_values(by=['server', 'datetime', 'campaign_id']).reset_index(drop=True)

# final clean data
detail_clean = detail_clean[
    [
        'campaign_id',
        'server',
        'datetime',
        'sent_detail',
        'r_sent_detail',
        'offset',
        'limit',
        'ips_list',
        'nb_ips'
    ]
]

"""The `detail_clean` DataFrame is sorted by `server`, `datetime`, and `campaign_id` to ensure a consistent order, which is beneficial for time-series analysis and merging operations. Finally, only the most relevant columns are selected to form the refined `detail_clean` DataFrame, preparing it for subsequent merges."""

detail_clean.columns

"""This command prints the column names of the `detail_clean` DataFrame, confirming the final set of columns after all the cleaning and selection steps."""

# detail_clean.to_excel('/content/detail_clean.xlsx', index=False)
# from google.colab import files
# files.download('/content/detail_clean.xlsx')

"""These commented-out lines show how to save the `detail_clean` DataFrame to an Excel file and download it, which is useful for inspecting the cleaned data externally.

Gride Data

This section handles the `DataGride.csv` file, which provides campaign-level summary data. Similar to the `detail` data, it undergoes cleaning and transformation to prepare it for merging.
"""

gride = pd.read_csv('/content/DataGride.csv')
gride.info()

"""The `DataGride.csv` file is loaded into the `gride` DataFrame. `gride.info()` gives an overview of its structure, including data types and null values."""

gride.head(2)

"""The first two rows of the `gride` DataFrame are displayed to understand its raw format."""

# crat new dataFrame keep only columns need it
gride_clean = gride[['Date', 'ID', 'Sent', 'R.Sent', 'Profile', 'Server(s)']].copy()

# Reanem columns
gride_clean = gride_clean.rename(columns={
    'Date': 'raw_gride_date',
    'ID': 'campaign_id',
    'Sent': 'sent_gride',
    'R.Sent': 'r_sent_gride',
    'Profile': 'profile',
    'Server(s)': 'servers_raw'
})

"""A new DataFrame `gride_clean` is created, selecting relevant columns from `gride`. Columns are renamed to standardize naming conventions, such as `Date` to `raw_gride_date` and `ID` to `campaign_id`."""

# cleand columns if we have space and type
text_cols = ['raw_gride_date', 'profile', 'servers_raw']
for col in text_cols:
    gride_clean[col] = gride_clean[col].astype(str).str.strip()

"""Similar to the `detail` data, string columns in `gride_clean` are stripped of whitespace to ensure data consistency."""

# convert Date to ral DateTime
import pandas as pd
import re

def parse_gride_datetime(x):
    x = str(x).strip()

    date_match = re.search(r'(\d{2}/\d{2}/\d{4})', x)
    time_match = re.search(r'(\d{2}:\d{2}:\d{2})', x)

    if not date_match:
        return pd.NaT

    date_part = date_match.group(1)
    time_part = time_match.group(1) if time_match else "00:00:00"

    full_str = f"{date_part} {time_part}"
    return pd.to_datetime(full_str, format="%d/%m/%Y %H:%M:%S", errors="coerce")

gride_clean['datetime_gride'] = gride_clean['raw_gride_date'].apply(parse_gride_datetime)

"""The `raw_gride_date` column is converted into datetime objects using a custom `parse_gride_datetime` function. This function specifically handles the date and time format found in `gride_clean`, making the data suitable for time-based operations and merging."""

# Convert numerical Columns
num_cols = ['campaign_id', 'sent_gride', 'r_sent_gride']
for col in num_cols:
    gride_clean[col] = pd.to_numeric(gride_clean[col], errors='coerce')

"""Key numerical columns are converted to a numeric type, ensuring that mathematical operations can be performed accurately and preventing potential type-related errors during analysis."""

# Split servers into a list
def split_servers(val):
    val = str(val).strip()

    if val == '' or val.lower() == 'nan':
        return []

    parts = [s.strip() for s in val.split(',') if s.strip() != '']
    return parts

gride_clean['servers_list'] = gride_clean['servers_raw'].apply(split_servers)
gride_clean['nb_servers'] = gride_clean['servers_list'].apply(len)

"""The `servers_raw` column in the `gride` data can contain multiple server names. The `split_servers` function extracts these names into a list (`servers_list`) and `nb_servers` counts the number of servers, which helps in understanding server allocation per campaign."""

# Keep only columns important
gride_clean = gride_clean[
    [
        'campaign_id',
        'datetime_gride',
        'sent_gride',
        'r_sent_gride',
        'servers_raw',
        'servers_list',
        'nb_servers'
    ]
]

"""Only the essential columns are retained in `gride_clean`, streamlining the DataFrame for later use."""

import re
import pandas as pd

def extract_servers(val):
    val = str(val)
    servers = re.findall(r's_[^\s,]+', val)
    return servers

# extract list
gride_clean['servers_list'] = gride_clean['servers_raw'].apply(extract_servers)

# count real servers
gride_clean['nb_servers'] = gride_clean['servers_list'].apply(len)

# extract raw number if exists
gride_clean['nb_servers_raw'] = gride_clean['servers_raw'].str.extract(r'^(\d+)')
gride_clean['nb_servers_raw'] = pd.to_numeric(gride_clean['nb_servers_raw'], errors='coerce')

# fix missing values
gride_clean['nb_servers_raw'] = gride_clean['nb_servers_raw'].fillna(gride_clean['nb_servers'])

"""This cell refines the server extraction process. The `extract_servers` function uses regular expressions to accurately pull server names (e.g., 's_cmh11_1341') from the `servers_raw` string. It also calculates `nb_servers` based on the extracted list and tries to capture raw server counts if available, ensuring consistency in server counting."""

gride_clean.head(2)

"""The head of `gride_clean` is displayed to verify the server extraction and counting, including the `servers_list`, `nb_servers`, and `nb_servers_raw` columns."""

# Keep only columns important
gride_clean = gride_clean[
    [
        'campaign_id',
        'datetime_gride',
        'sent_gride',
        'r_sent_gride',
        'servers_list',
        'nb_servers'
    ]
]

"""The `gride_clean` DataFrame is finalized by selecting a specific set of columns for optimal usability in subsequent merging operations."""

gride_clean.head(2)

"""The first two rows are displayed to confirm the final structure of `gride_clean`."""

# gride_clean.to_excel('/content/gride_clean.xlsx', index=False)
# from google.colab import files
# files.download('/content/gride_clean.xlsx')

"""These commented-out lines allow for saving and downloading the cleaned `gride_clean` DataFrame, useful for external review.

Merge between Deatil & Gride

This section merges the `detail_clean` (detailed sending events) and `gride_clean` (campaign summaries) DataFrames to combine campaign-level information with individual sending records.
"""

# Check missing values in both datasets
print(detail_clean.isnull().sum())
print(gride_clean.isnull().sum())

"""Before merging, it's good practice to check for missing values in the key DataFrames (`detail_clean` and `gride_clean`) to understand potential data loss or issues during the merge."""

# We should verify that in gride_clean, each campaign_id appears only once.
print("Duplicated campaign_id in gride_clean:", gride_clean['campaign_id'].duplicated().sum())

"""This check ensures that `campaign_id` is unique in `gride_clean` before performing a left merge. If there were duplicates, the merge operation might produce unintended rows."""

# merge detail + gride
final1 = detail_clean.merge(
    gride_clean,
    on='campaign_id',
    how='left'
)

"""The `detail_clean` and `gride_clean` DataFrames are merged using a `left` merge on `campaign_id`. This means all records from `detail_clean` are kept, and matching records from `gride_clean` are added. If no match is found, columns from `gride_clean` will have `NaN` values."""

# Sort to Stay safe
final1 = final1.sort_values(by=['server', 'datetime_gride', 'campaign_id']).reset_index(drop=True)

"""The merged DataFrame `final1` is sorted by `server`, `datetime_gride`, and `campaign_id` to maintain a logical order, which is important for subsequent time-based analysis or grouping."""

# Check merge Work
print("detail_clean shape:", detail_clean.shape)
print("gride_clean shape:", gride_clean.shape)
print("final1 shape:", final1.shape)

"""This step verifies the outcome of the merge by comparing the shapes (rows, columns) of the original DataFrames (`detail_clean`, `gride_clean`) with the resulting `final1` DataFrame. This helps confirm that the merge operation worked as expected and the number of rows is consistent with a left merge."""

final1['server_in_gride_list'] = final1.apply(
    lambda row: row['server'] in row['servers_list'] if isinstance(row['servers_list'], list) else False,
    axis=1
)

"""A new boolean column `server_in_gride_list` is created. This column checks if the individual `server` from `detail_clean` is present within the `servers_list` (list of servers associated with the campaign from `gride_clean`). This is useful for verifying server assignment consistency."""

final1.head(2)

"""The head of `final1` is displayed to show the newly added `server_in_gride_list` column and the integrated data from both `detail_clean` and `gride_clean`."""

final1 = final1[
    [
        'campaign_id',
        'server',
        'datetime_gride',
        'sent_detail',
        'r_sent_detail',
        'offset',
        'limit',
        'ips_list',
        'nb_ips',
        'sent_gride',
        'r_sent_gride',
        'servers_list',
        'server_in_gride_list',
        'nb_servers'
    ]
].copy()

"""The `final1` DataFrame is refined by selecting a specific set of columns that are relevant for the next stage of analysis, ensuring a clean and focused dataset."""

final1['server_in_gride_list'].value_counts(dropna=False)

"""This command provides a count of unique values in the `server_in_gride_list` column, including `NaN` values. This helps quickly assess how often a server from the detail data was found in the corresponding gride server list."""

# Create a copy of final1 for further processing
final1_V2 = final1.copy()

# Explode the 'ips_list' column so each IP gets its own row
final1_V2 = final1_V2.explode('ips_list')

# Rename the exploded column for clarity
final1_V2 = final1_V2.rename(columns={'ips_list': 'ip'})

# Drop the specified columns that are no longer needed
final1_V2 = final1_V2.drop(columns=['servers_list', 'nb_servers', 'nb_ips','server_in_gride_list'], errors='ignore')

# Display the head of the new DataFrame
display(final1_V2.head())

"""To prepare for IP-level analysis, `final1` is copied to `final1_V2`. The `ips_list` column, which contains a list of IPs, is then 'exploded'. This means that if a row has multiple IPs in its `ips_list`, it will be duplicated, with each duplicate row containing a single IP from that list. This transforms the data from a server-level view to an IP-level view. The `servers_list`, `nb_servers`, and `nb_ips` columns are dropped as they are no longer needed in this exploded, IP-centric view."""

# final1_V2.to_excel('/content/final1_ready_V2.xlsx', index=False)
# from google.colab import files
# files.download('/content/final1_ready_V2.xlsx')

"""These commented-out lines show how to save and download `final1_V2` as an Excel file, which can be useful for debugging or external analysis of the IP-exploded data.

Data Drop

This section processes the `Drop.json` file, which contains information about email sending failures or 'drops'. The data is extracted, cleaned, and enriched to identify specific IPs, servers, and error types associated with these drops. This information will then be merged with the main dataset.
"""

with open('/content/Drop.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

"""The `Drop.json` file is loaded using the `json` library, and the content is stored in the `data` variable. The `encoding='utf-8'` ensures proper handling of various characters."""

drop = pd.DataFrame(data)
drop.info()

"""The loaded `data` (which is a list of dictionaries) is converted into a pandas DataFrame named `drop`. `drop.info()` then displays a summary of this DataFrame, including column names, non-null counts, and data types, similar to previous datasets."""

drop.head(2)

"""The first two rows of the `drop` DataFrame are displayed to understand its structure and content."""

print(f"{drop['fullMessage'][0]}/n")

"""This line prints the `fullMessage` from the first record in the `drop` DataFrame. This column often contains detailed, human-readable information about the drop event, including servers, IPs, and error messages, which guides the extraction of structured error data."""

# Creat DataFram Drop
drop_clean = drop[['byIp', 'fullMessage', 'limit', 'offset', 'outSum', 'totalIps', 'reportTime', 'ipMap']].copy()

# Rename Columns
drop_clean = drop_clean.rename(columns={
    'byIp': 'by_ip',
    'fullMessage': 'full_message',
    'reportTime': 'raw_report_time',
    'ipMap': 'ip_map_raw'
})

"""A new DataFrame `drop_clean` is created by selecting a subset of relevant columns from `drop`. These columns are then renamed for clarity and consistency, such as `byIp` to `by_ip` and `reportTime` to `raw_report_time`."""

# Avoid Problem od spaces
text_cols = ['by_ip', 'full_message', 'raw_report_time', 'ip_map_raw']
for col in text_cols:
    drop_clean[col] = drop_clean[col].astype(str).str.strip()

"""Whitespace is removed from key string columns in `drop_clean` to ensure data consistency and prevent issues with matching or parsing."""

# Correct column of ReportTime
def parse_drop_datetime(x, year=2026):
    x = str(x).strip()

    # extract day/month
    date_match = re.search(r'(\d{2})/(\d{2})', x)

    # extract time
    time_match = re.search(r'(\d{2}:\d{2}:\d{2})', x)

    if not date_match:
        return pd.NaT

    day = date_match.group(1)
    month = date_match.group(2)
    time_part = time_match.group(1) if time_match else "00:00:00"

    # build full datetime
    full_str = f"{year}-{month}-{day} {time_part}"

    return pd.to_datetime(full_str, format="%Y-%m-%d %H:%M:%S", errors="coerce")

# apply
drop_clean['datetime_drop'] = drop_clean['raw_report_time'].apply(parse_drop_datetime)

"""A custom function `parse_drop_datetime` is used to convert the `raw_report_time` string into a datetime object. This function extracts the day, month, and time from the string, assuming a `year=2026`, and converts it to a standard datetime format. This is crucial for time-based merging with other datasets."""

drop_clean['datetime_drop'].isnull().sum()

"""This checks how many entries in the `datetime_drop` column are `NaN` (Not a Time), indicating rows where the datetime conversion failed. This helps assess the quality of the date parsing."""

drop_clean.head(2)

"""The head of `drop_clean` is displayed to verify that the `datetime_drop` column has been correctly populated after the conversion."""

# Extract name of server from FullMsg
import re

def extract_servers_from_message(msg):
    msg = str(msg)
    servers = re.findall(r's_[A-Za-z0-9_]+', msg)
    return list(dict.fromkeys(servers))  # remove duplicates, keep order

drop_clean['servers_drop_list'] = drop_clean['full_message'].apply(extract_servers_from_message)

# nbr of server
drop_clean['nb_servers_drop'] = drop_clean['servers_drop_list'].apply(len)

"""The `extract_servers_from_message` function uses regular expressions to find server names (e.g., `s_cmh2_6145`) within the `full_message` column. This extracts the list of servers related to each drop event. `nb_servers_drop` then counts these extracted servers."""

# Extract Ip from IpMap
def extract_ips(text):
    text = str(text)
    ips = re.findall(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', text)
    return list(dict.fromkeys(ips))  # remove duplicates, keep order

drop_clean['ips_list_drop'] = drop_clean['ip_map_raw'].apply(extract_ips)
drop_clean['nb_ips_drop'] = drop_clean['ips_list_drop'].apply(len)

"""Similarly, the `extract_ips` function uses regular expressions to identify IP addresses from the `ip_map_raw` column, which typically contains a dictionary-like string of IPs and their specific errors. These IPs are stored in `ips_list_drop`, and their count is stored in `nb_ips_drop`."""

# List of the error
ERROR_PATTERNS = [
    'dkim = did not pass',
    'Rate limit SPF - Suspicious',
    'Rate limit IP Netblock',
    'Rate limit SPF',
    'Rate limit DKIM',
    'Rate limit unsolicited',
    'Message rejected 550',
    'Message blocked - unsolicited',
    'Low reputation domain',
    'TLS required',
    'Connection closed',
    'Server Busy'
]

# extract all matching errors from full_message
def extract_error_detail(msg):
    msg = str(msg)
    msg_lower = msg.lower()

    found = []
    for err in ERROR_PATTERNS:
        if err.lower() in msg_lower:
            found.append(err)

    if len(found) == 0:
        return ['Other']

    return found

drop_clean['error_detail'] = drop_clean['full_message'].apply(extract_error_detail)

"""A predefined list of `ERROR_PATTERNS` is used to identify specific types of errors within the `full_message` text. The `extract_error_detail` function checks for the presence of these patterns and populates the `error_detail` column with a list of detected errors for each drop event. If no specific pattern is found, it defaults to 'Other'."""

# nbr of error detected
drop_clean['nb_errors_detected'] = drop_clean['error_detail'].apply(len)

"""The `nb_errors_detected` column is created to count how many distinct error patterns were identified for each drop record, providing a quick summary of error complexity."""

# Convert column to numeric columns
num_cols = ['by_ip', 'limit', 'offset', 'outSum', 'totalIps']
for col in num_cols:
    drop_clean[col] = pd.to_numeric(drop_clean[col], errors='coerce')

"""All relevant numerical columns in `drop_clean` are converted to a numeric data type, using `errors='coerce'` to handle any values that cannot be converted by turning them into `NaN`."""

drop_clean.head(2)

"""The head of `drop_clean` is displayed to review the results of server, IP, and error extraction, as well as numerical conversions."""

drop_clean_v2 = drop_clean[
    [
        'datetime_drop',
        'servers_drop_list',
        'nb_servers_drop',
        'nb_ips_drop',
        'by_ip',
        'limit',
        'offset',
        'outSum',
        'totalIps', # Include totalIps here
        'error_detail',
        'nb_errors_detected'
    ]
].copy()

"""A new DataFrame `drop_clean_v2` is created, retaining only the columns essential for merging with the main dataset. This includes datetime, server/IP lists, drop metrics, and error details."""

drop_clean_v2.head(2)

"""The head of `drop_clean_v2` is displayed for a quick verification of its structure and content after column selection."""

# IP Errors detected
import json

def extract_ip_errors(ip_map_str):
    if not ip_map_str or ip_map_str.lower() == 'nan':
        return []
    try:
        ip_map = json.loads(ip_map_str.replace("\'", "\"")) # Handle single quotes in JSON string
    except json.JSONDecodeError:
        return []

    ip_errors = []
    for ip, errors in ip_map.items():
        for error in errors:
            ip_errors.append({'ip': ip, 'error': error})
    return ip_errors

drop_clean_v2['ip_errors'] = drop_clean['ip_map_raw'].apply(extract_ip_errors)

"""The `extract_ip_errors` function parses the `ip_map_raw` column (which is a string representation of a dictionary) to extract individual IP addresses and their associated error messages. This is crucial for linking specific errors to specific IPs during the merge. The result is stored as a list of dictionaries in the `ip_errors` column."""

drop_clean_v2.head(2)

"""The head of `drop_clean_v2` is displayed to show the newly added `ip_errors` column."""

# Explode the 'ip_errors' column so each IP-error pair gets its own row
drop_exploded = drop_clean_v2.explode('ip_errors')

# Extract 'ip' from the exploded 'ip_errors' column
drop_exploded['ip'] = drop_exploded['ip_errors'].apply(lambda x: x.get('ip') if isinstance(x, dict) else None)

# Drop the original 'ip_errors' column as it is now expanded
drop_exploded = drop_exploded.drop(columns=['ip_errors'])

display(drop_exploded.head())

"""The `ip_errors` column, which contains a list of IP-error dictionaries, is 'exploded' into `drop_exploded`. This means each IP-error pair gets its own row, transforming the data to a granular IP-error level. The IP address is then extracted into a new `ip` column, and the original `ip_errors` column is dropped."""

# Explode the 'ip_errors' column to get one row per IP-error pair
drop_final = drop_clean_v2.explode('ip_errors')

# Extract 'ip' and 'error' into new columns
drop_final['ip_from_error'] = drop_final['ip_errors'].apply(lambda x: x.get('ip') if isinstance(x, dict) else None)
drop_final['error_type_from_error'] = drop_final['ip_errors'].apply(lambda x: x.get('error') if isinstance(x, dict) else None)

# Drop the original 'ip_errors' column as it is now redundant
# The 'ips_list_drop' column was already excluded when drop_clean_v2 was created,
# so attempting to drop it here would cause a KeyError.
drop_final = drop_final.drop(columns=['ip_errors'])

# Display the head of the new DataFrame
display(drop_final.head())

"""This step further refines the exploded drop data. `drop_final` is created by exploding `ip_errors` from `drop_clean_v2`. Then, `ip_from_error` and `error_type_from_error` columns are created to explicitly separate the IP and the specific error type from each dictionary within the `ip_errors` list. The original `ip_errors` column is then dropped."""

drop_final.columns

"""This command lists the columns of the `drop_final` DataFrame, confirming the successful extraction of `ip_from_error` and `error_type_from_error`."""

# Create a subset of drop_final with required columns for merging
drop_for_merge = drop_final[
    [
        'datetime_drop',
        'servers_drop_list',
        'limit',
        'outSum',
        'by_ip',
        'totalIps',
        'ip_from_error',
        'error_type_from_error'
    ]
].copy()

# Extract the single server string from the list in 'servers_drop_list'
# Handle cases where the list might be empty or contain non-string elements
drop_for_merge['server'] = drop_for_merge['servers_drop_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
drop_for_merge = drop_for_merge.drop(columns=['servers_drop_list']) # Drop the original list column

# Rename 'ip_from_error' to 'ip' for consistent merging with final1_V2
drop_for_merge = drop_for_merge.rename(columns={'ip_from_error': 'ip'})


# Display the head of the new DataFrame
display(drop_for_merge.head())

"""This cell creates `drop_for_merge`, a prepared version of the drop data for merging. It selects specific columns, extracts a single `server` name from `servers_drop_list`, renames `ip_from_error` to `ip`, and calculates `outSum_per_ip` and `by_ip_per_ip` by dividing `outSum` and `by_ip` by `totalIps`. This ensures that drop-related metrics are standardized per IP address."""

# Re-run the drop_for_merge creation after changes
# Create a subset of drop_final with required columns for merging
drop_for_merge = drop_final[
    [
        'datetime_drop',
        'servers_drop_list',
        'limit',
        'outSum',
        'totalIps',
        'ip_from_error',
        'error_type_from_error'
    ]
].copy()

# Extract the single server string from the list in 'servers_drop_list'
# Handle cases where the list might be empty or contain non-string elements
drop_for_merge['server'] = drop_for_merge['servers_drop_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
drop_for_merge = drop_for_merge.drop(columns=['servers_drop_list']) # Drop the original list column

# Rename 'ip_from_error' to 'ip' for consistent merging with final1_V2
drop_for_merge = drop_for_merge.rename(columns={'ip_from_error': 'ip'})

# Calculate outSum_per_ip and by_ip_per_ip based on totalIps
drop_for_merge['totalIps'] = pd.to_numeric(drop_for_merge['totalIps'], errors='coerce')





# Display the head of the new DataFrame
display(drop_for_merge.head())

"""This cell re-runs the previous cell's code to ensure `drop_for_merge` is updated with any recent changes or definitions, particularly after any modifications to the `calculate_ip_distribution` function or related logic."""

# Re-run the merge after updating drop_for_merge
import numpy as np

# Drop rows with NaN in merge keys before sorting
final1_V2_clean = final1_V2.dropna(subset=['server', 'ip', 'datetime_gride']).copy()
drop_for_merge_clean = drop_for_merge.dropna(subset=['server', 'ip', 'datetime_drop']).copy()

# Ensure datetime columns are of datetime type
final1_V2_clean['datetime_gride'] = pd.to_datetime(final1_V2_clean['datetime_gride'])
drop_for_merge_clean['datetime_drop'] = pd.to_datetime(drop_for_merge_clean['datetime_drop'])

# List to store merged results from each group
merged_parts = []

# Get all unique server-IP pairs from final1_V2_clean to iterate through
unique_server_ip_pairs = final1_V2_clean[['server', 'ip']].drop_duplicates().values

for server_name, ip_val in unique_server_ip_pairs:
    # Filter dataframes for the current server and IP
    current_final1_subset = final1_V2_clean[
        (final1_V2_clean['server'] == server_name) &
        (final1_V2_clean['ip'] == ip_val)
    ].sort_values(by='datetime_gride').reset_index(drop=True)

    current_drop_subset = drop_for_merge_clean[
        (drop_for_merge_clean['server'] == server_name) &
        (drop_for_merge_clean['ip'] == ip_val)
    ].sort_values(by='datetime_drop').reset_index(drop=True)

    # Only proceed with merge if both subsets have data
    if not current_final1_subset.empty and not current_drop_subset.empty:
        # Perform merge_asof for the current group
        merged_group = pd.merge_asof(
            current_final1_subset,
            current_drop_subset,
            left_on='datetime_gride',
            right_on='datetime_drop',
            direction='nearest',
            tolerance=pd.Timedelta('20min'),
            suffixes=('_detail', '_drop')
        )
        merged_parts.append(merged_group)

# Concatenate all merged parts
if merged_parts:
    final_merged_df = pd.concat(merged_parts, ignore_index=True)
else:
    # If no merges happened (e.g., no common server/IP pairs), create an empty DataFrame
    final_merged_df = pd.DataFrame(columns=list(final1_V2_clean.columns) + [col + '_drop' for col in drop_for_merge_clean.columns if col not in ['server', 'ip']])

# Fill NaN in error_type_from_error with 'No error'
final_merged_df['error_type_from_error'] = final_merged_df['error_type_from_error'].fillna('No error')

# Drop datetime_drop and other _drop columns that are now redundant
# Note: 'limit_drop' and 'outSum' are kept as they are useful for error analysis
final_merged_df = final_merged_df.drop(columns=[
    'datetime_drop'
], errors='ignore')

# Rename columns to remove suffixes and align names for clarity
final_merged_df = final_merged_df.rename(columns={
    'server_detail': 'server',
    'ip_detail': 'ip',
    'offset_detail': 'offset',
    'limit_detail': 'limit'
})

display(final_merged_df.head())

# drop_for_merge.to_excel('/content/drop_for_merge.xlsx', index=False)
# from google.colab import files
# files.download('/content/drop_for_merge.xlsx')

"""Merge Between final1_v2 & DropData_v2"""

import numpy as np

# Drop rows with NaN in merge keys before sorting
final1_V2_clean = final1_V2.dropna(subset=['server', 'ip', 'datetime_gride']).copy()
drop_for_merge_clean = drop_for_merge.dropna(subset=['server', 'ip', 'datetime_drop']).copy()

# Ensure datetime columns are of datetime type
final1_V2_clean['datetime_gride'] = pd.to_datetime(final1_V2_clean['datetime_gride'])
drop_for_merge_clean['datetime_drop'] = pd.to_datetime(drop_for_merge_clean['datetime_drop'])

# List to store merged results from each group
merged_parts = []

# Get all unique server-IP pairs from final1_V2_clean to iterate through
unique_server_ip_pairs = final1_V2_clean[['server', 'ip']].drop_duplicates().values

for server_name, ip_val in unique_server_ip_pairs:
    # Filter dataframes for the current server and IP
    current_final1_subset = final1_V2_clean[
        (final1_V2_clean['server'] == server_name) &
        (final1_V2_clean['ip'] == ip_val)
    ].sort_values(by='datetime_gride').reset_index(drop=True)

    current_drop_subset = drop_for_merge_clean[
        (drop_for_merge_clean['server'] == server_name) &
        (drop_for_merge_clean['ip'] == ip_val)
    ].sort_values(by='datetime_drop').reset_index(drop=True)

    # Only proceed with merge if both subsets have data
    if not current_final1_subset.empty and not current_drop_subset.empty:
        # Perform merge_asof for the current group
        merged_group = pd.merge_asof(
            current_final1_subset,
            current_drop_subset,
            left_on='datetime_gride',
            right_on='datetime_drop',
            direction='nearest',
            tolerance=pd.Timedelta('20min'),
            suffixes=('_detail', '_drop')
        )
        merged_parts.append(merged_group)

# Concatenate all merged parts
if merged_parts:
    final_merged_df = pd.concat(merged_parts, ignore_index=True)
else:
    # If no merges happened (e.g., no common server/IP pairs), create an empty DataFrame
    final_merged_df = pd.DataFrame(columns=list(final1_V2_clean.columns) + [col + '_drop' for col in drop_for_merge_clean.columns if col not in ['server', 'ip']])

# Fill NaN in error_type_from_error with 'No error'
final_merged_df['error_type_from_error'] = final_merged_df['error_type_from_error'].fillna('No error')

# Drop datetime_drop and other _drop columns that are now redundant
# Note: 'limit_drop' and 'outSum' are kept as they are useful for error analysis
final_merged_df = final_merged_df.drop(columns=[
    'datetime_drop'
], errors='ignore')

# Rename columns to remove suffixes and align names for clarity
final_merged_df = final_merged_df.rename(columns={
    'server_detail': 'server',
    'ip_detail': 'ip',
    'offset_detail': 'offset',
    'limit_detail': 'limit'
})

display(final_merged_df.head())

"""This is the crucial merging step. It performs a `pd.merge_asof` between `final1_V2` (IP-exploded detail and gride data) and `drop_for_merge` (IP-level drop data). The merge is done on `server` and `ip`, and importantly, it's a *nearest* time-based merge (`datetime_gride` with `datetime_drop`) with a `tolerance` of `20min`. This means it finds the closest drop event within a 20-minute window for each sending event. `NaN` values in `error_type_from_error` are filled with 'No error', and redundant `_drop` columns are removed. Finally, columns are renamed for consistency.

This cell contains the `calculate_ip_distribution` function. Its main purpose is to attribute the total sent and received counts (from `sent_detail` and `r_sent_detail`) to individual IP addresses within each unique campaign, server, and datetime group. It first identifies the number of IPs in each group (`nb_ips_in_campaign`). Then, for each group, it divides the `total_sent_detail` and `total_r_sent_detail` equally among all IPs belonging to that group, resulting in `sent_per_ip` and `r_sent_per_ip` columns. It also includes verification steps (`total_sent_calc_per_group`, `sent_diff`, etc.) to ensure that the sum of `sent_per_ip` and `r_sent_per_ip` for all IPs in a group matches the original group totals.
"""

import numpy as np
pd.set_option('future.no_silent_downcasting', True)

def calculate_ip_distribution(df):
    # Group by campaign, server, and datetime to process each unique sending event
    # Using .copy() to prevent SettingWithCopyWarning for modification inside the loop
    df = df.copy()

    # Calculate the number of IPs in each group
    df['nb_ips_in_campaign'] = df.groupby(['campaign_id', 'server', 'datetime_gride'])['ip'].transform('count')

    # Identify IPs with actual errors (not 'No error')
    df['ip_has_error'] = df['error_type_from_error'].notna() & (df['error_type_from_error'] != 'No error')

    # Initialize new columns with NaN to handle cases where a group might not be processed or to clearly mark missing data
    df['sent_per_ip'] = np.nan
    df['r_sent_per_ip'] = np.nan
    df['limit_per_ip'] = np.nan # New column for limit per IP

    for (campaign, server, dt), group in df.groupby(['campaign_id', 'server', 'datetime_gride'], as_index=False):
        total_sent_detail = group['sent_detail'].iloc[0]
        total_r_sent_detail = group['r_sent_detail'].iloc[0]
        total_limit = group['limit'].iloc[0] # Get the total limit for the group
        num_ips_in_group = group['nb_ips_in_campaign'].iloc[0] # All rows in the group will have the same num_ips_in_group

        if num_ips_in_group > 0:
            # 1. Distribute sent_per_ip equally across all IPs as per requirement 1
            sent_per_ip_base = total_sent_detail // num_ips_in_group
            sent_per_ip_remainder = total_sent_detail % num_ips_in_group

            # Distribute base and remainder for sent_per_ip
            sent_values = [sent_per_ip_base] * num_ips_in_group
            for i in range(sent_per_ip_remainder):
                sent_values[i] += 1
            df.loc[group.index, 'sent_per_ip'] = sent_values

            # 2. Distribute limit_per_ip equally across all IPs
            limit_per_ip_base = total_limit // num_ips_in_group
            limit_per_ip_remainder = total_limit % num_ips_in_group

            limit_values = [limit_per_ip_base] * num_ips_in_group
            for i in range(limit_per_ip_remainder):
                limit_values[i] += 1
            df.loc[group.index, 'limit_per_ip'] = limit_values

            # 3. Distribute r_sent_per_ip based on error status and lost volume
            if total_sent_detail <= total_r_sent_detail: # Case: sent_detail <= r_sent_detail
                # No impact from errors, or an anomaly where r_sent > sent, distribute r_sent_detail equally
                r_sent_per_ip_base = total_r_sent_detail // num_ips_in_group
                r_sent_per_ip_remainder = total_r_sent_detail % num_ips_in_group

                r_sent_values_equal_dist = [r_sent_per_ip_base] * num_ips_in_group
                for i in range(r_sent_per_ip_remainder):
                    r_sent_values_equal_dist[i] += 1
                df.loc[group.index, 'r_sent_per_ip'] = r_sent_values_equal_dist
            else: # Case: sent_detail > r_sent_detail (some volume was lost)
                # Start with the sent_per_ip values as the potential received for each IP
                r_sent_values_potential = df.loc[group.index, 'sent_per_ip'].copy()

                lost_emails_to_absorb = total_sent_detail - total_r_sent_detail

                # Identify safe and error IPs within the current group
                safe_ips_indices = group[~group['ip_has_error']].index
                error_ips_indices = group[group['ip_has_error']].index

                num_safe_ips = len(safe_ips_indices)
                num_error_ips = len(error_ips_indices)

                # Create a temporary array for r_sent_per_ip calculation to avoid modifying DataFrame in loop
                temp_r_sent = r_sent_values_potential.to_numpy()
                group_indices = group.index.to_numpy()

                # First, try to absorb all lost emails from error IPs
                if num_error_ips > 0:
                    error_ip_positions_in_group = [np.where(group_indices == idx)[0][0] for idx in error_ips_indices]

                    for _ in range(int(lost_emails_to_absorb)):
                        if lost_emails_to_absorb == 0: break
                        # Prioritize IPs with errors to absorb loss
                        # Find an error IP that still has volume to reduce
                        eligible_error_ips = [pos for pos in error_ip_positions_in_group if temp_r_sent[pos] > 0]
                        if eligible_error_ips: # If there are error IPs that can absorb loss
                            # Simple round-robin distribution of 1 unit of loss
                            target_pos = eligible_error_ips[0] # Pick the first eligible error IP
                            temp_r_sent[target_pos] -= 1
                            lost_emails_to_absorb -= 1
                        else: # All error IPs are at 0, break and distribute remaining to safe IPs
                            break

                # If there's still lost volume, distribute it among safe IPs
                if lost_emails_to_absorb > 0 and num_safe_ips > 0:
                    safe_ip_positions_in_group = [np.where(group_indices == idx)[0][0] for idx in safe_ips_indices]

                    for _ in range(int(lost_emails_to_absorb)):
                        if lost_emails_to_absorb == 0: break
                        eligible_safe_ips = [pos for pos in safe_ip_positions_in_group if temp_r_sent[pos] > 0]
                        if eligible_safe_ips: # If there are safe IPs that can absorb loss
                            target_pos = eligible_safe_ips[0] # Pick the first eligible safe IP
                            temp_r_sent[target_pos] -= 1
                            lost_emails_to_absorb -= 1
                        else:
                            break

                df.loc[group.index, 'r_sent_per_ip'] = temp_r_sent

        else: # num_ips_in_group == 0 (robustness)
            df.loc[group.index, 'sent_per_ip'] = 0
            df.loc[group.index, 'r_sent_per_ip'] = 0
            df.loc[group.index, 'limit_per_ip'] = 0

    # Ensure final columns are floats before filling NaNs with 0
    df['sent_per_ip'] = df['sent_per_ip'].astype(float).fillna(0)
    df['r_sent_per_ip'] = df['r_sent_per_ip'].astype(float).fillna(0)
    df['limit_per_ip'] = df['limit_per_ip'].astype(float).fillna(0)

    # Verification columns (optional, for debugging)
    df['total_sent_calc_per_group'] = df.groupby(['campaign_id', 'server', 'datetime_gride'])['sent_per_ip'].transform('sum')
    df['total_r_sent_calc_per_group'] = df.groupby(['campaign_id', 'server', 'datetime_gride'])['r_sent_per_ip'].transform('sum')
    df['total_limit_calc_per_group'] = df.groupby(['campaign_id', 'server', 'datetime_gride'])['limit_per_ip'].transform('sum')

    df['sent_diff'] = df['total_sent_calc_per_group'] - df['sent_detail']
    df['r_sent_diff'] = df['total_r_sent_calc_per_group'] - df['r_sent_detail']
    df['limit_diff'] = df['total_limit_calc_per_group'] - df['limit']

    return df

final_merged_df_V2 = calculate_ip_distribution(final_merged_df)

# Display relevant columns to verify the distribution
display(final_merged_df_V2[['campaign_id', 'server', 'datetime_gride', 'ip',
                         'sent_detail', 'r_sent_detail', 'limit', 'error_type_from_error',
                         'nb_ips_in_campaign', 'ip_has_error', 'sent_per_ip', 'r_sent_per_ip', 'limit_per_ip',
                         'total_sent_calc_per_group', 'sent_diff',
                         'total_r_sent_calc_per_group', 'r_sent_diff',
                         'total_limit_calc_per_group', 'limit_diff']].head(2))

"""This cell re-runs the `calculate_ip_distribution` function on the `final_merged_df` and then displays the head of the `final_merged_df_V2` DataFrame. This ensures that the IP-level distribution (i.e., `sent_per_ip` and `r_sent_per_ip`) is re-calculated and verified, showing how the total campaign sends are distributed among individual IPs."""

# Display the head of the DataFrame after all calculations and before final column selection
display(final_merged_df_V2.head(2))

"""This cell explicitly displays the first few rows of `final_merged_df_V2` after all calculations, allowing for a comprehensive check of all columns and their values, including the newly calculated `sent_per_ip` and `r_sent_per_ip`."""

# final_merged_df_V2.to_excel('/content/test.xlsx', index=False)
# from google.colab import files
# files.download('/content/test.xlsx')

"""These commented-out lines would allow you to save and download the `final_merged_df_V2` DataFrame as an Excel file for external use or sharing.

### Verification of IP-Level Distribution

To ensure the `sent_per_ip` and `r_sent_per_ip` calculations are correct, we will aggregate these new columns back to the `campaign_id`, `server_detail`, and `datetime_gride` level and compare them against the original `sent_detail` and `r_sent_detail`.

Ideally, the `sent_diff` and `r_sent_diff` columns (which represent the difference between the aggregated IP-level sends and the original totals) should be very close to zero.

This markdown cell introduces the verification process for the IP-level distribution, explaining its importance for ensuring data integrity.
"""

# Perform the aggregation for verification
verification_df = final_merged_df_V2.groupby(['campaign_id', 'server', 'datetime_gride']).agg(
    original_sent_detail=('sent_detail', 'first'),
    original_r_sent_detail=('r_sent_detail', 'first'),
    sum_sent_per_ip=('sent_per_ip', 'sum'),
    sum_r_sent_per_ip=('r_sent_per_ip', 'sum')
).reset_index()

# Calculate the differences
verification_df['sent_deviation'] = verification_df['sum_sent_per_ip'] - verification_df['original_sent_detail']
verification_df['r_sent_deviation'] = verification_df['sum_r_sent_per_ip'] - verification_df['original_r_sent_detail']

# Display rows with significant deviations (e.g., greater than a small epsilon)
epsilon = 0.001  # Tolerance for floating point comparisons
deviations = verification_df[
    (abs(verification_df['sent_deviation']) > epsilon) |
    (abs(verification_df['r_sent_deviation']) > epsilon)
]

if deviations.empty:
    print("No significant deviations found. IP-level distribution sums match original totals.")
else:
    print("Deviations found in IP-level distribution:")
    display(deviations)

"""This cell performs the verification of the IP-level distribution. It groups the `final_merged_df_V2` by `campaign_id`, `server`, and `datetime_gride`, then aggregates `sent_per_ip` and `r_sent_per_ip` to sum them up. These sums are then compared against the original `sent_detail` and `r_sent_detail` values. `sent_deviation` and `r_sent_deviation` are calculated, and the code checks for any significant deviations (beyond a small `epsilon` tolerance). If no significant deviations are found, it confirms that the IP-level distribution accurately reflects the original totals.

### Final Column Selection and Data Summary

This section outlines the final steps of data preparation, including selecting the most relevant columns for the final dataset and providing a summary of the entire data processing journey.
"""

# Select final columns for the merged DataFrame
final_data = final_merged_df_V2[[
    'campaign_id',
    'server',
    'ip',
    'datetime_gride',
    'sent_detail',
    'r_sent_detail',
    'sent_per_ip',
    'r_sent_per_ip',
    'offset',
    'limit',
    'limit_per_ip',
    'outSum',
    'error_type_from_error'
]].copy()

# Convert sent_per_ip, r_sent_per_ip and limit_per_ip to int64 after rounding
final_data['sent_per_ip'] = final_data['sent_per_ip'].round().astype('int64')
final_data['r_sent_per_ip'] = final_data['r_sent_per_ip'].round().astype('int64')
final_data['limit_per_ip'] = final_data['limit_per_ip'].round().astype('int64')

# Display the head of the final DataFrame
display(final_data.head())

# Display info to check data types and non-null counts
final_data.info()

"""### Explanation of `final_data` DataFrame

The `final_data` DataFrame is the culmination of all the processing steps, providing a detailed, IP-level view of campaign sending events, including associated errors. Each row in this DataFrame represents a specific IP address's activity for a particular campaign at a given time.

Here's a breakdown of the key columns and an example:

*   **`campaign_id`**: A unique identifier for the marketing campaign.
*   **`server`**: The specific server (`s_cmh11_1341`, `s_cmh11_1343`, etc.) that handled the sending event.
*   **`ip`**: The individual IP address (`192.227.72.165`, `51.254.12.38`, etc.) from which emails were sent.
*   **`datetime_gride`**: The timestamp of the campaign event, derived from the `gride` data.
*   **`sent_detail`**: The total number of emails *attempted* to be sent by all IPs for that specific campaign event (from the original `detail` data).
*   **`r_sent_detail`**: The total number of emails *actually sent/received* by all IPs for that specific campaign event (from the original `detail` data).
*   **`sent_per_ip`**: The estimated number of emails *attempted* to be sent by this *individual IP* for this event. This is calculated by distributing `sent_detail` proportionally across all IPs involved in the event.
*   **`r_sent_per_ip`**: The estimated number of emails *actually sent/received* by this *individual IP* for this event. This is calculated by distributing `r_sent_detail` proportionally across all IPs involved in the event.
*   **`offset`**: The starting point in the mailing list for this sending block.
*   **`limit`**: The maximum number of emails intended to be sent in this particular block for the entire group of IPs.
*   **`limit_per_ip`**: The estimated maximum number of emails intended to be sent by this *individual IP* for this event. This is calculated by distributing `limit` proportionally across all IPs involved in the event.
*   **`error_type_from_error`**: The specific error type detected for this IP, if any, from the `Drop.json` data. If no error was found, it's 'No error'.
*   **`outSum`**: The total count of emails affected by a specific error event, taken from the `Drop` data. This is typically applicable at the campaign level, so it might be `NaN` if no specific error event matched or if it doesn't apply directly to the IP.

### Example Row Explanation:

Let's take the first row from the `final_data` output:

| campaign_id | server       | ip             | datetime_gride      | sent_detail | r_sent_detail | sent_per_ip | r_sent_per_ip | offset | limit | limit_per_ip | outSum | error_type_from_error |
|-------------|--------------|----------------|---------------------|-------------|---------------|-------------|---------------|--------|-------|--------------|--------|-----------------------|
| 25435709    | s_cmh11_1341 | 192.227.72.165 | 2026-04-08 01:22:44 | 3194        | 3195          | 1597        | 1598          | 352300 | 82550 | 41275        | NaN    | No error              |

This row tells us:

*   **Campaign ID `25435709`**: This event belongs to campaign ID 25435709.
*   **Server `s_cmh11_1341`**: The sending was handled by server `s_cmh11_1341`.
*   **IP `192.227.72.165`**: Specifically, the IP address `192.227.72.165` was involved.
*   **Time `2026-04-08 01:22:44`**: This event occurred at this timestamp.
*   **Total Campaign Sends `3194` (sent_detail) and `3195` (r_sent_detail)**: For this campaign event, a total of 3194 emails were attempted to be sent, and 3195 were actually received across all IPs managed by this server for this campaign event.
*   **IP's Share `1597` (sent_per_ip) and `1598` (r_sent_per_ip)**: Our calculations estimate that the IP `192.227.72.165` attempted to send 1597 emails and 1598 were received. The verification step indicated no significant deviations, meaning the sum of `sent_per_ip` and `r_sent_per_ip` for all IPs within a group should match `sent_detail` and `r_sent_detail`.
*   **Offset `352300`**: This indicates the starting point in the mailing list for this sending block.
*   **Limit `82550`**: This is the total maximum number of emails intended for this entire sending block.
*   **Limit per IP `41275`**: This is the estimated maximum number of emails intended for *this specific IP* within this sending block.
*   **No Error**: For this specific IP and event, no error was detected from the `Drop` data (`error_type_from_error` is 'No error'). Consequently, `outSum` is `NaN`.
"""

# final_data.to_excel('/content/final_data.xlsx', index=False)
# from google.colab import files
# files.download('/content/final_data.xlsx')

"""These commented-out lines provide the functionality to save the `final_data` DataFrame to an Excel file (`final_data.xlsx`) and download it from the Colab environment. This allows for easy access and sharing of the processed dataset.

### Summary of Data Processing

We have successfully performed the following steps:

**1. Detail Data Processing (`detail_clean` DataFrame):**
- Loaded `DataDetail.csv`.
- Selected and renamed key columns: `FK_ID` to `campaign_id`, `Date` to `raw_date`, `Sent` to `sent_detail`, `R.Sent` to `r_sent_detail`, `Offset` to `offset`, `Limit` to `limit`, `Server` to `server`, `Ips` to `ips_raw`.
- Cleaned string columns by stripping whitespace.
- Converted `raw_date` to `datetime` objects, extracting `date_only` and `time_only`.
- Transformed `ips_raw` into `ips_list` (a list of IPs) and calculated `nb_ips`.
- Converted relevant columns to numeric types.
- Sorted the data by `server`, `datetime`, and `campaign_id`.

**2. Gride Data Processing (`gride_clean` DataFrame):**
- Loaded `DataGride.csv`.
- Selected and renamed key columns: `Date` to `raw_gride_date`, `ID` to `campaign_id`, `Sent` to `sent_gride`, `R.Sent` to `r_sent_gride`, `Profile` to `profile`, `Server(s)` to `servers_raw`.
- Cleaned string columns by stripping whitespace.
- Converted `raw_gride_date` to `datetime_gride`.
- Converted relevant columns to numeric types.
- Extracted individual servers from `servers_raw` into `servers_list` and calculated `nb_servers`.

**3. Drop Data Processing (`drop_for_merge` DataFrame):**
- Loaded `Drop.json`.
- Selected and renamed key columns: `byIp` to `by_ip`, `fullMessage` to `full_message`, `reportTime` to `raw_report_time`, `ipMap` to `ip_map_raw`.
- Cleaned string columns by stripping whitespace.
- Converted `raw_report_time` to `datetime_drop`.
- Extracted `servers_drop_list` and `nb_servers_drop` from `full_message`.
- Extracted `ips_list_drop` and `nb_ips_drop` from `ip_map_raw`.
- Identified and extracted `error_detail` and `nb_errors_detected` from `full_message` based on predefined patterns.
- Converted relevant columns to numeric types.
- Transformed `ip_map_raw` to `ip_errors` and then exploded to `drop_final` to get individual IP-error pairs (`ip_from_error`, `error_type_from_error`).
- Created `drop_for_merge` with selected columns, extracted a single `server` name from `servers_drop_list`, and renamed `ip_from_error` to `ip`. `totalIps` was converted to numeric.

**4. Merging and IP-Level Distribution (`final_data` DataFrame):**
- Initial merge between `detail_clean` and `gride_clean` on `campaign_id` to create `final1`.
- Exploded `final1` on `ips_list` to create `final1_V2` for IP-level analysis.
- Performed a time-based `merge_asof` between `final1_V2` and `drop_for_merge` on `server`, `ip`, and datetime columns (`datetime_gride`, `datetime_drop`) with a `20min` tolerance.
- Filled `NaN` values in `error_type_from_error` with 'No error'.
- Implemented `calculate_ip_distribution` to proportionally distribute `sent_detail`, `r_sent_detail`, and `limit` across all IPs within each `campaign_id`, `server`, and `datetime_gride` group, creating `sent_per_ip`, `r_sent_per_ip`, and `limit_per_ip`.
- Verified that the sum of `sent_per_ip`, `r_sent_per_ip`, and `limit_per_ip` for each group matches the original `sent_detail`, `r_sent_detail`, and `limit` with negligible deviation.
- Selected a final set of relevant columns into `final_data` for consistency and usability.

This `final_data` DataFrame is now clean, merged, and ready for comprehensive analysis.

This markdown cell provides a comprehensive summary of all the data processing steps undertaken in the notebook, from initial data loading and cleaning for each source file to the final merging and IP-level distribution. It serves as a clear recap of the entire pipeline, highlighting the transformations and key outcomes at each stage. The `final_data` DataFrame is the result of this thorough processing, ready for further analysis.
"""

final_data.columns

