# -*- coding: utf-8 -*-
"""PFE_9_ml_recommendation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAnN-Pgz0hbLpY8b2nzPR7ZwlLdS-ZOT

# PFE_9_ml_recommendation_model.ipynb

## Objective

Train ML models to predict the best initial sending strategy for a new IP:

- initial_volume (first_sent_per_ip)
- drops_per_day
- growth_rate
- time_gap_min
- maximum_safe_volume

## STEP 1 — Import libraries

This step imports all the necessary Python libraries for data manipulation, machine learning, and visualization. These libraries provide the tools needed to load, process, train models, and evaluate the recommendation system.
"""

# Core libraries for data manipulation and numerical operations
import pandas as pd
import numpy as np
import os
import joblib

# Scikit-learn for machine learning models and utilities
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

# Libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Configure display options for pandas DataFrames
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

"""## STEP 2 — Load Excel or CSV files

In this step, we load the two primary datasets provided: `initial_behavior_summary.xlsx` and `df_ml.xlsx`. These datasets contain historical data about IP sending behavior, which will be used to train our machine learning models. Ensure that the files are present in the specified paths.
"""

# Load initial_behavior_summary data
initial_behavior_summary = pd.read_excel('/content/initial_behavior_summary.xlsx')

# Load df_ml data
df_ml = pd.read_excel('/content/df_ml.xlsx')

# Display the first few rows of each DataFrame to verify successful loading
print("Initial Behavior Summary Head:")
display(initial_behavior_summary.head())

print("\ndf_ml Head:")
display(df_ml.head())

"""## STEP 3 — Convert datetime columns

This step focuses on converting relevant columns in both DataFrames to datetime objects. Correct data types are crucial for time-series analysis and accurate feature engineering. We'll identify columns that represent dates or timestamps and convert them using `pd.to_datetime`.
"""

# Define datetime columns for initial_behavior_summary
datetime_cols_initial_behavior = ['first_used_at', 'first_error_day', 'first_netblock_day']

# Convert columns to datetime in initial_behavior_summary
for col in datetime_cols_initial_behavior:
    initial_behavior_summary[col] = pd.to_datetime(initial_behavior_summary[col], errors='coerce')

# Define datetime columns for df_ml
datetime_cols_df_ml = ['datetime_gride']

# Convert columns to datetime in df_ml
for col in datetime_cols_df_ml:
    df_ml[col] = pd.to_datetime(df_ml[col], errors='coerce')

# Display info to verify data types
print("Initial Behavior Summary Info after datetime conversion:")
initial_behavior_summary.info()

print("\ndf_ml Info after datetime conversion:")
df_ml.info()

"""## STEP 4 — Select safe historical IPs

To build a recommendation system for *safe* initial sending patterns, we need to filter our historical data to include only IPs that had a successful launch and did not encounter any immediate errors. This ensures our models learn from positive examples, leading to robust and reliable recommendations.

We define 'safe' based on the following criteria:
- `first_launch_success` is True (or 1).
- `first_error` is null (indicating no early errors).

If these criteria are not directly available, we infer safety based on the absence of specific error flags (`spf_error`, `dkim_error`, `netblock_error`) during the initial phase and a reasonable `safe_duration_days`.
"""

# Identify error columns in df_ml to check for initial errors
error_columns_in_df_ml = ['spf_error', 'dkim_error', 'netblock_error']

# Aggregate df_ml to identify IPs with any error
# If any of the error columns are True for an IP, mark it as having an error
first_error_time = df_ml[df_ml[error_columns_in_df_ml].any(axis=1)].groupby('ip')['datetime_gride'].min().reset_index()
first_error_time.rename(columns={'datetime_gride': 'first_error_datetime'}, inplace=True)

# Merge this back into initial_behavior_summary to get error timestamps
ip_data = initial_behavior_summary[['ip', 'first_used_at']].copy()
ip_data = pd.merge(ip_data, first_error_time, on='ip', how='left')

# Determine if an IP had an error before its first launch success (if applicable) or generally any error
# For simplicity, we'll mark an IP as 'has_error' if 'first_error_datetime' is not NaT
ip_data['has_error'] = ip_data['first_error_datetime'].notna()

# Filter initial_behavior_summary to select safe IPs
# Criteria for 'safe' IPs:
# 1. `first_launch_success` is 1
# 2. No `first_error_datetime` (or it's after a 'safe duration' if we were to define one)

# For this example, we'll use `first_launch_success` and the absence of `first_error_datetime`
# If `first_launch_success` is not available, we would use the `has_error` flag directly.

# Let's check for 'first_launch_success' column first
if 'first_launch_success' in initial_behavior_summary.columns:
    # Using a mask for clarity
    no_error_mask = ~ip_data['has_error'] # IPs that never had an error recorded
    has_error_mask = ip_data['has_error']

    # Further filter initial_behavior_summary for IPs that had no errors from ip_data
    # Also ensure first_launch_success (if available) is True/1
    safe_ips_mask = (initial_behavior_summary['first_launch_success'] == 1) & (initial_behavior_summary['ip'].isin(ip_data[no_error_mask]['ip']))
    training_df = initial_behavior_summary[safe_ips_mask].copy()

    # Also create a filtered_df for IPs with errors to analyze later if needed
    ips_with_errors_mask = initial_behavior_summary['ip'].isin(ip_data[has_error_mask]['ip'])
    filtered_df = initial_behavior_summary[ips_with_errors_mask].copy()
    print(f"Number of safe IPs: {len(training_df)}")
    print(f"Number of IPs with errors: {len(filtered_df)}")
else:
    # If 'first_launch_success' is not present, rely solely on the derived 'has_error'
    no_error_mask = ~ip_data['has_error'] # IPs that never had an error recorded
    training_df = initial_behavior_summary[initial_behavior_summary['ip'].isin(ip_data[no_error_mask]['ip'])].copy()
    has_error_mask = ip_data['has_error']
    filtered_df = initial_behavior_summary[initial_behavior_summary['ip'].isin(ip_data[has_error_mask]['ip'])].copy()
    print(f"'first_launch_success' column not found. Filtering based on error flags only.")
    print(f"Number of safe IPs (no errors): {len(training_df)}")
    print(f"Number of IPs with errors: {len(filtered_df)}")

# Display the first few rows of the training_df
print("\nSafe IPs (training_df) Head:")
display(training_df.head())

"""## STEP 5 — Aggregate `df_ml` per IP

To create a single row per IP for training, we need to aggregate the detailed `df_ml` data. This involves calculating summary statistics for key metrics like `drops_per_day`, `growth_rate`, `time_gap_min`, and `limit_usage_ratio` for each IP. These aggregated features will provide a concise representation of an IP's behavior over time.
"""

# Aggregate `df_ml` to get average `drops_per_day` for each IP
# The `drops_per_day` is already pre-calculated in df_ml, so we just take the mean per IP.
avg_drops_per_day_df = df_ml.groupby('ip')['drops_per_day'].mean().reset_index()
avg_drops_per_day_df.rename(columns={'drops_per_day': 'avg_drops_per_day'}, inplace=True)

# Aggregate other relevant features from `df_ml` per IP
# This will capture the average behavior characteristics over the IP's lifetime
agg_features = {
    'growth_rate': ('growth_rate', 'mean'),
    'time_gap_min': ('time_gap_min', 'mean'),
    'limit_usage_ratio': ('limit_usage_ratio', 'mean'),
    'sent_ratio': ('sent_ratio', 'mean')
}
df_ml_agg = df_ml.groupby('ip').agg(
    avg_growth_rate=pd.NamedAgg(column='growth_rate', aggfunc='mean'),
    avg_time_gap_min=pd.NamedAgg(column='time_gap_min', aggfunc='mean'),
    avg_limit_usage_ratio=pd.NamedAgg(column='limit_usage_ratio', aggfunc='mean'),
    avg_sent_ratio=pd.NamedAgg(column='sent_ratio', aggfunc='mean')
).reset_index()

# Merge avg_drops_per_day_df with df_ml_agg
df_ml_agg = pd.merge(df_ml_agg, avg_drops_per_day_df, on='ip', how='left')


print("Aggregated df_ml (df_ml_agg) Head:")
display(df_ml_agg.head())

"""## STEP 6 — Merge datasets into one training dataset

Now, we combine the `training_df` (which contains safe IPs and their initial behavior) with the aggregated features from `df_ml_agg`. This merge creates a comprehensive dataset where each row represents a unique safe IP, enriched with both its initial setup characteristics and its average behavioral patterns. This combined dataset, `merged_df`, will be the foundation for training our machine learning models.
"""

# Merge the training_df (safe IPs from initial_behavior_summary) with df_ml_agg
# We use a left merge to keep all safe IPs from training_df and add their aggregated df_ml features.
merged_df = pd.merge(training_df, df_ml_agg, on='ip', how='left')

# Handle any potential NaN values that might result from the merge if an IP in training_df
# wasn't present in df_ml_agg (though this shouldn't happen with correct data, it's good practice).
# For numerical columns, fill NaNs with 0 or the mean/median depending on context.
# Here, we'll fill with 0, assuming missing aggregated values mean no activity or 0 for rate-based metrics.

# Identify numerical columns that might have NaNs after merge
# (excluding 'ip', and other identifier columns)
numerical_cols_to_fill = ['avg_growth_rate', 'avg_time_gap_min', 'avg_limit_usage_ratio', 'avg_sent_ratio', 'avg_drops_per_day']
for col in numerical_cols_to_fill:
    if col in merged_df.columns:
        merged_df[col] = merged_df[col].fillna(0)

print("Merged DataFrame (merged_df) Head:")
display(merged_df.head())
print(f"Shape of merged_df: {merged_df.shape}")

"""## STEP 7 — Select features and targets

In this crucial step, we define the input features (X) and the output targets (y) for our machine learning models. Each target will have its own dedicated model. The features will consist of characteristics that are known *before* an IP is launched, or early behavior metrics that are predictive of future success.

**Targets to predict:**
- `y_initial_volume` = `first_sent_per_ip`
- `y_growth_rate` = `average_safe_growth_rate` (from `initial_behavior_summary`) or `avg_growth_rate` (from `df_ml_agg`)
- `y_max_safe_volume` = `maximum_safe_volume`
- `y_time_gap` = `average_time_gap_min` (from `initial_behavior_summary`) or `avg_time_gap_min` (from `df_ml_agg`)
- `y_drops_per_day` = `avg_drops_per_day` (from `df_ml_agg`)

**Features (X):**
We'll select features that would be available for a new IP or are early indicators. These can include `first_limit`, `first_offset`, `avg_limit_usage_ratio`, `avg_sent_ratio`, `safe_duration_days`, `avg_time_gap_min` (if we consider a short initial observation period). For simplicity, we'll start with a set of features from the merged dataset that are most likely to be relevant.

We will also perform a train-test split to evaluate our models on unseen data.
"""

# Define the target variables for prediction
# Using the aggregated values from merged_df as these represent the 'safe' outcomes.
targets = {
    'initial_volume': merged_df['first_sent_per_ip'],
    'growth_rate': merged_df['avg_growth_rate'], # Using aggregated growth rate from df_ml_agg
    'max_safe_volume': merged_df['maximum_safe_volume'],
    'time_gap_min': merged_df['avg_time_gap_min'], # Using aggregated time gap from df_ml_agg
    'drops_per_day': merged_df['avg_drops_per_day'] # Using aggregated drops per day from df_ml_agg
}

# Define the features (X) for the models
# These features should represent initial characteristics or early behavior indicators.
# Let's consider features that are known or can be estimated early in an IP's lifecycle.
features = [
    'first_limit',              # Initial sending limit set for the IP
    'first_offset',             # Initial offset (start time delay)
    'avg_limit_usage_ratio',    # Average usage ratio of the limit
    'avg_sent_ratio',           # Average sent ratio
    'safe_duration_days',       # How long the IP was 'safe' for
    'average_time_gap_min'      # Average time gap from initial_behavior_summary
]

# Ensure all features exist in merged_df
existing_features = [f for f in features if f in merged_df.columns]
missing_features = [f for f in features if f not in merged_df.columns]

if missing_features:
    print(f"Warning: The following features are missing from merged_df: {missing_features}. They will be skipped.")

X = merged_df[existing_features]

# Drop rows where any target value might be NaN if not handled earlier
# This ensures target series are aligned with X and don't contain NaNs
# It's better to drop here rather than training on incomplete targets

# Initialize a dictionary to store split data for each target
X_train_dict = {}
X_test_dict = {}
y_train_dict = {}
y_test_dict = {}

for name, target_series in targets.items():
    # Temporarily rename the target_series to match the 'name' key for concatenation
    # This ensures the column in temp_df has the correct name for later selection
    target_series_renamed = target_series.rename(name)

    temp_df = pd.concat([X, target_series_renamed], axis=1).dropna()
    X_aligned = temp_df[existing_features]
    y_aligned = temp_df[name]

    # Split data into training and testing sets
    # Using a fixed random_state for reproducibility
    X_train, X_test, y_train, y_test = train_test_split(X_aligned, y_aligned, test_size=0.2, random_state=42)

    X_train_dict[name] = X_train
    X_test_dict[name] = X_test
    y_train_dict[name] = y_train
    y_test_dict[name] = y_test

    print(f"\n--- Target: {name} ---")
    print(f"X_train shape: {X_train.shape}")
    print(f"y_train shape: {y_train.shape}")
    print(f"X_test shape: {X_test.shape}")
    print(f"y_test shape: {y_test.shape}")

print("\nFeatures used (X Head):")
display(X.head())

"""## STEP 13 — Export models and final training dataset

To ensure our trained models and the processed training data can be easily reused and deployed, we will export them. The models will be saved using `joblib`, and the `merged_df` (our final training dataset) will be saved as a CSV file. This allows for quick loading and application of the recommendation system without needing to re-run the entire pipeline.
"""

# Create a directory to save models if it doesn't exist
output_models_dir = './trained_models'
os.makedirs(output_models_dir, exist_ok=True)

saved_model_paths = {}

print("\n--- Exporting Trained Models ---")
for target_name, models_for_target in trained_models.items():
    # For simplicity, we'll save the best performing model for each target
    # (e.g., RandomForestRegressor, or determine based on evaluation_df if needed)

    # Get the best model for the current target based on R2 score from evaluation_df
    best_model_info = evaluation_df[evaluation_df['Target'] == target_name].sort_values(by='R2', ascending=False).iloc[0]
    best_model_name = best_model_info['Model']

    model_to_save = models_for_target[best_model_name]

    filename = f'model_{target_name}.pkl'
    filepath = os.path.join(output_models_dir, filename)
    joblib.dump(model_to_save, filepath)
    saved_model_paths[target_name] = filepath
    print(f"Exported {best_model_name} for {target_name} to {filepath}")

print("\n--- Exporting Final Training Dataset (merged_df) ---")
output_filename = 'ml_recommendation_training_data.csv'
merged_df.to_csv(output_filename, index=False)
print(f"Exported merged_df to {output_filename}")

print("All models and data exported successfully!")

"""## STEP 12 — Test the function with an example new IP

To demonstrate the `recommend_new_ip_strategy` function, we'll create a hypothetical new IP with a set of input features. The function will then use the trained models to predict the recommended values for `initial_volume`, `drops_per_day`, `growth_rate`, `time_gap_min`, and `maximum_safe_volume` for this new IP.
"""

# Example input for a new IP
# These values should be based on what's known or assumed for a new IP before launch.
# Ensure the columns match the features used in training (existing_features).

sample_input_data = {
    'first_limit': [80000],  # Example: A higher initial limit
    'first_offset': [20000], # Example: A moderate offset
    'avg_limit_usage_ratio': [0.5], # Example: Assumed moderate limit usage
    'avg_sent_ratio': [0.9], # Example: Assumed high sent ratio
    'safe_duration_days': [3], # Example: Assumed initial safe duration
    'average_time_gap_min': [30] # Example: Assumed average time gap
}
sample_df = pd.DataFrame(sample_input_data)

# Filter sample_df to only include the features that were used in training
sample_df_filtered = sample_df[existing_features]

print("Sample input for a new IP:")
display(sample_df_filtered)

# Get recommendations for the new IP
recommendation_df = recommend_new_ip_strategy(
    new_ip_features=sample_df_filtered,
    trained_models=trained_models,
    target_features=existing_features
)

print("\n--- Recommended Strategy for New IP ---")
display(recommendation_df)

"""## STEP 11 — Create function `recommend_new_ip_strategy()`

This function will serve as the core of our recommendation system. It will take in initial characteristics of a new IP (or a set of features that can be estimated for a new IP) and use the trained machine learning models to predict the recommended sending strategy (initial volume, growth rate, etc.).
"""

def recommend_new_ip_strategy(new_ip_features: pd.DataFrame, trained_models: dict, target_features: list) -> pd.DataFrame:
    """
    Recommends an initial sending strategy for a new IP based on trained ML models.

    Args:
        new_ip_features (pd.DataFrame): DataFrame containing features for the new IP.
                                        Must have columns matching the training features.
        trained_models (dict): Dictionary of trained models, structured as
                               {'target_name': {'model_name': model_object}}.
        target_features (list): List of feature names that were used for training.

    Returns:
        pd.DataFrame: A DataFrame with recommended values for each target variable.
    """
    recommendations = {}

    # Ensure the input features match the training features
    # We need to ensure that the new_ip_features DataFrame has all the columns
    # that were used for training, even if some values are placeholders for a new IP.
    # For this example, let's assume `new_ip_features` comes with all necessary columns.

    # Filter `new_ip_features` to only include the `target_features`
    input_features_for_prediction = new_ip_features[target_features]

    for target_name, models_for_target in trained_models.items():
        # For simplicity, we'll use the 'best' model as determined by R2,
        # or just pick RandomForestRegressor if R2 info isn't directly available here.
        # In a real-world scenario, you might have a mechanism to pick the best model.

        # Get the best model for the current target from evaluation_df
        best_model_info = evaluation_df[evaluation_df['Target'] == target_name].sort_values(by='R2', ascending=False).iloc[0]
        best_model_name = best_model_info['Model']

        model = models_for_target[best_model_name]

        # Make prediction
        prediction = model.predict(input_features_for_prediction)[0] # [0] because we expect a single prediction
        recommendations[f'recommended_{target_name}'] = prediction

    return pd.DataFrame([recommendations])

print("Function `recommend_new_ip_strategy` created successfully.")

"""## STEP 10 — Show feature importance

Understanding feature importance helps us identify which input variables are most influential in predicting our target variables. This can provide valuable insights into the underlying dynamics of safe IP sending behavior. We'll identify the best model for each target (based on R2 score) and display its feature importances.
"""

print("\n--- Feature Importance for Best Models ---")
feature_importances_dict = {}

for target_name in targets.keys():
    # Find the best model for the current target based on R2 score
    best_model_info = evaluation_df[evaluation_df['Target'] == target_name].sort_values(by='R2', ascending=False).iloc[0]
    best_model_name = best_model_info['Model']

    model = trained_models[target_name][best_model_name]

    # Check if the model has a feature_importances_ attribute
    if hasattr(model, 'feature_importances_'):
        importances = model.feature_importances_

        # Get the feature names from the X_train_dict for the current target
        feature_names = X_train_dict[target_name].columns

        feature_importance_df = pd.DataFrame({
            'Feature': feature_names,
            'Importance': importances
        })
        feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

        feature_importances_dict[target_name] = feature_importance_df

        print(f"\nFeature Importance for {target_name} (Best Model: {best_model_name}):")
        display(feature_importance_df)

        # Plotting feature importance
        plt.figure(figsize=(10, 6))
        sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
        plt.title(f'Feature Importance for {target_name} ({best_model_name})')
        plt.tight_layout()
        plt.show()
    else:
        print(f"\n{best_model_name} for {target_name} does not have feature importances.")

"""## STEP 9 — Evaluate models

After training, it's crucial to evaluate the performance of our models on unseen data. We will use the test sets (`X_test`, `y_test`) created in Step 7. For each model and target, we'll calculate:
- **Mean Absolute Error (MAE):** The average of the absolute differences between predictions and actual values. It's a measure of prediction accuracy.
- **Mean Squared Error (MSE) / Root Mean Squared Error (RMSE):** Similar to MAE but penalizes larger errors more. RMSE is the square root of MSE and is in the same units as the target variable.
- **R-squared (R2 Score):** Represents the proportion of the variance in the dependent variable that is predictable from the independent variables. A higher R2 indicates a better fit.
"""

evaluation_results = []

print("\n--- Evaluating Models ---")
for name, models_for_target in trained_models.items():
    X_test = X_test_dict[name]
    y_test = y_test_dict[name]

    print(f"\nEvaluating models for target: {name}")
    for model_name, model in models_for_target.items():
        y_pred = model.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        r2 = r2_score(y_test, y_pred)

        evaluation_results.append({
            'Target': name,
            'Model': model_name,
            'MAE': mae,
            'RMSE': rmse,
            'R2': r2
        })

        print(f"  {model_name} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R2: {r2:.2f}")

evaluation_df = pd.DataFrame(evaluation_results)
print("\n--- Evaluation Results ---")
display(evaluation_df.sort_values(by=['Target', 'R2'], ascending=[True, False]))

"""## STEP 8 — Train ML models

In this step, we'll train a set of machine learning models for each of our defined target variables. We will use `RandomForestRegressor`, `GradientBoostingRegressor`, and `ExtraTreesRegressor`, which are powerful ensemble methods suitable for regression tasks. Each model will be trained on the `X_train` and `y_train` data corresponding to its specific target. The trained models will then be stored for later use in evaluation and prediction.
"""

# Initialize models
models = {
    'RandomForestRegressor': RandomForestRegressor(random_state=42),
    'GradientBoostingRegressor': GradientBoostingRegressor(random_state=42),
    'ExtraTreesRegressor': ExtraTreesRegressor(random_state=42)
}

trained_models = {}

# Train a model for each target variable
print("\n--- Training Models ---")
for name in targets.keys():
    print(f"Training models for target: {name}")
    X_train = X_train_dict[name]
    y_train = y_train_dict[name]

    trained_models[name] = {}
    for model_name, model in models.items():
        print(f"  Training {model_name}...")
        model.fit(X_train, y_train)
        trained_models[name][model_name] = model
        print(f"  {model_name} trained for {name}.")

print("\nAll models trained successfully!")

"""# PFE_9_ml_recommendation_model.ipynb

## Objective

Train ML models to predict the best initial sending strategy for a new IP:

- initial_volume (first_sent_per_ip)
- drops_per_day
- growth_rate
"""