# -*- coding: utf-8 -*-
"""PFE_8_initial_volume_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LM76dd67pE3J1QVtUJvu5_Vy9TMNT1Hy

# PFE_8_initial_volume_recommendation.ipynb

## Objective

Build a recommendation system for NEW IPs (cold start problem).

The system should suggest:
- initial volume
- drops per day
- growth rate
- time gap between drops
- maximum safe volume

---

This section sets up the Python environment by importing the `pandas` library, which is essential for working with data in tabular form (DataFrames). It then loads two Excel files, `first_ip_summary.xlsx` and `df_ml.xlsx`, into pandas DataFrames. Finally, it prints a confirmation message to indicate that the datasets have been successfully loaded.

## Data Loading

Loading the `first_ip_summary.xlsx` and `df_ml.xlsx` datasets into pandas DataFrames and converting the specified datetime columns.
"""

import pandas as pd

# Load first_ip_summary
first_ip_summary = pd.read_excel('/content/first_ip_summary.xlsx')

# Load df_ml
df_ml = pd.read_excel('/content/df_ml.xlsx')

print("Datasets loaded successfully.")

"""After loading the data, this step converts the `datetime_gride` column in `df_ml` and the `first_used_at` column in `first_ip_summary` to datetime objects. This is crucial for performing time-based calculations accurately. The code then displays the first few rows and information about each DataFrame to verify the successful conversion and data structure."""

# Convert datetime columns
df_ml['datetime_gride'] = pd.to_datetime(df_ml['datetime_gride'])
first_ip_summary['first_used_at'] = pd.to_datetime(first_ip_summary['first_used_at'])

print("Datetime columns converted.")

# Display first few rows and info for verification
print("\nfirst_ip_summary head:")
display(first_ip_summary.head())
print("\ndf_ml head:")
display(df_ml.head())

print("\nfirst_ip_summary info:")
first_ip_summary.info()
print("\ndf_ml info:")
df_ml.info()

"""This section calculates various behavioral metrics for each IP address. It combines `df_ml` with `first_ip_summary` to link each event to the IP's launch date. For each unique IP, it determines the 'safe period' (time without errors), the first error day, and the first netblock day. It then calculates the `safe_duration_days` (how long the IP operated without errors), `maximum_safe_volume` (highest daily volume during the safe period), `average_safe_growth_rate`, and `average_time_gap_min` for each IP. Finally, these metrics are compiled into a summary DataFrame.

## STEP 1 — COMPUTE IP BEHAVIOR METRICS
"""

# Merge df_ml with first_ip_summary to get 'first_used_at' for each event
# This is crucial for calculating safe_duration_days accurately relative to the IP's launch
df_combined = pd.merge(df_ml, first_ip_summary[['ip', 'first_used_at']], on='ip', how='left')

# Sort by IP and datetime_gride to ensure correct chronological order for calculations
df_combined = df_combined.sort_values(by=['ip', 'datetime_gride']).reset_index(drop=True)

# Initialize a dictionary to store IP behavior metrics
ip_behavior_metrics = {}

# Process each unique IP
for ip_address in df_combined['ip'].unique():
    ip_data = df_combined[df_combined['ip'] == ip_address].copy()
    first_used_at = ip_data['first_used_at'].iloc[0]

    # Identify the first error day
    # Assuming 'risk_label' != 'Safe' indicates an error
    error_events = ip_data[ip_data['risk_label'] != 'Safe']
    first_error_day = error_events['datetime_gride'].min() if not error_events.empty else pd.NaT

    # Identify the first netblock day
    netblock_events = ip_data[ip_data['netblock_error'] == 1]
    first_netblock_day = netblock_events['datetime_gride'].min() if not netblock_events.empty else pd.NaT

    # Filter data for the 'safe period' (before the first error, if any)
    if pd.isna(first_error_day):
        # If no error, the entire period is considered safe
        safe_period_data = ip_data
        duration_delta = ip_data['datetime_gride'].max() - first_used_at
    else:
        # Safe period is from first_used_at up to the moment before the first error
        safe_period_data = ip_data[ip_data['datetime_gride'] < first_error_day]
        duration_delta = first_error_day - first_used_at

    # Calculate safe_duration_days in fractional days
    # If duration_delta is negative (first_error_day < first_used_at, which shouldn't happen with min()), or 0, set to 0.
    safe_duration_days = duration_delta.total_seconds() / (24 * 3600) if duration_delta.total_seconds() > 0 else 0

    # Calculate metrics for the safe period
    maximum_safe_volume = safe_period_data['daily_volume'].max() if not safe_period_data.empty else 0
    average_safe_growth_rate = safe_period_data['growth_rate'].mean() if not safe_period_data.empty else 0
    average_time_gap_min = safe_period_data['time_gap_min'].mean() if not safe_period_data.empty else 0

    # Store computed metrics
    ip_behavior_metrics[ip_address] = {
        'ip': ip_address,
        'safe_duration_days': safe_duration_days,
        'first_error_day': first_error_day,
        'first_netblock_day': first_netblock_day,
        'maximum_safe_volume': maximum_safe_volume,
        'average_safe_growth_rate': average_safe_growth_rate,
        'average_time_gap_min': average_time_gap_min
    }

# Convert the dictionary to a DataFrame
ip_behavior_summary_df = pd.DataFrame.from_dict(ip_behavior_metrics, orient='index')

print("IP behavior metrics computed successfully.")
display(ip_behavior_summary_df.head())
ip_behavior_summary_df.info()

"""This step merges the `ip_behavior_summary_df` (containing the calculated IP metrics) with the `first_ip_summary` DataFrame. This creates a comprehensive summary, `initial_behavior_summary`, that includes both initial launch information and detailed behavioral metrics for each IP. This combined DataFrame is then used for the next steps in identifying safe-start IPs.

## STEP 2 — MERGE DATASETS
"""

# Merge the IP behavior summary with first_ip_summary using 'ip'
# This combines the initial launch data with the calculated behavior metrics
initial_behavior_summary = pd.merge(
    first_ip_summary,
    ip_behavior_summary_df[['ip', 'safe_duration_days', 'first_error_day', 'first_netblock_day',
                            'maximum_safe_volume', 'average_safe_growth_rate', 'average_time_gap_min']],
    on='ip',
    how='left'
)

print("Datasets merged successfully.")
display(initial_behavior_summary.head())
initial_behavior_summary.info()

# initial_behavior_summary.to_excel('/content/initial_behavior_summary.xlsx', index=False)
# from google.colab import files
# files.download('/content/initial_behavior_summary.xlsx')

initial_behavior_summary.columns

"""This crucial step identifies IPs that meet the criteria for being considered 'safe-start' IPs. It filters the `initial_behavior_summary` based on four conditions:
- `first_launch_success == 1`: The IP had a successful initial launch.
- `first_error == 'No error'`: There were no initial errors recorded.
- `first_sent_per_ip < 10000`: The initial sending volume was below a certain threshold, indicating a cautious start.
- `safe_duration_days > 0`: The IP operated for at least some period without generating any errors.

The code then prints the number of identified safe-start IPs and displays their details. A diagnostic section is included to analyze the conditions if no safe-start IPs are found, helping to understand which criteria might be too strict.

## STEP 3 — SELECT SAFE-START IPS
"""

# Define safe-start IPs based on the criteria
safe_start_ips = initial_behavior_summary[
    (initial_behavior_summary['first_launch_success'] == 1) &
    (initial_behavior_summary['first_error'] == 'No error') &
    (initial_behavior_summary['first_sent_per_ip'] < 10000) &
    (initial_behavior_summary['safe_duration_days'] > 1) # Changed from >= 1 to > 0
].copy()

print(f"Identified {len(safe_start_ips)} safe-start IPs.")
display(safe_start_ips.head())
safe_start_ips.info()

# --- DIAGNOSTIC: Analyze why no safe-start IPs were found ---

print("\n--- Analysis of Safe-Start IP Conditions ---")

# Check basic statistics for potentially problematic columns
print("\nStatistics for 'safe_duration_days':")
display(initial_behavior_summary['safe_duration_days'].describe())

print("\nStatistics for 'first_sent_per_ip':")
display(initial_behavior_summary['first_sent_per_ip'].describe())

# Check the number of IPs satisfying each individual condition
print("\nNumber of IPs satisfying individual conditions:")
cond_launch_success = initial_behavior_summary['first_launch_success'] == 1
cond_no_error = initial_behavior_summary['first_error'] == 'No error'
cond_sent_volume = initial_behavior_summary['first_sent_per_ip'] < 10000
cond_safe_duration = initial_behavior_summary['safe_duration_days'] > 0 # Changed from >= 1 to > 0

print(f"  - first_launch_success == 1: {cond_launch_success.sum()} out of {len(initial_behavior_summary)}")
print(f"  - first_error == 'No error': {cond_no_error.sum()} out of {len(initial_behavior_summary)}")
print(f"  - first_sent_per_ip < 10000: {cond_sent_volume.sum()} out of {len(initial_behavior_summary)}")
print(f"  - safe_duration_days > 0: {cond_safe_duration.sum()} out of {len(initial_behavior_summary)}")

# Check combinations of conditions to find the bottleneck
print("\nNumber of IPs satisfying combinations of conditions:")
print(f"  - (launch_success & no_error): {(cond_launch_success & cond_no_error).sum()}")
print(f"  - (launch_success & no_error & sent_volume): {(cond_launch_success & cond_no_error & cond_sent_volume).sum()}")
print(f"  - (launch_success & no_error & safe_duration): {(cond_launch_success & cond_no_error & cond_safe_duration).sum()}")
print(f"  - (ALL conditions): {(cond_launch_success & cond_no_error & cond_sent_volume & cond_safe_duration).sum()}")

print("\n--- End of Analysis ---")

# safe_start_ips.to_excel('/content/safe_start_ips.xlsx', index=False)
# from google.colab import files
# files.download('/content/safe_start_ips.xlsx')

safe_start_ips.columns

"""This step calculates the recommended values for various metrics based on the behavior of the `safe_start_ips`. It uses the median for 'initial volume', 'growth rate', 'time gap', and 'maximum safe volume' to get a central, robust estimate. For 'drops per day', it finds the mode (most frequent value) from the `df_ml` data during the safe period of these IPs. The results are then presented in a clear DataFrame called `recommendations_df`.

## STEP 4 — COMPUTE RECOMMENDATIONS
"""

# Compute recommendations from safe-start IPs
recommended_initial_volume = safe_start_ips['first_sent_per_ip'].median()
# For drops per day, we need to go back to the df_ml data for the safe IPs
# and then find the mode of drops_per_day during their safe period.
# However, the current structure of `safe_start_ips` does not directly contain `drops_per_day` aggregated.
# We need to consider how `drops_per_day` is defined and if it's per day or per event.
# From the initial problem description, it's 'drops per day', which is already aggregated daily in `df_ml`.
# Let's calculate the mode of 'drops_per_day' for the safe period of these safe_start_ips.

# Filter df_ml for the safe_start_ips
df_ml_safe_ips = df_ml[df_ml['ip'].isin(safe_start_ips['ip'])]

# Merge with initial_behavior_summary to get first_error_day for filtering safe period events
df_ml_safe_ips = pd.merge(df_ml_safe_ips, initial_behavior_summary[['ip', 'first_error_day']], on='ip', how='left')

# Filter events to only include the safe period for each IP
safe_period_events = df_ml_safe_ips[
    df_ml_safe_ips.apply(lambda row: pd.isna(row['first_error_day']) or row['datetime_gride'] < row['first_error_day'], axis=1)
]

# Calculate the mode of drops_per_day across all safe period events of safe-start IPs
# We take the first mode in case of multiple modes
recommended_drops_per_day = safe_period_events['drops_per_day'].mode()[0] if not safe_period_events['drops_per_day'].mode().empty else 0

recommended_growth_rate = safe_start_ips['average_safe_growth_rate'].median()
recommended_time_gap = safe_start_ips['average_time_gap_min'].median()
recommended_max_safe_volume = safe_start_ips['maximum_safe_volume'].median()

# Store recommendations in a DataFrame for clear display
recommendations_df = pd.DataFrame({
    'Metric': [
        'Recommended Initial Volume',
        'Recommended Drops Per Day',
        'Recommended Growth Rate',
        'Recommended Time Gap (min)',
        'Recommended Maximum Safe Volume'
    ],
    'Value': [
        recommended_initial_volume,
        recommended_drops_per_day,
        recommended_growth_rate,
        recommended_time_gap,
        recommended_max_safe_volume
    ]
})

print("Recommendations computed successfully.")
display(recommendations_df)

df_ml_safe_ips.columns

# --- DIAGNOSTIC: Analyze why no safe-start IPs were found ---

print("\n--- Analysis of Safe-Start IP Conditions ---")

# Check basic statistics for potentially problematic columns
print("\nStatistics for 'safe_duration_days':")
display(initial_behavior_summary['safe_duration_days'].describe())

print("\nStatistics for 'first_sent_per_ip':")
display(initial_behavior_summary['first_sent_per_ip'].describe())

# Check the number of IPs satisfying each individual condition
print("\nNumber of IPs satisfying individual conditions:")
cond_launch_success = initial_behavior_summary['first_launch_success'] == 1
cond_no_error = initial_behavior_summary['first_error'] == 'No error'
cond_sent_volume = initial_behavior_summary['first_sent_per_ip'] < 10000
cond_safe_duration = initial_behavior_summary['safe_duration_days'] >= 1

print(f"  - first_launch_success == 1: {cond_launch_success.sum()} out of {len(initial_behavior_summary)}")
print(f"  - first_error == 'No error': {cond_no_error.sum()} out of {len(initial_behavior_summary)}")
print(f"  - first_sent_per_ip < 10000: {cond_sent_volume.sum()} out of {len(initial_behavior_summary)}")
print(f"  - safe_duration_days >= 1: {cond_safe_duration.sum()} out of {len(initial_behavior_summary)}")

# Check combinations of conditions to find the bottleneck
print("\nNumber of IPs satisfying combinations of conditions:")
print(f"  - (launch_success & no_error): {(cond_launch_success & cond_no_error).sum()}")
print(f"  - (launch_success & no_error & sent_volume): {(cond_launch_success & cond_no_error & cond_sent_volume).sum()}")
print(f"  - (launch_success & no_error & safe_duration): {(cond_launch_success & cond_no_error & cond_safe_duration).sum()}")
print(f"  - (ALL conditions): {(cond_launch_success & cond_no_error & cond_sent_volume & cond_safe_duration).sum()}")

print("\n--- End of Analysis ---")