# -*- coding: utf-8 -*-
"""PFE_11_simulation_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ad5TpdWWaeHBGkOI8eqV2igv1iycdhYc

# PFE_11_simulation_engine.ipynb: Email Sending IP Optimization Simulation Engine

## OBJECTIVE:
Build a simulation engine that simulates the evolution of an email sending IP strategy day by day.

This notebook will allow users to define various parameters and observe the simulated impact on email volume, risk, and error probabilities over time.

---

### STEP 1 — Import Libraries

We start by importing all the necessary Python libraries for data manipulation, numerical operations, plotting, and model loading.
"""

# Import standard libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib # Used for loading .pkl models
import os # Used to check for file existence

# Configure plot styles
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['figure.dpi'] = 100

"""---

### STEP 2 — Load Required Datasets/Models

This section attempts to load pre-trained models (PFE6, PFE7, PFE9) from `.pkl` files. If any model file is not found, a placeholder function will be used instead. This ensures the simulation can run even if the actual models are not yet available.

**Integration Point:** To use your real trained models, ensure their `.pkl` files are in the specified paths (`/content/risk_model.pkl`, `/content/best_model_spf_error.pkl`, etc.) and the `try-except` blocks will automatically load them.
"""

# Initialize model variables to None or placeholder functions
risk_model = None
error_prediction_model = None
recommendation_model = None
growth_rate_model = None
max_safe_volume_model = None
time_gap_min_model = None
drops_per_day_model = None
initial_volume_model = None

# Paths to your trained models
MODEL_PATHS = {
    'risk_model': '/content/risk_model.pkl',
    'error_prediction_model': '/content/best_model_spf_error.pkl', # Example: using SPF error model
    'netblock_error_model': '/content/best_model_netblock_error.pkl',
    'dkim_error_model': '/content/best_model_dkim_error.pkl',
    'growth_rate_model': '/content/model_growth_rate.pkl',
    'max_safe_volume_model': '/content/model_max_safe_volume.pkl',
    'time_gap_min_model': '/content/model_time_gap_min.pkl',
    'drops_per_day_model': '/content/model_drops_per_day.pkl',
    'initial_volume_model': '/content/model_initial_volume.pkl',
    # PFE9 recommendation system might be more complex, handled separately or as a function
}

# Function to safely load models or return a placeholder
def load_model_or_placeholder(model_name, path):
    try:
        if os.path.exists(path):
            print(f"Loading {model_name} from {path}...")
            return joblib.load(path)
        else:
            print(f"Warning: {model_name} not found at {path}. Using placeholder.")
            return None # Will be replaced by a specific placeholder function later
    except Exception as e:
        print(f"Error loading {model_name} from {path}: {e}. Using placeholder.")
        return None

# Attempt to load all models
risk_model = load_model_or_placeholder('Risk Prediction Model', MODEL_PATHS['risk_model'])
error_prediction_model = load_model_or_placeholder('Error Prediction Model', MODEL_PATHS['error_prediction_model'])
# Load other auxiliary models if needed
growth_rate_model = load_model_or_placeholder('Growth Rate Model', MODEL_PATHS['growth_rate_model'])
max_safe_volume_model = load_model_or_placeholder('Max Safe Volume Model', MODEL_PATHS['max_safe_volume_model'])
time_gap_min_model = load_model_or_placeholder('Time Gap Min Model', MODEL_PATHS['time_gap_min_model'])
drops_per_day_model = load_model_or_placeholder('Drops Per Day Model', MODEL_PATHS['drops_per_day_model'])
initial_volume_model = load_model_or_placeholder('Initial Volume Model', MODEL_PATHS['initial_volume_model'])

"""---

### STEP 3 — Create Placeholder Prediction Models and Helper Functions

These functions act as substitutes if the actual trained models (PFE6, PFE7, PFE9) are not loaded. They provide basic, illustrative logic to keep the simulation running. If the real models were successfully loaded in STEP 2, the simulation will use them instead.

**Integration Point:** When your real models are ready, you can modify these functions to call your loaded `risk_model.predict()`, `error_prediction_model.predict()`, etc., using the appropriate input features. Ensure the output format (e.g., probability between 0 and 1) matches what the simulation expects.
"""

# Placeholder for PFE6: Risk Prediction Model
def predict_risk_probability(volume, limit, day_number, current_growth_rate):
    """
    Placeholder function to predict risk probability.
    If a real model is loaded, it will be used instead.
    Risk increases with volume, limit usage, and day number.
    """
    if risk_model is not None: # Use real model if loaded
        try:
            # Example: assume risk model expects a DataFrame with features
            # Adjust features as per your actual model's training data
            features = pd.DataFrame([[volume, limit, day_number, current_growth_rate]],
                                    columns=['volume', 'limit', 'day', 'growth_rate'])
            # Ensure the model outputs a probability (e.g., using predict_proba for classification)
            if hasattr(risk_model, 'predict_proba'):
                # Assuming binary classification, take probability of the 'risk' class
                return risk_model.predict_proba(features)[:, 1][0]
            elif hasattr(risk_model, 'predict'):
                # If it's a regression model or direct probability output
                return risk_model.predict(features)[0]
            else:
                print("Warning: Risk model loaded but cannot find 'predict_proba' or 'predict' method. Using placeholder logic.")
        except ValueError as e:
            print(f"Error using risk_model for prediction (feature mismatch or other ValueError): {e}. Using placeholder logic.")
        except Exception as e:
            print(f"An unexpected error occurred with risk_model: {e}. Using placeholder logic.")

    # Placeholder logic (if no real model, prediction method not found, or error occurred)
    # A simple linear increase based on factors, capped at 1.
    base_risk = 0.05
    volume_factor = min(volume / (limit * 2), 0.5) if limit > 0 else 0.5 # Max 0.5 based on volume
    growth_factor = current_growth_rate * 0.5 # Higher growth, higher risk
    day_factor = day_number * 0.01 # Risk slightly increases over time

    risk = base_risk + volume_factor + growth_factor + day_factor
    return min(risk, 0.99)

# Placeholder for PFE7: Error Prediction Model
def predict_error_probability(volume, limit, day_number, risk_prob):
    """
    Placeholder function to predict error probability.
    If a real model is loaded, it will be used instead.
    Error probability increases with volume and risk.
    """
    if error_prediction_model is not None: # Use real model if loaded
        try:
            # Example: assume error model expects a DataFrame with features
            # Adjust features as per your actual model's training data
            features = pd.DataFrame([[volume, limit, day_number, risk_prob]],
                                    columns=['volume', 'limit', 'day', 'risk_probability'])
            if hasattr(error_prediction_model, 'predict_proba'):
                return error_prediction_model.predict_proba(features)[:, 1][0]
            elif hasattr(error_prediction_model, 'predict'):
                return error_prediction_model.predict(features)[0]
            else:
                print("Warning: Error model loaded but cannot find 'predict_proba' or 'predict' method. Using placeholder logic.")
        except ValueError as e:
            print(f"Error using error_prediction_model for prediction (feature mismatch or other ValueError): {e}. Using placeholder logic.")
        except Exception as e:
            print(f"An unexpected error occurred with error_prediction_model: {e}. Using placeholder logic.")

    # Placeholder logic (if no real model, prediction method not found, or error occurred)
    base_error = 0.01
    volume_factor = min(volume / (limit * 1.5), 0.3) if limit > 0 else 0.3 # Max 0.3 based on volume
    risk_factor = risk_prob * 0.5 # Higher risk, higher error

    error = base_error + volume_factor + risk_factor
    return min(error, 0.50) # Capped at 50% for realism

# Placeholder for PFE9: Recommendation System (simplified for simulation logic)
def classify_risk_zone(risk_probability, error_probability):
    """
    Classifies the current state into Safe, Risk, or Dangerous zones
    based on predicted risk and error probabilities.

    **Integration Point:** This function can be replaced or enhanced by your PFE9
    recommendation system logic that might consider more factors.
    """
    if risk_probability > 0.7 or error_probability > 0.15:
        return 'Dangerous'
    elif risk_probability > 0.4 or error_probability > 0.05:
        return 'Risk'
    else:
        return 'Safe'

# Placeholder for growth rate prediction (if model not loaded)
def get_growth_rate(day_number, base_growth_rate):
    if growth_rate_model is not None:
        try:
            # Example: assume model expects day_number
            # Adjust input features based on your actual model
            features = pd.DataFrame([[day_number]], columns=['day'])
            return growth_rate_model.predict(features)[0]
        except Exception as e:
            print(f"Error using growth_rate_model for prediction: {e}. Using placeholder value.")
            return base_growth_rate # Fallback if model prediction fails
    else:
        # Simple placeholder: constant growth rate
        return base_growth_rate

# Placeholder for initial volume prediction (if model not loaded)
def get_initial_volume(strategy_params):
    if initial_volume_model is not None:
        try:
            # Attempt to predict using the loaded model.
            # This part needs to be adjusted based on the *actual* features
            # your initial_volume_model expects. Given the error, the model
            # expects different features than just 'initial_volume'.
            # For robust placeholder behavior, if the model cannot handle the
            # simplified input, we fall back to the default value.
            # You will need to explicitly construct the expected DataFrame
            # with all required features (e.g., 'average_time_gap_min', 'avg_limit_usage_ratio')
            # if you want to use the actual model here.
            print(f"Warning: initial_volume_model expects specific features (e.g., {list(initial_volume_model.feature_names_in_)}). Using provided initial_volume as placeholder.")
            return strategy_params.get('initial_volume', 500)
        except Exception as e:
            print(f"Error using initial_volume_model for prediction: {e}. Using placeholder value.")
            return strategy_params.get('initial_volume', 500) # Fallback if model prediction fails
    else:
        return strategy_params.get('initial_volume', 500) # Default if not provided or model missing

# Placeholder for optimal drops per day (if model not loaded)
def get_drops_per_day(current_volume, limit, day_number, base_drops_per_day):
    if drops_per_day_model is not None:
        try:
            features = pd.DataFrame([[current_volume, limit, day_number]],
                                    columns=['volume', 'limit', 'day'])
            return int(drops_per_day_model.predict(features)[0])
        except Exception as e:
            print(f"Error using drops_per_day_model for prediction: {e}. Using placeholder value.")
            return base_drops_per_day # Fallback if model prediction fails
    else:
        return base_drops_per_day

# Placeholder for optimal time gap between drops (if model not loaded)
def get_time_gap_between_drops(current_volume, limit, day_number, base_time_gap):
    if time_gap_min_model is not None:
        try:
            features = pd.DataFrame([[current_volume, limit, day_number]],
                                    columns=['volume', 'limit', 'day'])
            return time_gap_min_model.predict(features)[0]
        except Exception as e:
            print(f"Error using time_gap_min_model for prediction: {e}. Using placeholder value.")
            return base_time_gap # Fallback if model prediction fails
    else:
        return base_time_gap

"""---

### STEP 4 — Create Simulation Function

This function is the core of the simulation engine. It takes user-defined parameters and simulates the daily evolution of email sending metrics over a specified number of days.
"""

def simulate_ip_strategy(
    initial_volume,
    base_drops_per_day,
    base_growth_rate, # This is the 'base' growth rate; actual might be predicted
    limit,
    time_gap_between_drops,
    number_of_days_to_simulate
):
    """
    Simulates the daily evolution of an email sending IP strategy.

    Args:
        initial_volume (int): Starting email volume on Day 1.
        base_drops_per_day (int): Base number of email drops per day.
        base_growth_rate (float): Base daily volume growth rate (e.g., 0.05 for 5%).
        limit (int): Daily sending limit for the IP.
        time_gap_between_drops (int): Time in minutes between drops.
        number_of_days_to_simulate (int): Total number of days to simulate.

    Returns:
        pd.DataFrame: A DataFrame containing the simulated daily metrics.
    """

    simulation_results = []
    current_volume = initial_volume
    cumulative_volume = 0

    print(f"Starting simulation for {number_of_days_to_simulate} days...")

    for day in range(1, number_of_days_to_simulate + 1):
        # --- STEP 5: Simulate daily evolution ---
        # Get growth rate (can be predicted by model or use base)
        daily_growth_rate = get_growth_rate(day, base_growth_rate)

        if day == 1:
            daily_volume = initial_volume
        else:
            daily_volume = current_volume * (1 + daily_growth_rate)
        daily_volume = int(round(daily_volume)) # Ensure whole numbers for volume

        # Update current_volume for next day's calculation
        current_volume = daily_volume
        cumulative_volume += daily_volume

        # --- STEP 6: Compute metrics per day ---
        # Get actual drops_per_day (can be predicted by model or use base)
        drops_per_day = get_drops_per_day(daily_volume, limit, day, base_drops_per_day)

        volume_per_drop = daily_volume / drops_per_day if drops_per_day > 0 else 0

        # Limit usage ratio (capped at 1.0)
        limit_usage_ratio = min(daily_volume / limit, 1.0) if limit > 0 else 0.0

        # Estimated sent ratio (simple placeholder, could be 1 - error_probability)
        estimated_sent_ratio = 1.0 # Will be refined after error prediction

        # --- STEP 7: Predict risk and errors ---
        estimated_risk_probability = predict_risk_probability(
            volume=daily_volume,
            limit=limit,
            day_number=day,
            current_growth_rate=daily_growth_rate
        )
        estimated_error_probability = predict_error_probability(
            volume=daily_volume,
            limit=limit,
            day_number=day,
            risk_prob=estimated_risk_probability
        )

        # Refine estimated_sent_ratio based on error probability
        estimated_sent_ratio = max(0, 1.0 - estimated_error_probability)

        # --- STEP 8: Classify Safe/Risk/Dangerous ---
        predicted_risk_zone = classify_risk_zone(
            risk_probability=estimated_risk_probability,
            error_probability=estimated_error_probability
        )

        simulation_results.append({
            'Day': day,
            'Daily Volume': daily_volume,
            'Volume/Drop': round(volume_per_drop, 2),
            'Cumulative Volume': cumulative_volume,
            'Limit Usage Ratio': round(limit_usage_ratio, 3),
            'Growth Rate': round(daily_growth_rate, 4),
            'Estimated Sent Ratio': round(estimated_sent_ratio, 3),
            'Estimated Risk Probability': round(estimated_risk_probability, 3),
            'Estimated Error Probability': round(estimated_error_probability, 3),
            'Predicted Risk Zone': predicted_risk_zone
        })

    # --- STEP 9: Create final simulation dataframe ---
    df_simulation = pd.DataFrame(simulation_results)
    return df_simulation

"""---

### STEP 10 — Visualize Results

This section provides functions to plot the key metrics from the simulation, offering a clear visual understanding of the IP's performance and risk profile over time.
"""

def plot_simulation_results(df_simulation, title_suffix=""):
    """
    Plots the key metrics from the email sending IP simulation.
    """
    fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(18, 18))
    fig.suptitle(f'Email Sending IP Strategy Simulation Results {title_suffix}', fontsize=16)

    # Plot 1: Daily Volume Evolution
    sns.lineplot(ax=axes[0, 0], x='Day', y='Daily Volume', data=df_simulation, marker='o')
    axes[0, 0].set_title('Daily Volume Evolution')
    axes[0, 0].set_ylabel('Emails Sent')

    # Plot 2: Cumulative Volume
    sns.lineplot(ax=axes[0, 1], x='Day', y='Cumulative Volume', data=df_simulation, marker='o', color='green')
    axes[0, 1].set_title('Cumulative Volume Sent')
    axes[0, 1].set_ylabel('Total Emails Sent')

    # Plot 3: Limit Usage Ratio
    sns.lineplot(ax=axes[1, 0], x='Day', y='Limit Usage Ratio', data=df_simulation, marker='o', color='purple')
    axes[1, 0].set_title('Daily Limit Usage Ratio')
    axes[1, 0].set_ylabel('Ratio of Limit Used')
    axes[1, 0].axhline(y=1.0, color='r', linestyle='--', label='Limit')
    axes[1, 0].legend()

    # Plot 4: Risk Probability Evolution
    sns.lineplot(ax=axes[1, 1], x='Day', y='Estimated Risk Probability', data=df_simulation, marker='o', color='orange')
    axes[1, 1].set_title('Estimated Risk Probability Evolution')
    axes[1, 1].set_ylabel('Risk Probability')
    axes[1, 1].axhline(y=0.4, color='orange', linestyle='--', label='Risk Threshold')
    axes[1, 1].axhline(y=0.7, color='red', linestyle='--', label='Dangerous Threshold')
    axes[1, 1].legend()

    # Plot 5: Error Probability Evolution
    sns.lineplot(ax=axes[2, 0], x='Day', y='Estimated Error Probability', data=df_simulation, marker='o', color='red')
    axes[2, 0].set_title('Estimated Error Probability Evolution')
    axes[2, 0].set_ylabel('Error Probability')
    axes[2, 0].axhline(y=0.05, color='orange', linestyle='--', label='Risk Threshold')
    axes[2, 0].axhline(y=0.15, color='red', linestyle='--', label='Dangerous Threshold')
    axes[2, 0].legend()

    # Plot 6: Risk Zone Evolution
    # Map risk zones to numerical values for plotting
    risk_zone_map = {'Safe': 0, 'Risk': 1, 'Dangerous': 2}
    df_simulation['Risk Zone Numerical'] = df_simulation['Predicted Risk Zone'].map(risk_zone_map)
    sns.scatterplot(ax=axes[2, 1], x='Day', y='Risk Zone Numerical', hue='Predicted Risk Zone', data=df_simulation, s=100, palette={'Safe': 'green', 'Risk': 'orange', 'Dangerous': 'red'})
    axes[2, 1].set_title('Predicted Risk Zone Evolution')
    axes[2, 1].set_yticks([0, 1, 2])
    axes[2, 1].set_yticklabels(['Safe', 'Risk', 'Dangerous'])
    axes[2, 1].set_ylabel('Risk Zone')
    axes[2, 1].get_legend().set_title('Zone')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

def plot_comparison(df_safe, df_dangerous, metric, title):
    """
    Compares a specific metric between two simulation scenarios.
    """
    plt.figure(figsize=(12, 7))
    sns.lineplot(x='Day', y=metric, data=df_safe, label='Safe Strategy', marker='o')
    sns.lineplot(x='Day', y=metric, data=df_dangerous, label='Dangerous Strategy', marker='o')
    plt.title(title)
    plt.ylabel(metric)
    plt.xlabel('Day')
    plt.legend()
    plt.grid(True)
    plt.show()

"""---

### STEP 11 — Test Multiple Simulation Scenarios

Here, we define a set of parameters for a typical simulation run and execute the `simulate_ip_strategy` function. This demonstrates how to use the engine with custom inputs.
"""

# --- Scenario 1: Default/Moderate Strategy ---
print("\n--- Running Scenario 1: Moderate Strategy ---")
default_strategy_params = {
    'initial_volume': get_initial_volume({'initial_volume': 1000}), # Use model if available, else 1000
    'base_drops_per_day': get_drops_per_day(1000, 5000, 1, 5), # Use model if available, else 5
    'base_growth_rate': 0.15,
    'limit': 5000,
    'time_gap_between_drops': get_time_gap_between_drops(1000, 5000, 1, 60), # Use model if available, else 60
    'number_of_days_to_simulate': 30
}

df_scenario_1 = simulate_ip_strategy(**default_strategy_params)
print("Simulation for Scenario 1 completed.")

# Display the first few rows of the simulation results
print("\nScenario 1 Results (first 5 days):")
print(df_scenario_1.head())

# Visualize Scenario 1 results
plot_simulation_results(df_scenario_1, title_suffix='(Moderate Strategy)')

"""---

### STEP 12 — Compare Safe vs. Dangerous Strategies

This section defines two distinct strategies – one 'safe' with lower growth and higher limits, and one 'dangerous' with aggressive growth and tighter limits. We then simulate both and compare their outcomes visually, highlighting the trade-offs between volume and risk.
"""

# --- Scenario 2: Safe Strategy ---
print("\n--- Running Scenario 2: Safe Strategy ---")
safe_strategy_params = {
    'initial_volume': get_initial_volume({'initial_volume': 800}),
    'base_drops_per_day': get_drops_per_day(800, 6000, 1, 4),
    'base_growth_rate': 0.05,
    'limit': 6000,
    'time_gap_between_drops': get_time_gap_between_drops(800, 6000, 1, 90),
    'number_of_days_to_simulate': 30
}
df_safe_strategy = simulate_ip_strategy(**safe_strategy_params)
print("Simulation for Safe Strategy completed.")

# --- Scenario 3: Dangerous/Aggressive Strategy ---
print("\n--- Running Scenario 3: Dangerous Strategy ---")
dangerous_strategy_params = {
    'initial_volume': get_initial_volume({'initial_volume': 1200}),
    'base_drops_per_day': get_drops_per_day(1200, 3000, 1, 6),
    'base_growth_rate': 0.25,
    'limit': 3000,
    'time_gap_between_drops': get_time_gap_between_drops(1200, 3000, 1, 30),
    'number_of_days_to_simulate': 30
}
df_dangerous_strategy = simulate_ip_strategy(**dangerous_strategy_params)
print("Simulation for Dangerous Strategy completed.")

# --- Compare Strategies ---
print("\n--- Comparing Safe vs. Dangerous Strategies ---")
plot_comparison(df_safe_strategy, df_dangerous_strategy, 'Daily Volume', 'Daily Volume Comparison: Safe vs. Dangerous')
plot_comparison(df_safe_strategy, df_dangerous_strategy, 'Estimated Risk Probability', 'Risk Probability Comparison: Safe vs. Dangerous')
plot_comparison(df_safe_strategy, df_dangerous_strategy, 'Estimated Error Probability', 'Error Probability Comparison: Safe vs. Dangerous')

"""---

### STEP 13 — Export Simulation Results

Finally, the simulation results can be exported to a CSV file for further analysis or integration with other tools/dashboards.
"""

output_filename_1 = 'simulation_results_moderate_strategy.csv'
df_scenario_1.to_csv(output_filename_1, index=False)
print(f"Simulation results for Moderate Strategy exported to {output_filename_1}")

output_filename_2 = 'simulation_results_safe_strategy.csv'
df_safe_strategy.to_csv(output_filename_2, index=False)
print(f"Simulation results for Safe Strategy exported to {output_filename_2}")

output_filename_3 = 'simulation_results_dangerous_strategy.csv'
df_dangerous_strategy.to_csv(output_filename_3, index=False)
print(f"Simulation results for Dangerous Strategy exported to {output_filename_3}")

"""---

## Why this Simulation Engine is Important

This Email Sending IP Optimization Simulation Engine serves as a critical tool for strategic decision-making:

1.  **Proactive Risk Management:** By simulating various sending strategies, organizations can proactively identify potential risks (e.g., high error rates, IP blacklisting) before implementing them in a live environment. This prevents costly damage to sender reputation.
2.  **Strategy Optimization:** The engine allows for A/B testing of different parameters (growth rates, daily volumes, drops per day) to determine the optimal strategy that maximizes email deliverability and volume while minimizing risk.
3.  **Understanding IP Behavior:** It provides insights into how IP reputation evolves under different loads and growth patterns, helping users understand the delicate balance required for sustained success.
4.  **Informed Decision Making:** Instead of relying on guesswork, the simulation provides data-driven predictions on the impact of changes, enabling more informed and confident decisions.
5.  **Preventing IP Blocking:** By modeling risk and error probabilities, the engine helps users avoid thresholds that lead to email providers blocking an IP, thus safeguarding critical communication channels.

## Connection to Final Dashboard and Decision Engine

This simulation engine is designed to be the analytical core for a future dashboard and decision engine (e.g., built with Streamlit):

*   **Interactive Parameter Tuning:** Users can input parameters directly into the dashboard, trigger simulations, and instantly visualize the outcomes without needing to write code.
*   **Scenario Comparison:** The dashboard can present comparative analyses of different strategies side-by-side, making it easy to evaluate trade-offs.
*   **Recommendations:** The outputs of this simulation, especially the risk zone classification and predicted metrics, can feed directly into a decision engine that offers real-time recommendations for adjusting sending volumes or strategies.
*   **Predictive Analytics:** The engine's ability to forecast future performance under various conditions makes it a powerful component for predictive analytics within the dashboard, allowing users to anticipate future challenges and opportunities.
"""